///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using log4net;

using MCTR.DomainEntity;
using MCTR.BusinessInterface;
using MCTR.Business;

namespace MCTR.RESTService.Controllers
{

    public class BuProfileServiceController : ApiController
    {

         private readonly ILog logger;

        public BuProfileServiceController()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileBuProfileOnLoad
        ///</summary>
        ///<param></param>
        ///<returns>HttpResponseMessage </returns>


        [HttpGet]
        [ActionName("buProfileBuProfileOnLoad")]
        public HttpResponseMessage buProfileBuProfileOnLoad()
        {
            try { 
            logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfileBuProfileOnLoad()  ");

            IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
            var response = buProfileBusiness.buProfileBuProfileOnLoad();
            logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfileBuProfileOnLoad() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfileBuProfileOnLoad()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilebusinessUnitPostTextItem
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfilebusinessUnitPostTextItem")]
        public HttpResponseMessage buProfilebusinessUnitPostTextItem([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfilebusinessUnitPostTextItem() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfilebusinessUnitPostTextItem(buProfile);
                    
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfilebusinessUnitPostTextItem() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex){
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfilebusinessUnitPostTextItem()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }

        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileoffsetActivityPreTextItem
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>


        [HttpPost]
        [ActionName("buProfileoffsetActivityPreTextItem")]
        public HttpResponseMessage buProfileoffsetActivityPreTextItem([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetActivityPreTextItem() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfileoffsetActivityPreTextItem(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetActivityPreTextItem() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.MctrLogController.buProfileoffsetActivityPreTextItem()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileoffsetActivityPostTextItem
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>


        [HttpPost]
        [ActionName("buProfileoffsetActivityPostTextItem")]
        public HttpResponseMessage buProfileoffsetActivityPostTextItem([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetActivityPostTextItem() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfileoffsetActivityPostTextItem(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetActivityPostTextItem() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetActivityPostTextItem()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileoffsetProjectPreTextItem
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfileoffsetProjectPreTextItem")]
        public HttpResponseMessage buProfileoffsetProjectPreTextItem([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetProjectPreTextItem() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfileoffsetProjectPreTextItem(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetProjectPreTextItem() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetProjectPreTextItem()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileoffsetProjectPostTextItem
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfileoffsetProjectPostTextItem")]
        public HttpResponseMessage buProfileoffsetProjectPostTextItem([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetProjectPostTextItem() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfileoffsetProjectPostTextItem(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetProjectPostTextItem() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetProjectPostTextItem()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileoffsetAccountPreTextItem
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>


        [HttpPost]
        [ActionName("buProfileoffsetAccountPreTextItem")]
        public HttpResponseMessage buProfileoffsetAccountPreTextItem([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetAccountPreTextItem() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfileoffsetAccountPreTextItem(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetAccountPreTextItem() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetAccountPreTextItem()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileoffsetAccountPostTextItem
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfileoffsetAccountPostTextItem")]
        public HttpResponseMessage buProfileoffsetAccountPostTextItem([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetAccountPostTextItem() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfileoffsetAccountPostTextItem(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetAccountPostTextItem() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfileoffsetAccountPostTextItem()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileopenLOV
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfileopenLOV")]
        public HttpResponseMessage buProfileopenLOV(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfileopenLOV() ");

                IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                var response = buProfileBusiness.buProfileopenLOV(buProfile);
                logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfileopenLOV() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfileopenLOV()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilebemsAdminPostTextItem
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfilebemsAdminPostTextItem")]
        public HttpResponseMessage buProfilebemsAdminPostTextItem([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfilebemsAdminPostTextItem() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfilebemsAdminPostTextItem(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfilebemsAdminPostTextItem() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfilebemsAdminPostTextItem()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilePostQuery
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfilePostQuery")]
        public HttpResponseMessage buProfilePostQuery([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePostQuery() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfilePostQuery(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePostQuery() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePostQuery()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilePreInsert
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfilePreInsert")]
        public HttpResponseMessage buProfilePreInsert([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePreInsert() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfilePreInsert(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePreInsert() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePreInsert()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilePreUpdate
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfilePreUpdate")]
        public HttpResponseMessage buProfilePreUpdate([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePreUpdate() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfilePreUpdate(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePreUpdate() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePreUpdate()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileWhenNewFormInstance
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfileWhenNewFormInstance")]
        public HttpResponseMessage buProfileWhenNewFormInstance([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfileWhenNewFormInstance() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfileWhenNewFormInstance(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfileWhenNewFormInstance() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfileWhenNewFormInstance()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilebusinessUnitPreTextItem
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfileWhenWindowClosed")]
        public HttpResponseMessage buProfileWhenWindowClosed([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfileWhenWindowClosed() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfileWhenWindowClosed(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfileWhenWindowClosed() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfileWhenWindowClosed()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileDelete
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfileDelete")]
        public HttpResponseMessage buProfileDelete([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfileDelete() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfileDelete(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfileDelete() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : GetAdmin
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("GetAdmin")]
        //Change the Input paramaters
        public HttpResponseMessage GetAdmin(IEnumerable<MctrEmployee> employee)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.GetAdmin() ");
                IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                var response = buProfileBusiness.GetAdmin(employee);
                logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.GetAdmin() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.GetAdmin()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }

        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilePostUpdate
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfilePostUpdate")]
        public HttpResponseMessage buProfilePostUpdate([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePostUpdate() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfilePostUpdate(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePostUpdate() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePostUpdate()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilePostInsert
        ///</summary>
        ///<param name = "buProfile"></param>
        ///<returns>HttpResponseMessage </returns>

        [HttpPost]
        [ActionName("buProfilePostInsert")]
        public HttpResponseMessage buProfilePostInsert([FromBody]IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePostInsert() with request : " + buProfile);
                if (buProfile != null)
                {
                    IBuProfileBusiness buProfileBusiness = new BuprofileBusiness();
                    var response = buProfileBusiness.buProfilePostInsert(buProfile);
                    logger.Info("Response received from MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePostInsert() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception ex)
            {
                logger.Error("Excpetion occured at MCTR.RESTService.Controllers.BuProfileServiceController.buProfilePostInsert()" + ex.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError,ex.Message);
            }
        }


    }

}

