///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®

using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using log4net;
using MCTR.BusinessInterface;
using MCTR.Business;
using MCTR.DomainEntity;

namespace MCTR.RESTService.Controllers
{
    public class CreateMctrLovServiceController : ApiController
    {

         private readonly ILog logger;

        public CreateMctrLovServiceController()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }


        [HttpPost]
        [ActionName("getRgYearLOV")]
        public HttpResponseMessage getRgYearLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgYearLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgYearLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgYearLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgReasonLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>

        [HttpPost]
        [ActionName("getRgReasonLOV")]
        public HttpResponseMessage getRgReasonLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgReasonLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgReasonLOV(createMctrLov);
                logger.Info("Response received from mctrCreateFormBusiness.getRgReasonLOV() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgApplLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>

        [HttpPost]
        [ActionName("getRgApplLOV")]
        public HttpResponseMessage getRgApplLOV([FromBody] IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgApplLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgApplLOV(createMctrLov);
                logger.Info("Response received from mctrCreateFormBusiness.getRgApplLOV() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgSuperLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>

        [HttpPost]
        [ActionName("getRgSuperLOV")]
        public HttpResponseMessage getRgSuperLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgSuperLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgSuperLOV(createMctrLov);
                logger.Info("Response received from mctrCreateFormBusiness.getRgSuperLOV() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
           
            
        }

        [HttpGet]
        [ActionName("getRgApprSuperLOV")]
        public HttpResponseMessage getRgApprSuperLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgSuperLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgApprSuperLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgSuperLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgFinCtlLOV")]
        public HttpResponseMessage getRgFinCtlLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgSuperLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgFinCtlLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgSuperLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpGet]
        [ActionName("getRgApprFinCtlLOV")]
        public HttpResponseMessage getRgApprFinCtlLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgSuperLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgApprFinCtlLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgSuperLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgAcctLOV")]
        public HttpResponseMessage getRgAcctLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgSuperLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgAcctLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgSuperLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpGet]
        [ActionName("getRgApprAcctLOV")]
        public HttpResponseMessage getRgApprAcctLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgSuperLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgApprAcctLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgSuperLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgLbrAcctLOV")]
        public HttpResponseMessage getRgLbrAcctLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgSuperLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgLbrAcctLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgSuperLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpGet]
        [ActionName("getRgApprLbrAcctLOV")]
        public HttpResponseMessage getRgApprLbrAcctLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgSuperLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgApprLbrAcctLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgSuperLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }


        [HttpPost]
        [ActionName("getRgMatlAcctLOV")]
        public HttpResponseMessage getRgMatlAcctLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgSuperLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgMatlAcctLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgSuperLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpGet]
        [ActionName("getRgMatlAcctLOV")]
        public HttpResponseMessage getRgApprMatlAcctLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgApprMatlAcctLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgApprMatlAcctLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgApprMatlAcctLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgCostAcctLOV")]
        public HttpResponseMessage getRgCostAcctLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgCostAcctLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgCostAcctLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgCostAcctLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }


        [HttpGet]
        [ActionName("getRgApprCostAcctLOV")]
        public HttpResponseMessage getRgApprCostAcctLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgCostAcctLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgApprCostAcctLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgCostAcctLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgSrAcctLOV")]
        public HttpResponseMessage getRgSrAcctLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgSrAcctLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgSrAcctLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgSrAcctLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpGet]
        [ActionName("getRgApprSrAcctLOV")]
        public HttpResponseMessage getRgApprSrAcctLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgApprSrAcctLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgApprSrAcctLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgSrAcctLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgLiBemsLOV")]
        public HttpResponseMessage getRgLiBemsLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgLiBemsLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgLiBemsLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgLiBemsLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpGet]
        [ActionName("getRgRejectLOV")]
        public HttpResponseMessage getRgRejectLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgRejectLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgRejectLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgRejectLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgProjFromLOV")]
        public HttpResponseMessage getRgProjFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgProjFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgProjFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgProjFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgProjFromPromptLOV")]
        public HttpResponseMessage getRgProjFromPromptLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgProjFromPromptLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgProjFromPromptLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgProjFromPromptLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgTransFromLOV")]
        public HttpResponseMessage getRgTransFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgTransFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgTransFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgTransFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgHomeDeptFromLOV")]
        public HttpResponseMessage getRgHomeDeptFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgHomeDeptFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgHomeDeptFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgHomeDeptFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgHomeDeptLocFromLOV")]
        public HttpResponseMessage getRgHomeDeptLocFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgHomeDeptLocFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgHomeDeptLocFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgHomeDeptLocFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgListHomeDeptFromLOV")]
        public HttpResponseMessage getRgListHomeDeptFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgListHomeDeptFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgListHomeDeptFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgListHomeDeptFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }
        [HttpPost]
        [ActionName("getRgHomeLocFromLOV")]
        public HttpResponseMessage getRgHomeLocFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgHomeLocFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgHomeLocFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgHomeLocFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgListHomeLocFromLOV")]
        public HttpResponseMessage getRgListHomeLocFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgListHomeLocFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgListHomeLocFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgListHomeLocFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgClassCodeFromLOV")]
        public HttpResponseMessage getRgClassCodeFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgClassCodeFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgClassCodeFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgClassCodeFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgListClassCodeFromLOV")]
        public HttpResponseMessage getRgListClassCodeFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgListClassCodeFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgListClassCodeFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgListClassCodeFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgWorkDeptFromLOV")]
        public HttpResponseMessage getRgWorkDeptFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgWorkDeptFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgWorkDeptFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgWorkDeptFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgWorkDeptLocFromLOV")]
        public HttpResponseMessage getRgWorkDeptLocFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgWorkDeptLocFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgWorkDeptLocFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgWorkDeptLocFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }


        [HttpPost]
        [ActionName("getRgListWorkDeptFromLOV")]
        public HttpResponseMessage getRgListWorkDeptFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgListWorkDeptFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgListWorkDeptFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgListWorkDeptFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("getRgWorkLocFromLOV")]
        public HttpResponseMessage getRgWorkLocFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgWorkLocFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgWorkLocFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgWorkLocFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgListWorkLocFromLOV")]
        public HttpResponseMessage getRgListWorkLocFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgListWorkLocFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgListWorkLocFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgListWorkLocFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgRscFromLOV")]
        public HttpResponseMessage getRgRscFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgRscFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgRscFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgRscFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgWpdFromLOV")]
        public HttpResponseMessage getRgWpdFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgWpdFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgWpdFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgWpdFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgBulkFromLOV")]
        public HttpResponseMessage getRgBulkFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgBulkFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgBulkFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgBulkFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgCecEpFromLOV")]
        public HttpResponseMessage getRgCecEpFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgCecEpFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgCecEpFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgCecEpFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgListCecEpFromLOV")]
        public HttpResponseMessage getRgListCecEpFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgListCecEpFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgListCecEpFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgListCecEpFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgProjToLOV")]
        public HttpResponseMessage getRgProjToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgProjToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgProjToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgProjToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }
        [HttpPost]
        [ActionName("getRgProjToPromptLOV")]
        public HttpResponseMessage getRgProjToPromptLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgProjToPromptLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgProjToPromptLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgProjToPromptLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }
        [HttpPost]
        [ActionName("getRgHomeDeptToLOV")]
        public HttpResponseMessage getRgHomeDeptToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgHomeDeptToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgHomeDeptToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgHomeDeptToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgHomeDeptLocToLOV")]
        public HttpResponseMessage getRgHomeDeptLocToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgHomeDeptLocToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgHomeDeptLocToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgHomeDeptLocToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgListHomeDeptToLOV")]
        public HttpResponseMessage getRgListHomeDeptToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgListHomeDeptToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgListHomeDeptToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgListHomeDeptToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgHomeLocToLOV")]
        public HttpResponseMessage getRgHomeLocToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgHomeLocToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgHomeLocToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgHomeLocToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgListHomeLocToLOV")]
        public HttpResponseMessage getRgListHomeLocToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgListHomeLocToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgListHomeLocToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgListHomeLocToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgClassCodeToLOV")]
        public HttpResponseMessage getRgClassCodeToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgClassCodeToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgClassCodeToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgClassCodeToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgListClassCodeToLOV")]
        public HttpResponseMessage getRgListClassCodeToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgListClassCodeToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgListClassCodeToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgListClassCodeToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgWorkDeptToLOV")]
        public HttpResponseMessage getRgWorkDeptToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgWorkDeptToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgWorkDeptToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgWorkDeptToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgWorkDeptLocToLOV")]
        public HttpResponseMessage getRgWorkDeptLocToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgWorkDeptLocToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgWorkDeptLocToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgWorkDeptLocToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgListWorkDeptToLOV")]
        public HttpResponseMessage getRgListWorkDeptToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgListWorkDeptToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgListWorkDeptToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgListWorkDeptToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgWorkLocToLOV")]
        public HttpResponseMessage getRgWorkLocToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgWorkLocToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgWorkLocToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgWorkLocToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgListWorkLocToLOV")]
        public HttpResponseMessage getRgListWorkLocToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgListWorkLocToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgListWorkLocToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgListWorkLocToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }


        [HttpPost]
        [ActionName("getRgRscToLOV")]
        public HttpResponseMessage getRgRscToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgRscToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgRscToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgRscToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }
        [HttpPost]
        [ActionName("getRgWpdToLOV")]
        public HttpResponseMessage getRgWpdToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgWpdToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgWpdToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgWpdToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgBulkToLOV")]
        public HttpResponseMessage getRgBulkToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgBulkToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgBulkToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgBulkToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgCecEpToLOV")]
        public HttpResponseMessage getRgCecEpToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgCecEpToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgCecEpToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgCecEpToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgListCecEpToLOV")]
        public HttpResponseMessage getRgListCecEpToLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgListCecEpToLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgListCecEpToLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgListCecEpToLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }

        [HttpPost]
        [ActionName("getRgAffiliateFromLOV")]
        public HttpResponseMessage getRgAffiliateFromLOV([FromBody]IEnumerable<CreateMctrLov> createMctrLov)
        {
            logger.Info("Executing Rest API : getRgAffiliateFromLOV() with request : " + createMctrLov);

            ICreateMctrLovBusiness CreateMctrLovBusiness = new CreateMctrLovBusiness();
            var response = CreateMctrLovBusiness.getRgAffiliateFromLOV(createMctrLov);
            logger.Info("Response received from mctrCreateFormBusiness.getRgAffiliateFromLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);


        }




    }
}

