///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®

using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Net;
using System.Net.Http;
using System.Web.Http.Filters;

using log4net;
using MCTR.RESTService.Controllers;
using System.Web.Http;

namespace MCTR.RESTService
{
    public class ExceptionFilter : ExceptionFilterAttribute
    {
        public override void OnException(HttpActionExecutedContext actionExecutedContext)
        {
            ILog logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
            logger.Fatal(actionExecutedContext.Exception.Message);

            throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.ExpectationFailed)
            {
                Content = new StringContent(actionExecutedContext.Exception.Message + " FROM GLOBAL REST EXCEPTION HANDLER"),
                ReasonPhrase = actionExecutedContext.Exception.Message + " REASON PHRASE FROM GLOBAL REST EXCEPTION HANDLER"
            });
        }
    }
}

namespace MCTR.RESTService.Controllers
    {
        class ApiMessageError
        {
            public ApiMessageError()
            {
            }

            public string message { get; set; }
        }
    }
