///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  


using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using log4net;

using MCTR.DomainEntity;
using MCTR.BusinessInterface;
using MCTR.Business;

namespace MCTR.RESTService.Controllers
{
    ///*********************************************************************
    ///<summary>
    ///JrnlHistServiceController is a Rest controller implementation  
    ///which acts as a wrapper to the JrnlHistBusiness implementation and
    /// provides api path for each methods exposed.
    ///</summary>

    public class JrnlHistServiceController : ApiController
    {

         private readonly ILog logger;

        public JrnlHistServiceController()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : jrnlHistOnLoad
        ///</summary>
        ///<param name = "JrnlHist"></param>
        ///<returns>IEnumerable<JrnlHist> </returns>

        [HttpPost]
        [ActionName("jrnlHistOnLoad")]
        public HttpResponseMessage jrnlHistOnLoad([FromBody]IEnumerable<JrnlHist> jrnlHist)
        {
            try
            {
                logger.Info("Executing  MCTR.RESTService.Controllers.LineItemServiceController.jrnlHistOnLoad() with request : " + jrnlHist);
                if (jrnlHist != null)
                {
                    IJrnlHistBusiness jrnlHistBusiness = new JrnlHistBusiness();
                    var response = jrnlHistBusiness.jrnlHistOnLoad(jrnlHist);
                    logger.Info("Response received from MCTR.RESTService.Controllers.LineItemServiceController.jrnlHistOnLoad() with request : : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception e)
            {
                logger.Error("Error from  MCTR.RESTService.Controllers.LineItemServiceController.jrnlHistOnLoad()" + e.Message);
                throw;
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgJhistDateLOV()
        ///</summary>
        ///<param name = "JrnlHist"></param>
        ///<returns>IEnumerable<JrnlHist> </returns>

        [HttpGet]
        [ActionName("getRgJhistDateLOV")]
        public HttpResponseMessage getRgJhistDateLOV()
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.Controllers.LineItemServiceController.jrnlHistOnLoad()");

                IJrnlHistBusiness jrnlHistBusiness = new JrnlHistBusiness();
                var response = jrnlHistBusiness.getRgJhistDateLOV();
                logger.Info("Response received from MCTR.RESTService.Controllers.LineItemServiceController.jrnlHistOnLoad() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception e)
            {
                logger.Error("Error from  MCTR.RESTService.Controllers.LineItemServiceController.jrnlHistOnLoad()" + e.Message);
                throw;
            }
        }
    }



}


