///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History : 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using log4net;
using MCTR.BusinessInterface;
using MCTR.Business;
using MCTR.DomainEntity;

namespace MCTR.RESTService.Controllers
{

    public class MctrCreateFormServiceController : ApiController
    {

        private readonly ILog logger = null;
        private readonly IMctrCreateFormBusiness mctrCreateFormBusiness = new MctrCreateFormBusiness();
        public MctrCreateFormServiceController()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrLineItemactivityIdFromPreTextItem
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>

        [HttpPost]
        [ActionName("mctrLineItemactivityIdFromPreTextItem")]
        public HttpResponseMessage mctrLineItemactivityIdFromPreTextItem([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemactivityIdFromPreTextItem with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.mctrLineItemactivityIdFromPreTextItem(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.mctrLineItemactivityIdFromPreTextItem() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }

        [HttpPost]
        [ActionName("mctrheaderbuttoxlswhenbuttonpressed")]
        public HttpResponseMessage mctrheaderbuttoxlswhenbuttonpressed([FromBody]IEnumerable<HeaderExcel> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrheaderbuttoxlswhenbuttonpressed with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.mctrheaderbuttoxlswhenbuttonpressed(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.mctrheaderbuttoxlswhenbuttonpressed() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }


        [HttpPost]
        [ActionName("mctrLineItemclassCdToPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemclassCdToPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemclassCdToPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemamountToPostTextItem")]
        public HttpResponseMessage mctrLineItemamountToPostTextItem([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemamountToPostTextItem(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemestmtgPricgCdToPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemestmtgPricgCdToPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemestmtgPricgCdToPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemrscToPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemrscToPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemrscToPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemworkLocToPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemworkLocToPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemworkLocToPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }


        [HttpPost]
        [ActionName("getRgLOVReject")]
        public HttpResponseMessage getRgLOVReject([FromBody]IEnumerable<MctrRejectCode> mctrRejectCode)
        {

            var response = mctrCreateFormBusiness.getRgLOVReject(mctrRejectCode);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemworkDeptToPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemworkDeptToPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemworkDeptToPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemhomeBuglToPostTextItem")]
        public HttpResponseMessage mctrLineItemhomeBuglToPostTextItem([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemhomeBuglToPostTextItem(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemaccountToPostTextItem")]
        public HttpResponseMessage mctrLineItemaccountToPostTextItem([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemaccountToPostTextItem(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemestmtgPricgCdFromPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemestmtgPricgCdFromPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemestmtgPricgCdFromPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemquantityFromPostTextItem")]
        public HttpResponseMessage mctrLineItemquantityFromPostTextItem([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemquantityFromPostTextItem(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }


        [HttpPost]
        [ActionName("submitBtnmctrLineItemquantityFromPostTextItem")]
        public HttpResponseMessage submitBtnmctrLineItemquantityFromPostTextItem([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.submitBtnmctrLineItemquantityFromPostTextItem(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }


        [HttpPost]
        [ActionName("mctrLineItembulkFromPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItembulkFromPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItembulkFromPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItembutBulkWhenButtonPressedOpenLOV")]
        public HttpResponseMessage mctrLineItembutBulkWhenButtonPressedOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItembutBulkWhenButtonPressedOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        

 [HttpPost]
        [ActionName("batchModeCheck")]
        public HttpResponseMessage batchModeCheck([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.batchModeCheck(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItembutWpdWhenButtonPressedOpenLOV")]
        public HttpResponseMessage mctrLineItembutWpdWhenButtonPressedOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItembutWpdWhenButtonPressedOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("mctrLineItemhomeDeptToPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemhomeDeptToPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemhomeDeptToPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemhomeLocToPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemhomeLocToPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemhomeLocToPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }


        [HttpPost]
        [ActionName("mctrLineItemaccountFromPostTextItem")]
        public HttpResponseMessage mctrLineItemaccountFromPostTextItem([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemaccountFromPostTextItem(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("mctrHeaderPreUpdate")]
        public HttpResponseMessage mctrHeaderPreUpdate([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrHeaderPreUpdate with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.mctrHeaderPreUpdate(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.mctrHeaderPreUpdate() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrLineItembutCopyWhenButtonPressed
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>

        [HttpPost]
        [ActionName("mctrLineItembutCopyWhenButtonPressed")]
        public HttpResponseMessage mctrLineItembutCopyWhenButtonPressed([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItembutCopyWhenButtonPressed() with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.mctrLineItembutCopyWhenButtonPressed(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.mctrLineItembutCopyWhenButtonPressed() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }
        [HttpPost]
        [ActionName("mctrLineItemPreDelete")]
        public HttpResponseMessage mctrLineItemPreDelete([FromBody]IEnumerable<MctrLineItem> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemPreDelete() with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.mctrLineItemPreDelete(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.mctrLineItemPreDelete() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }

        [HttpPost]
        [ActionName("mctrHeaderbutUnjrnlWhenButtonPressed")]
        public HttpResponseMessage mctrHeaderbutUnjrnlWhenButtonPressed([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrHeaderbutUnjrnlWhenButtonPressed with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.mctrHeaderbutUnjrnlWhenButtonPressed(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.mctrHeaderbutUnjrnlWhenButtonPressed() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }

        [HttpPost]
        [ActionName("justificationsave")]
        public HttpResponseMessage justificationsave([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrHeaderbutUnjrnlWhenButtonPressed with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.justificationsave(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.justificationsave() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }

        [HttpPost]
        [ActionName("mctrHeaderbutJrnlWhenButtonPressed")]
        public HttpResponseMessage mctrHeaderbutJrnlWhenButtonPressed([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrHeaderbutJrnlWhenButtonPressed with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.mctrHeaderbutJrnlWhenButtonPressed(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.mctrHeaderbutJrnlWhenButtonPressed() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrLineItemOnLoad
        ///</summary>
        ///<param name = "mctrLineItem"></param>
        ///<returns>IEnumerable<MctrLineItem> </returns>
        [HttpPost]
        [ActionName("mctrLineItemOnLoad")]
        public HttpResponseMessage mctrLineItemOnLoad([FromBody]IEnumerable<MctrLineItem> mctrLineItem)
        {

            var response = mctrCreateFormBusiness.mctrLineItemOnLoad(mctrLineItem);
            logger.Info("Response received from mctrCreateFormBusiness.mctrLineItemOnLoad() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("ttdInqCyrTtdInqCyrOnLoad")]
        public HttpResponseMessage ttdInqCyrTtdInqCyrOnLoad([FromBody]IEnumerable<MctrLineiteminquiry> mctrlineitem)
        {
            logger.Info("Executing Rest API : mctrLineItemperiodToOnError() with request : " + mctrlineitem);


            var response = mctrCreateFormBusiness.ttdInqCyrTtdInqCyrOnLoad(mctrlineitem);
            logger.Info("Response received from mctrCreateFormBusiness.ttdInqCyrTtdInqCyrOnLoad() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);

        }

        [HttpPost]
        [ActionName("ttdInqPyrTtdInqPyrOnLoad")]
        public HttpResponseMessage ttdInqPyrTtdInqPyrOnLoad([FromBody]IEnumerable<MctrLineiteminquiry> mctrlineitem)
        {
            logger.Info("Executing Rest API : ttdInqPyrTtdInqPyrOnLoad() with request : " + mctrlineitem);


            var response = mctrCreateFormBusiness.ttdInqPyrTtdInqPyrOnLoad(mctrlineitem);
            logger.Info("Response received from mctrCreateFormBusiness.ttdInqPyrTtdInqPyrOnLoad() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);

        }

        [HttpPost]
        [ActionName("ttdInqFilter")]
        public HttpResponseMessage ttdInqFilter([FromBody]IEnumerable<MctrLineiteminquiry> mctrlineitem)
        {
            logger.Info("Executing Rest API : ttdInqPyrTtdInqPyrOnLoad() with request : " + mctrlineitem);


            var response = mctrCreateFormBusiness.ttdInqFilter(mctrlineitem);
            logger.Info("Response received from mctrCreateFormBusiness.ttdInqPyrTtdInqPyrOnLoad() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);

        }


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrLineItemperiodToOnError
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>

        [HttpPost]
        [ActionName("mctrLineItemperiodToOnError")]
        public HttpResponseMessage mctrLineItemperiodToOnError([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemperiodToOnError() with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.mctrLineItemperiodToOnError(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.mctrLineItembutProjFromPromptWhenNewItemInstance() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }

        [HttpPost]
        [ActionName("mctrHeaderbutJustificationWhenButtonPressed")]
        public HttpResponseMessage mctrHeaderbutJustificationWhenButtonPressed([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemperiodToOnError() with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.mctrHeaderbutJustificationWhenButtonPressed(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.mctrLineItembutProjFromPromptWhenNewItemInstance() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrLineItemactivityIdFromPreTextItem
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrLineItemaccountFromPostTextItem
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>

        [HttpPost]
        [ActionName("mctrLineItemhomeLocFromPreTextItem")]
        public HttpResponseMessage mctrLineItemhomeLocFromPreTextItem([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemhomeLocFromPreTextItem with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.mctrLineItemhomeLocFromPreTextItem(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.mctrLineItemhomeLocFromPreTextItem() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }

        [HttpPost]
        [ActionName("getRgBuGrpLOV")]
        public HttpResponseMessage getRgBuGrpLOV(IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : getRgBuGrpLOV() with request : " + mctrCreateForm);
            var response = mctrCreateFormBusiness.getRgBuGrpLOV(mctrCreateForm);
            List<MctrCreateForm> d = new List<MctrCreateForm>();
            var x = new MctrCreateForm();
            x.BusUnit = response;
            d.Add(x);
            logger.Info("Response received from mctrCreateFormBusiness.getRgBuGrpLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, d);
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgYearLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>

        [HttpPost]
        [ActionName("getRgYearLOV")]
        public HttpResponseMessage getRgYearLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : getRgYearLOV() with request : " + mctrCreateForm);
            var response = mctrCreateFormBusiness.getRgYearLOV(mctrCreateForm);
            logger.Info("Response received from mctrCreateFormBusiness.getRgYearLOV() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);

        }

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgReasonLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>

        [HttpPost]
        [ActionName("getRgReasonLOV()")]
        public HttpResponseMessage getRgReasonLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : getRgReasonLOV() with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.getRgReasonLOV(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.getRgReasonLOV() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgApplLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>

        [HttpPost]
        [ActionName("getRgApplLOV()")]
        public HttpResponseMessage getRgApplLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : getRgApplLOV() with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.getRgApplLOV(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.getRgApplLOV() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgSuperLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>

        [HttpPost]
        [ActionName("getRgSuperLOV()")]
        public HttpResponseMessage getRgSuperLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : getRgSuperLOV() with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.getRgSuperLOV(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.getRgSuperLOV() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }
        [HttpPost]
        [ActionName("mctrHeaderPreInsert")]
        public HttpResponseMessage mctrHeaderPreInsert([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrHeaderPreInsert() with request : " + mctrCreateForm);

            var response = mctrCreateFormBusiness.mctrHeaderPreInsert(mctrCreateForm);
            logger.Info("Response received from mctrCreateFormBusiness.mctrHeaderPreInsert() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemInsert")]
        public HttpResponseMessage mctrLineItemInsert([FromBody]IEnumerable<MctrLineItem> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemInsert() with request : " + mctrCreateForm);

            var response = mctrCreateFormBusiness.mctrLineItemInsert(mctrCreateForm);
            logger.Info("Response received from mctrCreateFormBusiness.mctrLineItemInsert() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemDelete")]
        public HttpResponseMessage mctrLineItemDelete([FromBody]IEnumerable<MctrLineItem> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemDelete() with request : " + mctrCreateForm);

            var response = mctrCreateFormBusiness.mctrLineItemDelete(mctrCreateForm);
            logger.Info("Response received from mctrCreateFormBusiness.mctrLineItemDelete() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        ///Method Name : mctrcommentonload
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>

        [HttpPost]
        public IEnumerable<MCTRComments> mctrcommentonload(IEnumerable<MCTRComments> mctrComments)
        {
            try
            {
                var response = mctrCreateFormBusiness.mctrcommentonload(mctrComments);
                return response;
            }
            catch (Exception ex)
            {
                logger.Error("Exception occured at mctrcommentonload : " + ex);
                throw;
            }
        }

        [HttpPost]
        [ActionName("mctrCommentcommentsWhenValidateItem")]
        public HttpResponseMessage mctrCommentviewStatementWhenButtonPressed([FromBody]IEnumerable<MCTRComments> mctrComments)
        {
            try
            {
                logger.Info("Executing MctrCreateFormServiceController : mctrCommentcommentsWhenValidateItem() with request : " + mctrComments);
                if (mctrComments != null)
                {
                   
                    var response = mctrCreateFormBusiness.mctrCommentviewStatementWhenButtonPressed(mctrComments);
                    logger.Info("Response received from  MctrCreateFormServiceController.mctrCommentcommentsWhenValidateItem() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                else
                {
                    return Request.CreateErrorResponse(HttpStatusCode.OK, new Exception());
                }
            }
            catch (Exception ex)
            {
                logger.Error("Error  from mctrCreateFormBusiness.mctrCommentcommentsWhenValidateItem() : " + ex);
                return Request.CreateErrorResponse(HttpStatusCode.OK, ex);
            }
        }

        [HttpPost]
        [ActionName("mctrCommentbutSaveWhenButtonPressed")]
        public HttpResponseMessage mctrCommentbutSaveWhenButtonPressed([FromBody]IEnumerable<MCTRComments> mctrComments)
        {
            try
            {
                logger.Info("Executing MctrCreateFormServiceController : mctrCommentbutSaveWhenButtonPressed() with request : " + mctrComments);
                if (mctrComments != null)
                {
                   
                    var response = mctrCreateFormBusiness.mctrCommentbutSaveWhenButtonPressed(mctrComments);
                    logger.Info("Response received from  MctrCreateFormServiceController.mctrCommentbutSaveWhenButtonPressed() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                else
                {
                    return Request.CreateErrorResponse(HttpStatusCode.OK, new Exception());
                }
            }
            catch (Exception ex)
            {
                logger.Error("Error  from mctrCreateFormBusiness.mctrCommentbutSaveWhenButtonPressed() : " + ex);
                return Request.CreateErrorResponse(HttpStatusCode.OK, ex);
            }
        }
        [HttpPost]
        [ActionName("mctrCommentPostQuery")]
        public IEnumerable<MCTRComments> mctrCommentPostQuery(IEnumerable<MCTRComments> mctrComments)
        {

            try
            {

                var response = mctrCreateFormBusiness.mctrCommentPostQuery(mctrComments);

                return response;
            }
            catch (Exception ex)
            {
                logger.Error("Exception occured at : " + ex);
                throw;
            }
        }
        [HttpPost]
        [ActionName("mctrCommentOnMessage")]
        public IEnumerable<MCTRComments> mctrCommentOnMessage(IEnumerable<MCTRComments> mctrComments)
        {
            try
            {

                var response = mctrCreateFormBusiness.mctrCommentOnMessage(mctrComments);

                return response;
            }
            catch (Exception ex)
            {
                logger.Error("Exception occured at : " + ex);
                throw;
            }
        }
        [HttpPost]
        [ActionName("mctrCommentPreInsert")]
        public IEnumerable<MCTRComments> mctrCommentPreInsert(IEnumerable<MCTRComments> mctrComments)
        {
            try
            {

                var response = mctrCreateFormBusiness.mctrCommentPreInsert(mctrComments);

                return response;
            }
            catch (Exception ex)
            {
                logger.Error("Exception occured at : " + ex);
                throw;
            }
        }
        [HttpPost]
        [ActionName("mctrCommentOnInsert")]
        public IEnumerable<MCTRComments> mctrCommentOnInsert(IEnumerable<MCTRComments> mctrComments)
        {
            try
            {

                var response = mctrCreateFormBusiness.mctrCommentOnInsert(mctrComments);

                return response;
            }
            catch (Exception ex)
            {
                logger.Error("Exception occured at : " + ex);
                throw;
            }
        }
        [HttpPost]
        [ActionName("mctrHeaderbutSubmitWhenButtonPressed")]
        public HttpResponseMessage mctrHeaderbutSubmitWhenButtonPressed([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            try
            {
                logger.Info("Executing Rest API : mctrHeaderbutSubmitWhenButtonPressed() with request : " + mctrCreateForm);

                var response = mctrCreateFormBusiness.mctrHeaderbutSubmitWhenButtonPressed(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.mctrHeaderbutSubmitWhenButtonPressed() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.RESTService.Controllers.MctrCreateFormService.mctrHeaderbutSubmitWhenButtonPressed() " + e.Message);
                throw;
            }
        }

        [HttpPost]
        [ActionName("mctrLineItemPreInsert")]
        public HttpResponseMessage mctrLineItemPreInsert([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemPreInsert() with request : " + mctrCreateForm);

            var response = mctrCreateFormBusiness.mctrLineItemPreInsert(mctrCreateForm);
            logger.Info("Response received from mctrLineItemPreInsert.mctrLineItemInsert() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrHeaderonLoad")]
        public HttpResponseMessage mctrHeaderonLoad([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemPreInsert() with request : " + mctrCreateForm);

            var response = mctrCreateFormBusiness.mctrHeaderonLoad(mctrCreateForm);
            logger.Info("Response received from mctrLineItemPreInsert.mctrLineItemInsert() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("mctrLineItemPostInsert")]
        public HttpResponseMessage mctrLineItemPostInsert([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemPostInsert() with request : " + mctrCreateForm);

            var response = mctrCreateFormBusiness.mctrLineItemPostInsert(mctrCreateForm);
            logger.Info("Response received from mctrCreateFormBusiness.mctrLineItemPostInsert() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("mctrLineItemPreUpdate")]
        public HttpResponseMessage mctrLineItemPreUpdate([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemPreUpdate() with request : " + mctrCreateForm);

            var response = mctrCreateFormBusiness.mctrLineItemPreUpdate(mctrCreateForm);
            logger.Info("Response received from mctrCreateFormBusiness.mctrLineItemPreUpdate() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("mctrLineItemPostUpdate")]
        public HttpResponseMessage mctrLineItemPostUpdate([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemPreUpdate() with request : " + mctrCreateForm);

            var response = mctrCreateFormBusiness.mctrLineItemPostUpdate(mctrCreateForm);
            logger.Info("Response received from mctrCreateFormBusiness.mctrLineItemPreUpdate() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemPostDelete")]
        public HttpResponseMessage mctrLineItemPostDelete([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemPostDelete() with request : " + mctrCreateForm);

            var response = mctrCreateFormBusiness.mctrLineItemPostDelete(mctrCreateForm);
            logger.Info("Response received from mctrCreateFormBusiness.mctrLineItemPostDelete() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("mctrLineItemPostQuery")]
        public HttpResponseMessage mctrLineItemPostQuery([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : mctrLineItemPostQuery() with request : " + mctrCreateForm);

            var response = mctrCreateFormBusiness.mctrLineItemPostQuery(mctrCreateForm);
            logger.Info("Response received from mctrCreateFormBusiness.mctrLineItemPostQuery() : " + response);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("pycystatuscheckbubut")]
        public HttpResponseMessage pycystatuscheckbubut([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            var response = mctrCreateFormBusiness.pycystatuscheckbubut(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("fyearperiodvalidation")]
        public HttpResponseMessage fyearperiodvalidation([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            var response = mctrCreateFormBusiness.fyearperiodvalidation(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("validApprover")]
        public HttpResponseMessage validApprover([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            var response = mctrCreateFormBusiness.validApprover(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("mctrLineItemamountfromPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemamountfromPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            var response = mctrCreateFormBusiness.mctrLineItemamountfromPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("mctrLineItembulkFromPostTextItemOpenLOVBulkFlag")]
        public HttpResponseMessage mctrLineItembulkFromPostTextItemOpenLOVBulkFlag([FromBody]IEnumerable<BuProfile> BuProfile)
        {
            var response = mctrCreateFormBusiness.mctrLineItembulkFromPostTextItemOpenLOVBulkFlag(BuProfile);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("mctrLineItemClassCditemOpenLOV")]
        public HttpResponseMessage mctrLineItemClassCditemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemClassCditemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("mctrLineItemhomeLocFromPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemhomeLocFromPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemhomeLocFromPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemhomeDeptFromPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemhomeDeptFromPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemhomeDeptFromPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("mctrLineItemaffiliateFromPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemaffiliateFromPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemaffiliateFromPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemwpdFromPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemwpdFromPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemwpdFromPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemrscFromPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemrscFromPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemrscFromPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemworkLocFromPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemworkLocFromPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemworkLocFromPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItemworkDeptFromPostTextItemOpenLOV")]
        public HttpResponseMessage mctrLineItemworkDeptFromPostTextItemOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItemworkDeptFromPostTextItemOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrHeaderbutBuWhenButtonPressedOpenLOV")]
        public HttpResponseMessage mctrHeaderbutBuWhenButtonPressedOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrHeaderbutBuWhenButtonPressedOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("buButPressPTTValidation")]
        public HttpResponseMessage buButPressPTTValidation([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.buButPressPTTValidation(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("mctrHeaderbutFiscalYearWhenButtonPressedOpenLOV")]
        public HttpResponseMessage mctrHeaderbutFiscalYearWhenButtonPressedOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrHeaderbutFiscalYearWhenButtonPressedOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("mctrLineItembutTransFromWhenButtonPressedOpenLOV")]
        public HttpResponseMessage mctrLineItembutTransFromWhenButtonPressedOpenLOV([FromBody]IEnumerable<MctrLineItem> mctrlineitem)
        {

            var response = mctrCreateFormBusiness.mctrLineItembutTransFromWhenButtonPressedOpenLOV(mctrlineitem);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("manRatedFlag")]
        public HttpResponseMessage manRatedFlag([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.manRatedFlag(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }

        [HttpPost]
        [ActionName("ValidateActivityID")]
        public HttpResponseMessage ValidateActivityID([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.ValidateActivityID(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("mctrLineItembutProjToWhenButtonPressedOpenLOV")]
        public HttpResponseMessage mctrLineItembutProjToWhenButtonPressedOpenLOV([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {

            var response = mctrCreateFormBusiness.mctrLineItembutProjToWhenButtonPressedOpenLOV(mctrCreateForm);
            return Request.CreateResponse(HttpStatusCode.OK, response);
        }
        [HttpPost]
        [ActionName("querymodecheck")]
        public HttpResponseMessage querymodecheck([FromBody]IEnumerable<MctrCreateForm> mctrCreateForm)
        {
            logger.Info("Executing Rest API : querymodecheck() with request : " + mctrCreateForm);
            if (mctrCreateForm != null)
            {

                var response = mctrCreateFormBusiness.querymodecheck(mctrCreateForm);
                logger.Info("Response received from mctrCreateFormBusiness.querymodecheck() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            else
            {
                return null;
            }
        }
    }
}