///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  


using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using log4net;

using MCTR.DomainEntity;
using MCTR.BusinessInterface;
using MCTR.Business;

namespace MCTR.RESTService.Controllers
{
    ///*********************************************************************
    ///<summary>
    ///MctrOhFormBlServiceController is a Rest controller implementation  
    ///which acts as a wrapper to the MctrOhFormBlBusiness implementation and
    /// provides api path for each methods exposed.
    ///</summary>

    public class MctrOhFormBlServiceController : ApiController
    {

         private readonly ILog logger;

        public MctrOhFormBlServiceController()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrOhMctrOhOnLoad
        ///</summary>
        ///<param name = "MctrOhFormBl"></param>
        ///<returns>IEnumerable<MctrOhFormBl> </returns>

        [HttpPost]
        [ActionName("mctrOhMctrOhOnLoad")]
        public HttpResponseMessage mctrOhMctrOhOnLoad([FromBody]IEnumerable<MctrOhFormBl> mctrOhFormBl)
        {
            try {
            logger.Info("Executing Rest API : mctrOhMctrOhOnLoad() with request : " + mctrOhFormBl);
            
                IMctrOhFormBlBusiness mctrOhFormBlBusiness = new MctrOhFormBlBusiness();
                var response = mctrOhFormBlBusiness.mctrOhMctrOhOnLoad(mctrOhFormBl);
                logger.Info("Response received from mctrOhFormBlBusiness.mctrOhMctrOhOnLoad() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.RESTService: " + e.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, e.Message);
            }

        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrOhFormBlWhenNewFormInstance
        ///</summary>
        ///<param name = "MctrOhFormBl"></param>
        ///<returns>IEnumerable<MctrOhFormBl> </returns>

        [HttpPost]
        [ActionName("mctrOhFormBlWhenNewFormInstance")]
        public HttpResponseMessage mctrOhFormBlWhenNewFormInstance([FromBody]IEnumerable<MctrOhFormBl> mctrOhFormBl)
        {
            logger.Info("Executing Rest API : mctrOhFormBlWhenNewFormInstance() with request : " + mctrOhFormBl);
            if (mctrOhFormBl != null)
            {
                IMctrOhFormBlBusiness mctrOhFormBlBusiness = new MctrOhFormBlBusiness();
                var response = mctrOhFormBlBusiness.mctrOhFormBlWhenNewFormInstance(mctrOhFormBl);
                logger.Info("Response received from mctrOhFormBlBusiness.mctrOhFormBlWhenNewFormInstance() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrOhFormBlWhenWindowClosed
        ///</summary>
        ///<param name = "MctrOhFormBl"></param>
        ///<returns>IEnumerable<MctrOhFormBl> </returns>

        [HttpPost]
        [ActionName("mctrOhFormBlWhenWindowClosed")]
        public HttpResponseMessage mctrOhFormBlWhenWindowClosed([FromBody]IEnumerable<MctrOhFormBl> mctrOhFormBl)
        {
            logger.Info("Executing Rest API : mctrOhFormBlWhenWindowClosed() with request : " + mctrOhFormBl);
            if (mctrOhFormBl != null)
            {
                IMctrOhFormBlBusiness mctrOhFormBlBusiness = new MctrOhFormBlBusiness();
                var response = mctrOhFormBlBusiness.mctrOhFormBlWhenWindowClosed(mctrOhFormBl);
                logger.Info("Response received from mctrOhFormBlBusiness.mctrOhFormBlWhenWindowClosed() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            return null;
        }


    }

}

