///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  


using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using log4net;

using MCTR.DomainEntity;
using MCTR.BusinessInterface;
using MCTR.Business;

namespace MCTR.RESTService.Controllers
{
    ///*********************************************************************
    ///<summary>
    ///MctrWkipJrnlsBlServiceController is a Rest controller implementation  
    ///which acts as a wrapper to the MctrWkipJrnlsBlBusiness implementation and
    /// provides api path for each methods exposed.
    ///</summary>

    public class MctrWkipJrnlsBlServiceController : ApiController
    {

         private readonly ILog logger;

        public MctrWkipJrnlsBlServiceController()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }


        ///*************************************************************
        ///<summary>
        ///Method Name : jrnlWeekJrnlWeekOnLoad
        ///</summary>
        ///<param name = "MctrWkipJrnlsBl"></param>
        ///<returns>IEnumerable<MctrWkipJrnlsBl> </returns>

        [HttpPost]
        [ActionName("jrnlWeekJrnlWeekOnLoad")]
        public HttpResponseMessage jrnlWeekJrnlWeekOnLoad([FromBody]IEnumerable<MctrWkipJrnlsBl> mctrWkipJrnlsBl)
        {
            try
            {
                logger.Info("Executing Rest API : jrnlWeekJrnlWeekOnLoad() with request : " + mctrWkipJrnlsBl);

                IMctrWkipJrnlsBlBusiness mctrWkipJrnlsBlBusiness = new MctrWkipJrnlsBlBusiness();
                var response = mctrWkipJrnlsBlBusiness.jrnlWeekJrnlWeekOnLoad(mctrWkipJrnlsBl);
                logger.Info("Response received from mctrWkipJrnlsBlBusiness.jrnlWeekJrnlWeekOnLoad() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.RESTService: " + e.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, e.Message);
            }


        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrWkipJrnlsBlWhenNewFormInstance
        ///</summary>
        ///<param name = "MctrWkipJrnlsBl"></param>
        ///<returns>IEnumerable<MctrWkipJrnlsBl> </returns>

        [HttpPost]
        [ActionName("mctrWkipJrnlsBlWhenNewFormInstance")]
        public HttpResponseMessage mctrWkipJrnlsBlWhenNewFormInstance([FromBody]IEnumerable<MctrWkipJrnlsBl> mctrWkipJrnlsBl)
        {
            try
            {
                logger.Info("Executing Rest API : mctrWkipJrnlsBlWhenNewFormInstance() with request : " + mctrWkipJrnlsBl);
                if (mctrWkipJrnlsBl != null)
                {
                    IMctrWkipJrnlsBlBusiness mctrWkipJrnlsBlBusiness = new MctrWkipJrnlsBlBusiness();
                    var response = mctrWkipJrnlsBlBusiness.mctrWkipJrnlsBlWhenNewFormInstance(mctrWkipJrnlsBl);
                    logger.Info("Response received from mctrWkipJrnlsBlBusiness.mctrWkipJrnlsBlWhenNewFormInstance() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.RESTService: " + e.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, e.Message);
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrWkipJrnlsBlWhenWindowClosed
        ///</summary>
        ///<param name = "MctrWkipJrnlsBl"></param>
        ///<returns>IEnumerable<MctrWkipJrnlsBl> </returns>

        [HttpPost]
        [ActionName("mctrWkipJrnlsBlWhenWindowClosed")]
        public HttpResponseMessage mctrWkipJrnlsBlWhenWindowClosed([FromBody]IEnumerable<MctrWkipJrnlsBl> mctrWkipJrnlsBl)
        {
            try
            {
                logger.Info("Executing Rest API : mctrWkipJrnlsBlWhenWindowClosed() with request : " + mctrWkipJrnlsBl);
                if (mctrWkipJrnlsBl != null)
                {
                    IMctrWkipJrnlsBlBusiness mctrWkipJrnlsBlBusiness = new MctrWkipJrnlsBlBusiness();
                    var response = mctrWkipJrnlsBlBusiness.mctrWkipJrnlsBlWhenWindowClosed(mctrWkipJrnlsBl);
                    logger.Info("Response received from mctrWkipJrnlsBlBusiness.mctrWkipJrnlsBlWhenWindowClosed() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.RESTService: " + e.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, e.Message);
            }
        }


    }

}

