///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History : 

using System;
using System.Collections.Generic;
using System.Web.Http;
using log4net;
using MCTR.DomainEntity;
using MCTR.BusinessInterface;
using MCTR.Business;
using System.Net.Http;
using System.Net;

namespace MCTR.RESTService.Controllers
{
    public class MCTRJobStatusServiceController : ApiController
    {

         private readonly ILog logger;

        public MCTRJobStatusServiceController()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }

        [HttpPost]
        [ActionName("MCTRJobStatusOnInsert")]
        public HttpResponseMessage MCTRJobStatusOnInsert([FromBody]IEnumerable<MCTRJobStatus> MCTRJobStatus)
        {
            try
            {
                
                if (MCTRJobStatus != null)
                {
                    logger.Info("Executing Rest API : MCTRJobStatusOnInsert() with request : " + MCTRJobStatus);
                    IMCTRJobStatusBusiness MCTRJobStatusBusiness = new MCTRJobStatusBusiness();
                    var response = MCTRJobStatusBusiness.MCTRJobStatusOnInsert(MCTRJobStatus);
                    logger.Info("Response received from MCTRJobStatusBusiness.MCTRJobStatusOnInsert() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.RESTService: " + e.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, e.Message);
            }
        }

        [HttpGet]
        [ActionName("GetData")]
        public HttpResponseMessage GetData()
        {
            try
            {
                logger.Info("Executing Rest API : GetData() : ");
                IMCTRJobStatusBusiness MCTRJobStatusBusiness = new MCTRJobStatusBusiness();
                var response = MCTRJobStatusBusiness.GetData();
                logger.Info("Response received from MCTRJobStatusBusiness.MCTRJobStatusOnInsert() : " + response);
                return Request.CreateResponse(HttpStatusCode.OK, response);
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.RESTService: " + e.Message);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, e.Message);
            }
        }
    }
}

