///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///
///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :

using log4net;
using MCTR.Business;
using MCTR.BusinessInterface;
using MCTR.DomainEntity;
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace MCTR.RESTService.Controllers
{
    ///*********************************************************************
    ///<summary>
    ///RoleServiceController is a Rest controller implementation  
    ///which acts as a wrapper to the RoleListBusiness implementation and
    /// provides api path for each methods exposed.
    ///</summary>

    public class RoleServiceController : ApiController
    {

         private readonly ILog logger;

        public RoleServiceController()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : rolePostQuery
        ///</summary>
        ///<param name = "role"></param>
        ///<returns>HttpResponseMessage</returns>

        [HttpPost]
        [ActionName("roleOnLoad")]
        public HttpResponseMessage roleOnLoad([FromBody]IEnumerable<RoleList> roleList)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.RoleServiceController.roleOnLoad() with request : " + roleList);
                if (roleList != null)
                {
                    IRoleBusiness roleBusiness = new RoleBusiness();
                    var response = roleBusiness.roleOnLoad(roleList);
                    logger.Info("Response received from MCTR.RESTService.RoleServiceController.roleOnLoad() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception e)
            {
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, e.Message);
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : Save
        ///</summary>
        ///<param name = "roleList"></param>
        ///<returns>HttpResponseMessage</returns>

        [HttpPost]
        [ActionName("Save")]
        public HttpResponseMessage Save([FromBody]IEnumerable<RoleList> roleList)
        {

            try
            {
                logger.Info("Executing MCTR.RESTService.RoleServiceController.roleOnLoad() with request : " + roleList);
                if (roleList != null)
                {
                    IRoleBusiness roleBusiness = new RoleBusiness();
                    var response = roleBusiness.Save(roleList);
                    logger.Info("Response received from MCTR.RESTService.RoleServiceController.roleOnLoad() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception e)
            {
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, e.Message);
            }
        }


        ///*************************************************************
        ///<summary>
        ///Method Name : rolePostQuery
        ///</summary>
        ///<param name = "role"></param>
        ///<returns>HttpResponseMessage</returns>
        [HttpPost]
        [ActionName("rolePostQuery")]
        public HttpResponseMessage rolePostQuery([FromBody]IEnumerable<Role> role)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.RoleServiceController.rolePostQuery() with request : " + role);
                if (role != null)
                {
                    IRoleBusiness roleBusiness = new RoleBusiness();
                    var response = roleBusiness.rolePostQuery(role);
                    logger.Info("Response received from MCTR.RESTService.RoleServiceController.rolePostQuery() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception e)
            {
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, e.Message);
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : roleWhenNewFormInstance
        ///</summary>
        ///<param name = "role"></param>
        ///<returns>HttpResponseMessage</returns>
        [HttpPost]
        [ActionName("roleWhenNewFormInstance")]
        public HttpResponseMessage roleWhenNewFormInstance([FromBody]IEnumerable<Role> role)
        {
            try
            {
                logger.Info("Executing MCTR.RESTService.RoleServiceController.roleWhenNewFormInstance() with request : " + role);
                if (role != null)
                {
                    IRoleBusiness roleBusiness = new RoleBusiness();
                    var response = roleBusiness.roleWhenNewFormInstance(role);
                    logger.Info("Response received from MCTR.RESTService.RoleServiceController.roleWhenNewFormInstance() : " + response);
                    return Request.CreateResponse(HttpStatusCode.OK, response);
                }
                return null;
            }
            catch (Exception e)
            {
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, e.Message);
            }
        }
    }
}

