$(document).ready(function () {

    var mctrObj = new MCTR();
    var MctrNo = $('#MctrNo').val();
    var columnNames = ['MCTR', 'LINE', 'F/T', 'Line OH'];
    var columnNamesRight = ['Intfc Line Num', 'Bus Unit', 'Project ID', 'Activity ID', 'Ledger Group', 'Bus Unit GL', 'Journal ID', 'Intfc Status', 'Load Status', 'Activity Type', 'Ledger', 'Oprid', 'Account', 'Majot Acct Nbr7', 'Deptid', 'Ovrhd Alctn Cd7', 'Affiliate', 'Deptid From', 'Ovrhd Alc Cd From7', 'Bus Unit GL From', 'Currency Cd', 'Stat Cd', 'Anal Type', 'Res Type', 'Res Sub Cat', 'Trans Date', 'Acntng Date', 'Dttm Stamp', 'Jrnl Ln Ref', 'Open Item Stat', 'Line Descr', 'Jrnl Line Date', 'Foreign Currency', 'Rt Type', 'Foreign Amount', 'Rate Mult', 'Cur Effdt', 'Proc Inst', 'Proj Trans Type', 'Proj Trans Code', 'Sys Srce', 'UOM', 'Emplid', 'Bus Unit AP', 'Vendor Id', 'Voucher Id', 'Voucher Line Num', 'Appl Jrnl Id', 'PO Id', 'BUS Unit AM', 'Asset Id', 'Cust Id', 'Item', 'Resource Qunatity', 'Resource Amount', 'Res User 1', 'Res User 2', 'Res User 3', 'Res User 4', 'Res User 5', 'Res User 6', 'Res User 7', 'Res User 8', 'Res User 9', 'Res User 10', 'Res User 11', 'Ext Ref Id7', 'Wrk Loc Cd7', 'Hm Loc Cd7', 'Proj Id From7', 'Actv Id From7', 'WPD Id7', 'Casual Id7', 'Est Pric Cd7', 'Work Grp Cd7', 'Work Grp From7', 'Lbr Rate Cd7', 'Bulk Alctn Cd7', 'Ovrhd Base Yr Cd7', 'Class Cd7', 'JV Item Cd7', 'Acct Per', 'Due Date', 'Fiscal Year', 'FC Trans Cd7', 'Var Dt7', 'Avg Rt Select Cd7', 'Ext System Cd7', 'BUS Unit BD', 'BUS Unit AR', 'BUS Unit PO', 'Profile Id', 'Req Id', 'Res Detail Id7', 'Group ByNum'];
    var colModel = [
         { name: 'MCTR_NO', index: 'MCTR_NO', classes: 'cell', stype: 'integer',width:60, editable: false },
         { name: 'LINE_NO', index: 'LINE_NO', classes: 'cell', stype: 'short', width: 50, editable: false },
        { name: 'FROM_TO', index: 'FROM_TO', stype: 'text', classes: 'cell', width: 50, editable: false },
        { name: 'LINE_NO_OH', index: 'LINE_NO_OH', classes: 'cell', stype: 'short', width: 60, editable: false }, ];

    var colModelRight = [
     { name: 'INTFC_LINE_NUM', index: 'INTFC_LINE_NUM', classes: 'cell', stype: 'decimal', editable: false },
    { name: 'BUSINESS_UNIT', index: 'BUSINESS_UNIT', classes: 'cell', stype: 'text', editable: false },
    { name: 'PROJECT_ID', index: 'PROJECT_ID', stype: 'text', classes: 'cell', editable: false },
 { name: 'ACTIVITY_ID', index: 'ACTIVITY_ID', classes: 'cell', stype: 'text', editable: false },
         { name: 'LEDGER_GROUP', index: 'LEDGER_GROUP', classes: 'cell', stype: 'text', editable: false },
    { name: 'BUSINESS_UNIT_GL', index: 'BUSINESS_UNIT_GL', classes: 'cell', stype: 'text', editable: false },
    { name: 'JOURNAL_ID', index: 'JOURNAL_ID', stype: 'text', classes: 'cell', editable: false },
 { name: 'INTFC_STATUS', index: 'INTFC_STATUS', classes: 'cell', stype: 'text', editable: false },
         { name: 'LOAD_STATUS', index: 'LOAD_STATUS', classes: 'cell', stype: 'text', editable: false },
    { name: 'ACTIVITY_TYPE', index: 'ACTIVITY_TYPE', classes: 'cell', stype: 'text', editable: false },
    { name: 'LEDGER', index: 'LEDGER', stype: 'text', classes: 'cell', editable: false },
 { name: 'OPRID', index: 'OPRID', classes: 'cell', stype: 'text', editable: false },
         { name: 'ACCOUNT', index: 'ACCOUNT', classes: 'cell', stype: 'text', editable: false },
    { name: 'MAJOR_ACCOUNT_NBR7', index: 'MAJOR_ACCOUNT_NBR7', classes: 'cell', stype: 'text', editable: false },
    { name: 'DEPTID', index: 'DEPTID', stype: 'text', classes: 'cell', editable: false },
 { name: 'OVRHD_ALCTN_CD7', index: 'OVRHD_ALCTN_CD7', classes: 'cell', stype: 'text', editable: false },
         { name: 'AFFILIATE', index: 'AFFILIATE', classes: 'cell', stype: 'text', editable: false },
    { name: 'DEPTID_FROM', index: 'DEPTID_FROM', classes: 'cell', stype: 'text', editable: false },
    { name: 'OVRHD_ALC_CD_FROM7', index: 'OVRHD_ALC_CD_FROM7', stype: 'text', classes: 'cell', editable: false },
 { name: 'BUS_UNIT_GL_FROM', index: 'BUS_UNIT_GL_FROM', classes: 'cell', stype: 'text', editable: false },
 { name: 'CURRENCY_CD', index: 'CURRENCY_CD', classes: 'cell', stype: 'text', editable: false },
         { name: 'STATISTICS_CODE', index: 'STATISTICS_CODE', classes: 'cell', stype: 'text', editable: false },
    { name: 'ANALYSIS_TYPE', index: 'ANALYSIS_TYPE', classes: 'cell', stype: 'text', editable: false },
    { name: 'RESOURCE_TYPE', index: 'RESOURCE_TYPE', stype: 'text', classes: 'cell', editable: false },
 { name: 'RESOURCE_SUB_CAT', index: 'RESOURCE_SUB_CAT', classes: 'cell', stype: 'text', editable: false },
 { name: 'TRANS_DT', index: 'TRANS_DT', classes: 'cell', stype: 'text', formatter: 'date', formatoptions: { srcformat: 'd/m/Y', newformat: 'Y/m/d' }, editable: false },
    { name: 'ACCOUNTING_DT', index: 'ACCOUNTING_DT', classes: 'cell', formatter: 'date', formatoptions: { srcformat: 'd/m/Y', newformat: 'Y/m/d' }, editable: false },
    { name: 'DTTM_STAMP', index: 'DTTM_STAMP', formatter: 'date', formatoptions: { srcformat: 'd/m/Y', newformat: 'Y/m/d' }, classes: 'cell', editable: false },
 { name: 'JRNL_LN_REF', index: 'JRNL_LN_REF', classes: 'cell', stype: 'text', editable: false },
 { name: 'OPEN_ITEM_STATUS', index: 'OPEN_ITEM_STATUS', classes: 'cell', stype: 'text', editable: false },
    { name: 'LINE_DESCR', index: 'LINE_DESCR', stype: 'text', classes: 'cell', editable: false },
 { name: 'JOURNAL_LINE_DATE', index: 'JOURNAL_LINE_DATE', classes: 'cell', formatter: 'date', formatoptions: { srcformat: 'd/m/Y', newformat: 'Y/m/d' }, editable: false },
 { name: 'FOREIGN_CURRENCY', index: 'FOREIGN_CURRENCY', classes: 'cell', stype: 'text', editable: false },
    { name: 'RT_TYPE', index: 'RT_TYPE', classes: 'cell', stype: 'text', editable: false },
    { name: 'FOREIGN_AMOUNT', index: 'FOREIGN_AMOUNT', stype: 'decimal', classes: 'cell', editable: false },
 { name: 'RATE_MULT', index: 'RATE_MULT', classes: 'cell', stype: 'decimal', editable: false },
 { name: 'CUR_EFFDT', index: 'CUR_EFFDT', classes: 'cell', formatter: 'date', formatoptions: { srcformat: 'd/m/Y', newformat: 'Y/m/d' }, editable: false },
    { name: 'PROCESS_INSTANCE', index: 'PROCESS_INSTANCE', stype: 'integer', classes: 'cell', editable: false },
 { name: 'PROJ_TRANS_TYPE', index: 'PROJ_TRANS_TYPE', classes: 'cell', stype: 'text', editable: false },
 { name: 'PROJ_TRANS_CODE', index: 'PROJ_TRANS_CODE', classes: 'cell', stype: 'text', editable: false },
    { name: 'SYSTEM_SOURCE', index: 'SYSTEM_SOURCE', stype: 'text', classes: 'cell', editable: false },
 { name: 'UNIT_OF_MEASURE', index: 'UNIT_OF_MEASURE', classes: 'cell', stype: 'text', editable: false },
 { name: 'EMPLID', index: 'EMPLID', classes: 'cell', stype: 'text', editable: false },
    { name: 'BUSINESS_UNIT_AP', index: 'BUSINESS_UNIT_AP', classes: 'cell', stype: 'text', editable: false },
    { name: 'VENDOR_ID', index: 'VENDOR_ID', stype: 'text', classes: 'cell', editable: false },
 { name: 'VOUCHER_ID', index: 'VOUCHER_ID', classes: 'cell', stype: 'text', editable: false },
 { name: 'VOUCHER_LINE_NUM', index: 'VOUCHER_LINE_NUM', classes: 'cell', stype: 'decimal', editable: false },
    { name: 'APPL_JRNL_ID', index: 'APPL_JRNL_ID', stype: 'text', classes: 'cell', editable: false },
 { name: 'PO_ID', index: 'PO_ID', classes: 'cell', stype: 'text', editable: false },
 { name: 'BUSINESS_UNIT_AM', index: 'BUSINESS_UNIT_AM', classes: 'cell', stype: 'text', editable: false },
    { name: 'ASSET_ID', index: 'ASSET_ID', stype: 'text', classes: 'cell', editable: false },
 { name: 'CUST_ID', index: 'CUST_ID', classes: 'cell', stype: 'text', editable: false },
 { name: 'ITEM', index: 'ITEM', classes: 'cell', stype: 'text', editable: false },
 { name: 'RESOURCE_QUANTITY', index: 'RESOURCE_QUANTITY', classes: 'cell', stype: 'decimal', editable: false },
    { name: 'RESOURCE_AMOUNT', index: 'RESOURCE_AMOUNT', classes: 'cell', stype: 'decimal', editable: false },
    { name: 'RES_USER1', index: 'RES_USER1', stype: 'text', classes: 'cell', editable: false },
 { name: 'RES_USER2', index: 'RES_USER2', classes: 'cell', stype: 'text', editable: false },
 { name: 'RES_USER3', index: 'RES_USER3', classes: 'cell', stype: 'text', editable: false },
    { name: 'RES_USER4', index: 'RES_USER4', stype: 'text', classes: 'cell', editable: false },
 { name: 'RES_USER5', index: 'RES_USER5', classes: 'cell', stype: 'text', editable: false },
 { name: 'RES_USER6', index: 'RES_USER6', classes: 'cell', stype: 'text', editable: false },
    { name: 'RES_USER7', index: 'RES_USER7', stype: 'text', classes: 'cell', editable: false },
 { name: 'RES_USER8', index: 'RES_USER8', classes: 'cell', stype: 'text', editable: false },
 { name: 'RES_USER9', index: 'RES_USER9', classes: 'cell', stype: 'text', editable: false },
    { name: 'RES_USER10', index: 'RES_USER10', classes: 'cell', stype: 'text', editable: false },
    { name: 'RES_USER11', index: 'RES_USER11', stype: 'text', classes: 'cell', editable: false },
 { name: 'EXT_REFERENCE_ID7', index: 'EXT_REFERENCE_ID7', classes: 'cell', stype: 'text', editable: false },
 { name: 'WORK_LOCATION_CD7', index: 'WORK_LOCATION_CD7', classes: 'cell', stype: 'text', editable: false },
    { name: 'HOME_LOCATION_CD7', index: 'HOME_LOCATION_CD7', stype: 'text', classes: 'cell', editable: false },
 { name: 'PROJECT_ID_FROM7', index: 'PROJECT_ID_FROM7', classes: 'cell', stype: 'text', editable: false },
 { name: 'ACTIVITY_ID_FROM7', index: 'ACTIVITY_ID_FROM7', classes: 'cell', stype: 'text', editable: false },
    { name: 'WPD', index: 'WPD', stype: 'text', classes: 'cell', editable: false },
 { name: 'CAUSAL_ID7', index: 'CAUSAL_ID7', classes: 'cell', stype: 'text', editable: false },
 { name: 'ESTMTG_PRICG_CD7', index: 'ESTMTG_PRICG_CD7', classes: 'cell', stype: 'text', editable: false },
    { name: 'WORK_GROUP_CD7', index: 'WORK_GROUP_CD7', classes: 'cell', stype: 'text', editable: false },
    { name: 'WORK_GROUP_FROM7', index: 'WORK_GROUP_FROM7', stype: 'text', classes: 'cell', editable: false },
 { name: 'LABOR_RATE_CD7', index: 'LABOR_RATE_CD7', classes: 'cell', stype: 'text', editable: false },
 { name: 'BULK_ALCTN_CD7', index: 'BULK_ALCTN_CD7', classes: 'cell', stype: 'text', editable: false },
 { name: 'OVRHD_BASE_YR_CD7', index: 'OVRHD_BASE_YR_CD7', classes: 'cell', stype: 'text', editable: false },
    { name: 'CLASS_CD7', index: 'CLASS_CD7', stype: 'text', classes: 'cell', editable: false },
 { name: 'JV_ITEM_CD7', index: 'JV_ITEM_CD7', classes: 'cell', stype: 'text', editable: false },
 { name: 'ACCOUNTING_PERIOD', index: 'ACCOUNTING_PERIOD', classes: 'cell', stype: 'decimal', editable: false },
    { name: 'DUE_DATE', index: 'DUE_DATE', formatter: 'date', formatoptions: { srcformat: 'd/m/Y', newformat: 'Y/m/d' }, classes: 'cell', editable: false },
 { name: 'FISCAL_YEAR', index: 'FISCAL_YEAR', classes: 'cell', stype: 'decimal', editable: false },
 { name: 'FC_TRANSLATION_CD7', index: 'FC_TRANSLATION_CD7', classes: 'cell', stype: 'text', editable: false },
    { name: 'VARIABLE_DT7', index: 'VARIABLE_DT7', classes: 'cell', formatter: 'date', formatoptions: { srcformat: 'd/m/Y', newformat: 'Y/m/d' }, editable: false },
    { name: 'AVG_RT_SELECT_CD7', index: 'AVG_RT_SELECT_CD7', stype: 'text', classes: 'cell', editable: false },
 { name: 'EXT_SYSTEM_CD7', index: 'EXT_SYSTEM_CD7', classes: 'cell', stype: 'text', editable: false },
 { name: 'BUSINESS_UNIT_BD', index: 'BUSINESS_UNIT_BD', classes: 'cell', stype: 'text', editable: false },
 { name: 'BUSINESS_UNIT_AR', index: 'BUSINESS_UNIT_AR', classes: 'cell', stype: 'text', editable: false },
 { name: 'BUSINESS_UNIT_PO', index: 'BUSINESS_UNIT_PO', classes: 'cell', stype: 'text', editable: false },
    { name: 'PROFILE_ID', index: 'PROFILE_ID', stype: 'text', classes: 'cell', editable: false },
 { name: 'REQ_ID', index: 'REQ_ID', classes: 'cell', stype: 'text', editable: false },
 { name: 'RES_DETAIL_ID7', index: 'RES_DETAIL_ID7', classes: 'cell', stype: 'decimal', editable: false },
    { name: 'GROUPBYNUM', index: 'GROUPBYNUM', stype: 'decimal', classes: 'cell', editable: false },


    ];
   

    mctrObj.CreateJqGrid('leftPanelGrid', '/MctrWkipJrnlsBl/jrnlWeekJrnlWeekOnLoadJson?mctrNo='+MctrNo, 'GET', {}, columnNames, colModel, false, 'SETID', [], 100, '100%', 'desc', false);

    mctrObj.CreateJqGrid('rightPanelGrid', '/MctrWkipJrnlsBl/jrnlWeekJrnlWeekOnLoadJson?mctrNo='+MctrNo, 'GET', {}, columnNamesRight, colModelRight, false, 'SETID', [], 100, '100%', 'desc', false);

});