using System;
using System.ComponentModel;
///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///
///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  
namespace MCTR.DomainEntity
{
    //********************************************************************
    ///<summary>
    ///LineItem is a domain model which refelects the screen components.
    ///</summary>
    public class LineItem : Global
    {

        public int MCTR_NO { get; set; }
        public short LINE_NO { get; set; }
        public Nullable<System.DateTime> PERIOD_FROM { get; set; }
        public Nullable<System.DateTime> PERIOD_TO { get; set; }
        public string TTD_FLAG { get; set; }
        public string PER_FLAG { get; set; }
        public string BEMS_1 { get; set; }
        public string APPR_CD_1 { get; set; }
        public Nullable<System.DateTime> DATE_APPR_1 { get; set; }
        public string BEMS_2 { get; set; }
        public string APPR_CD_2 { get; set; }
        public Nullable<System.DateTime> DATE_APPR_2 { get; set; }
        public string BEMS_3 { get; set; }
        public string APPR_CD_3 { get; set; }
        public Nullable<System.DateTime> DATE_APPR_3 { get; set; }
        public string ACTIVITY_ID_FROM { get; set; }
        public string PROJECT_ID_FROM { get; set; }
        public string ACCOUNT_FROM { get; set; }
        public string BUM_CD7_FROM { get; set; }
        public string HOME_DEPT_FROM { get; set; }
        public string HOME_LOC_FROM { get; set; }
        public string HOME_BUGL_FROM { get; set; }
        public string HOME_POOL_FROM { get; set; }
        public string LABOR_RATE_CD7_FROM { get; set; }
        public string CLASS_CD_FROM { get; set; }
        public string CUST_TYPE_CD7_FROM { get; set; }
        public string WORK_DEPT_FROM { get; set; }
        public string WORK_LOC_FROM { get; set; }
        public string WORK_BUGL_FROM { get; set; }
        public string WORK_POOL_FROM { get; set; }
        public string RSC_FROM { get; set; }
        public string PROJ_TRANS_TYPE_FROM { get; set; }
        public string PROJ_TRANS_CODE_FROM { get; set; }
        public string STAT_CODE_FROM { get; set; }
        public string UOM_FROM { get; set; }
        public string BULK_ALCTN_CD7_FROM { get; set; }
        public string WPD_ID7_FROM { get; set; }
        public Nullable<short> OH_BASE_YR_FROM { get; set; }
        public Nullable<decimal> QUANTITY_FROM { get; set; }
        public Nullable<decimal> AMOUNT_FROM { get; set; }
        public Nullable<decimal> ADJUSTMENT_FROM { get; set; }
        public string ACTIVITY_ID_TO { get; set; }
        public string PROJECT_ID_TO { get; set; }
        public string ACCOUNT_TO { get; set; }
        public string BUM_CD7_TO { get; set; }
        public string HOME_DEPT_TO { get; set; }
        public string HOME_LOC_TO { get; set; }
        public string HOME_BUGL_TO { get; set; }
        public string HOME_POOL_TO { get; set; }
        public string LABOR_RATE_CD7_TO { get; set; }
        public string CLASS_CD_TO { get; set; }
        public string CUST_TYPE_CD7_TO { get; set; }
        public string WORK_DEPT_TO { get; set; }
        public string WORK_LOC_TO { get; set; }
        public string WORK_BUGL_TO { get; set; }
        public string WORK_POOL_TO { get; set; }
        public string RSC_TO { get; set; }
        public string PROJ_TRANS_TYPE_TO { get; set; }
        public string PROJ_TRANS_CODE_TO { get; set; }
        public string STAT_CODE_TO { get; set; }
        public string UOM_TO { get; set; }
        public Nullable<short> OH_BASE_YR_TO { get; set; }
        public Nullable<decimal> QUANTITY_TO { get; set; }
        public Nullable<decimal> AMOUNT_TO { get; set; }
        public Nullable<decimal> ADJUSTMENT_TO { get; set; }
        public string MTL_JRNL { get; set; }
        public string CONTRACT_NUM_FROM { get; set; }
        public string CONTRACT_NUM_TO { get; set; }
        public string BUM_CD7_TO_ORIG { get; set; }
        public string WPD_FROM { get; set; }
        public string WPD_TO { get; set; }
        public string BULK_FROM { get; set; }
        public string BULK_TO { get; set; }
        public string CAUSAL_ID_FROM { get; set; }
        public string CAUSAL_ID_TO { get; set; }
        public string ESTMTG_PRICG_CD_FROM { get; set; }
        public string ESTMTG_PRICG_CD_TO { get; set; }
        public string PO_ID_FROM { get; set; }
        public string PO_ID_TO { get; set; }
        public string PART_NO_FROM { get; set; }
        public string PART_NO_TO { get; set; }
        public string EPACS_CTT_FROM { get; set; }
        public string EPACS_CTT_TO { get; set; }
        public string SHOP_ORDER_FROM { get; set; }
        public string SHOP_ORDER_TO { get; set; }
        public string PO_LINE_FROM { get; set; }
        public string PO_LINE_TO { get; set; }
        public string ACTY_RED_FLG_FROM { get; set; }
        public string ACTY_RED_FLG_TO { get; set; }
        public string DEPT_RED_FLG_FROM { get; set; }
        public string DEPT_RED_FLG_TO { get; set; }
        public string WORK_DEPT_RED_FLG_FROM { get; set; }
        public string WORK_DEPT_RED_FLG_TO { get; set; }
        public Nullable<decimal> MATERIAL_QUANTITY_FROM { get; set; }
        public Nullable<decimal> MATERIAL_QUANTITY_TO { get; set; }
        public string AFFILIATE_FROM { get; set; }
        public string AFFILIATE_TO { get; set; }
        public string Bems_Orig{ get; set; }

        public string jv_item_cd { get; set; }

        public string appl_jrnl_id { get; set; }

        public string from_to { get; set; }
        public LineItemDomainAdded LineItemDomainAdded { set; get; }
        public Nullable<decimal> OVH_AMOUNT_FROM { get; set; }
        public Nullable<decimal> OVH_AMOUNT_TO { get; set; }


    }
}
