///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///
///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  

using System;
using System.ComponentModel.DataAnnotations;

namespace MCTR.DomainEntity
{
///*********************************************************************
///<summary>
///MctrAttachBl is a domain model which refelects the screen components.
///</summary>
  public class MctrAttachBl {

        public int MCTR_NO { get; set; }
        public short ATTACH_NO { get; set; }
        [Required]
        public string ATTACH_FILENAME { get; set; }
        public string BEMS { get; set; }
        public Nullable<System.DateTime> DATE_ENTERED { get; set; }
        [Required]
        public string ATTACH_DESCR { get; set; }
        [Required]
        public byte[] ATTACH_BLOB { get; set; }

    }
}
