


using System;
///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///
///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  
namespace MCTR.DomainEntity
{
///*********************************************************************
///<summary>
///PerCheckBl is a domain model which refelects the screen components.
///</summary>
  public class PerCheckBl {

        public int MCTR_NO { get; set; }
        public short LINE_NO { get; set; }
        public short SEQ_NO { get; set; }
        public Nullable<short> FISCAL_YEAR { get; set; }
        public Nullable<short> ACCOUNTING_PERIOD { get; set; }
        public string ANALYSIS_TYPE { get; set; }
        public string ACTIVITY_ID { get; set; }
        public string PROJECT_ID { get; set; }
        public string ACCOUNT { get; set; }
        public string HOME_DEPT { get; set; }
        public string HOME_LOC { get; set; }
        public string HOME_BUGL { get; set; }
        public string HOME_POOL { get; set; }
        public string WORK_DEPT { get; set; }
        public string WORK_LOC { get; set; }
        public string WORK_BUGL { get; set; }
        public string WORK_POOL { get; set; }
        public string RSC { get; set; }
        public string PROJ_TRANS_TYPE { get; set; }
        public string PROJ_TRANS_CODE { get; set; }
        public Nullable<decimal> QUANTITY_YTD { get; set; }
        public Nullable<decimal> AMOUNT_YTD { get; set; }
        public string WPD { get; set; }
        public string BULK_ALCTN_CD7 { get; set; }
        public string CLASS_CD { get; set; }
        public string AFFILIATE { get; set; }
        public string OVRHD_BASE_YR_CD7 { get; set; }
        public virtual LineItem LineItem { get; set; }

    }
}
