///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MCTR.DomainEntity
{
    public class StatusHistHeader
    {
     
        public int Mctr_No { get; set; }
        public string title { get; set; }
        public string orig_bu { get; set; }
        public string orig_group { get; set; }
        public int fiscal_year { get; set; }
        public string reason_code { get; set; }
        public string reason_descr { get; set; }
        public string status_id { get; set; }
        public string status_descr { get; set; }
        public string date_enter { get; set; }
        public string date_journal { get; set; }
        public string appl_jrnl_id { get; set; }
        public string jv_item_cd { get; set; }
        public string bems_orig { get; set; }
        public string bems_orig_name { get; set; }

        public string descr { get; set; }

    }
}
