



///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///
///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  
using System;
using System.ComponentModel;
namespace MCTR.DomainEntity

{
///*********************************************************************
///<summary>
///StatHistBl is a domain model which refelects the screen components.
///</summary>
/// 
[DisplayName("My Model")]
  public class StatHistBl {

    	public Nullable<System.DateTime> Date_Time_Entered { set; get; }

    	public Nullable<System.DateTime> Date_Time_Left { set; get; }

    	public string Prior_Status { set; get; }

    	public string Next_Status { set; get; }
        public string Status_Descr { set; get; }
        public string reject_code { set; get; }
        public string reject_reason { set; get; }


    }
}
