//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTR.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCTR_ROLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MCTR_ROLE()
        {
            this.MCTR_HEADER = new HashSet<MCTR_HEADER>();
            this.MCTR_HEADER1 = new HashSet<MCTR_HEADER>();
            this.MCTR_HEADER2 = new HashSet<MCTR_HEADER>();
            this.MCTR_HEADER3 = new HashSet<MCTR_HEADER>();
            this.MCTR_HEADER4 = new HashSet<MCTR_HEADER>();
            this.MCTR_HEADER5 = new HashSet<MCTR_HEADER>();
            this.MCTR_HEADER6 = new HashSet<MCTR_HEADER>();
            this.MCTR_LINE_ITEM = new HashSet<MCTR_LINE_ITEM>();
            this.MCTR_LINE_ITEM1 = new HashSet<MCTR_LINE_ITEM>();
            this.MCTR_LINE_ITEM2 = new HashSet<MCTR_LINE_ITEM>();
            this.MCTR_ROLE_BU = new HashSet<MCTR_ROLE_BU>();
        }
    
        public string BEMS { get; set; }
        public string ACTIVE { get; set; }
        public string ACCOUNTANT_ROLE { get; set; }
        public string MATL_ACCT_ROLE { get; set; }
        public string COST_ACCT_ROLE { get; set; }
        public string FIN_CONTROL_ROLE { get; set; }
        public string SR_ACCT_ROLE { get; set; }
        public Nullable<System.DateTime> DATE_INIT_ADD { get; set; }
        public Nullable<System.DateTime> DATE_UPDATE { get; set; }
        public string BEMS_ADMIN { get; set; }
        public string LAST_BU { get; set; }
        public string LAST_LOC { get; set; }
        public string LAST_DEPT { get; set; }
        public string OVRRD_GRP_CD { get; set; }
        public Nullable<System.DateTime> LAST_LOGON { get; set; }
        public string ADMIN_ROLE { get; set; }
        public string LBR_ACCT_ROLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCTR_HEADER> MCTR_HEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCTR_HEADER> MCTR_HEADER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCTR_HEADER> MCTR_HEADER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCTR_HEADER> MCTR_HEADER3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCTR_HEADER> MCTR_HEADER4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCTR_HEADER> MCTR_HEADER5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCTR_HEADER> MCTR_HEADER6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCTR_LINE_ITEM> MCTR_LINE_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCTR_LINE_ITEM> MCTR_LINE_ITEM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCTR_LINE_ITEM> MCTR_LINE_ITEM2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCTR_ROLE_BU> MCTR_ROLE_BU { get; set; }
    }
}
