//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTR.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCTR_PROJECT_V
    {
        public string SETID { get; set; }
        public string BUSINESS_UNIT_GL { get; set; }
        public string PROJECT_ID { get; set; }
        public string ACCOUNT { get; set; }
        public string BUS_UNIT_MGMT_CD7 { get; set; }
        public string CUSTOMER_TYPE_CD7 { get; set; }
        public string CONTRACT_NUM { get; set; }
        public System.DateTime EFFDT { get; set; }
        public string EFF_STATUS { get; set; }
    }
}
