//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTR.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCTR_JOB_LOG
    {
        public string JOB_ID { get; set; }
        public System.DateTime RUN_DT { get; set; }
        public System.DateTime END_DT { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<System.DateTime> DATE_JOURNAL { get; set; }
        public Nullable<System.DateTime> COW_ACCTG_DT { get; set; }
        public Nullable<decimal> MCTR_JRNL_SEL_CNT { get; set; }
        public Nullable<decimal> STGD_JRNL_LOD_CNT { get; set; }
        public Nullable<decimal> HIST_JRNL_LOD_CNT { get; set; }
        public Nullable<decimal> MCTR_JRNL_DEL_CNT { get; set; }
        public Nullable<decimal> STGD_AUDT_LOD_CNT { get; set; }
        public Nullable<decimal> MCTR_HEADER_SEL_CNT { get; set; }
        public Nullable<decimal> MCTR_HEADER_UPD_CNT { get; set; }
        public Nullable<decimal> MCTR_STATUS_UPD_CNT { get; set; }
        public Nullable<decimal> MCTR_STATUS_INS_CNT { get; set; }
        public Nullable<System.DateTime> JRNL_HIST_PURG_DT { get; set; }
        public Nullable<decimal> JRNL_HIST_DEL_CNT { get; set; }
        public Nullable<decimal> JOB_LOG_DEL_CNT { get; set; }
        public Nullable<decimal> STGD_JRNL_DEL_CNT { get; set; }
        public string NOTES { get; set; }
    }
}
