//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTR.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCTR_BU_PROFILE
    {
        public string BUSINESS_UNIT { get; set; }
        public string BULK_FLG { get; set; }
        public string OFFSET_ACTIVITY { get; set; }
        public string OFFSET_PROJECT { get; set; }
        public string OFFSET_ACCOUNT { get; set; }
        public string RSC_LBR_FLG { get; set; }
        public string BEMS_ADMIN { get; set; }
        public string CLS_VDT_FLG { get; set; }
        public string REJECT_FLG { get; set; }
        public string MAN_RATED_FLG { get; set; }
        public string PYR_ONLY_FLG { get; set; }
    }
}
