//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTR.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCTR_EMPLOYEE_V
    {
        public string BEMS_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_INT { get; set; }
        public string LAST_NAME { get; set; }
        public string COMPONENT { get; set; }
        public string BUS_UNIT { get; set; }
        public string DIVISION { get; set; }
        public string DEPTNO { get; set; }
        public string EMP_STATUS { get; set; }
        public string CONTRACT_VENDOR_CODE { get; set; }
        public string LOCATION { get; set; }
        public string MGR_ID { get; set; }
        public string HR_MGR_LAST_NAME { get; set; }
        public string HR_MGR_FIRST_NAME { get; set; }
        public string ACCTG_BUS_UNIT_NM { get; set; }
        public string ACCT_DEPT_NM { get; set; }
        public string STABLE_EMAIL { get; set; }
        public string DEPT_NMW { get; set; }
        public string ACCTG_LOC_CDM { get; set; }
        public string LA_MGR_ID_BEMS { get; set; }
        public string LA_MGR_LAST_NAME { get; set; }
        public string LA_MGR_FIRST_NAME { get; set; }
        public string WORK_PHONE { get; set; }
        public string MAIL_CODE { get; set; }
    }
}
