//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTR.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCTR_CONTRACT_HIRE
    {
        public string CLOCK_NO { get; set; }
        public string BEMS_ID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string CMPON_CD { get; set; }
        public string DEPT { get; set; }
        public string STATUS { get; set; }
        public string MAILCODE { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string ACTG_LOC { get; set; }
    }
}
