//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTR.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTBL_MAJOR_ACCT
    {
        public string SETID { get; set; }
        public string MAJOR_ACCOUNT_NBR7 { get; set; }
        public System.DateTime EFFDT { get; set; }
        public string EFF_STATUS { get; set; }
        public string DESCR { get; set; }
        public string DESCRSHORT { get; set; }
        public string BILLABLE_FLG7 { get; set; }
        public string ACCOUNT_SE_GRP_CD7 { get; set; }
        public string INTERUNIT_FLG { get; set; }
        public string STATISTICS_ACCOUNT { get; set; }
        public string WPD_INDIRECT_FLG7 { get; set; }
        public string ACT_VALIDN_MA_CD7 { get; set; }
    }
}
