//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCTR.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTBL_ESTMT_PRIC
    {
        public string SETID { get; set; }
        public string ESTMTG_PRICG_CD7 { get; set; }
        public System.DateTime EFFDT { get; set; }
        public string EFF_STATUS { get; set; }
        public string DESCR { get; set; }
        public string DESCRSHORT { get; set; }
    }
}
