///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using MCTR.DomainEntity;

namespace MCTR.DataAccessInterface
{
   public interface ICreateMctrLovRepository
    {
        ///*************************************************************
        ///<summary>
        ///Method Name : getRgYearLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgYearLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgReasonLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgReasonLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgSuperLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgSuperLOV(IEnumerable<CreateMctrLov> createMctrLov);
        ///*************************************************************
        ///<summary>
        ///Method Name : getRgApplLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgApplLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgApprSuperLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgApprSuperLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgFinCtlLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgFinCtlLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgApprFinCtlLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgApprFinCtlLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgAcctLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgAcctLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgAcctLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgApprAcctLOV(IEnumerable<CreateMctrLov> createMctrLov);


        ///*************************************************************
        ///<summary>
        ///Method Name : getRgLbrAcctLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgLbrAcctLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgApprLbrAcctLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgApprLbrAcctLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgMatlAcctLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgMatlAcctLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgApprMatlAcctLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgApprMatlAcctLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgCostAcctLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgCostAcctLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgApprCostAcctLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgApprCostAcctLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgSrAcctLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgSrAcctLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgApprSrAcctLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgApprSrAcctLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgLiBemsLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgLiBemsLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgRejectLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgRejectLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgProjFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgProjFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgProjFromPromptLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgProjFromPromptLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgTransFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgTransFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgHomeDeptFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgHomeDeptFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgHomeDeptLocFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgHomeDeptLocFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgListHomeDeptFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgListHomeDeptFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgHomeLocFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgHomeLocFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgListHomeLocFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgListHomeLocFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgClassCodeFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgClassCodeFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgListClassCodeFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgListClassCodeFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgWorkDeptFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgWorkDeptFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgWorkDeptLocFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgWorkDeptLocFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgListWorkDeptFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgListWorkDeptFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgWorkLocFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgWorkLocFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgListWorkLocFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgListWorkLocFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgRscFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgRscFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgWpdFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgWpdFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgBulkFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgBulkFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgCecEpFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgCecEpFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgListCecEpFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgListCecEpFromLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgProjToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgProjToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgProjToPromptLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgProjToPromptLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgHomeDeptToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgHomeDeptToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgHomeDeptToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgHomeDeptLocToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgListHomeDeptToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgListHomeDeptToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgHomeLocToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgHomeLocToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgListHomeLocToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgListHomeLocToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgClassCodeToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgClassCodeToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgListClassCodeToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgListClassCodeToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgWorkDeptToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgWorkDeptToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgWorkDeptLocToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgWorkDeptLocToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgListWorkDeptToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgListWorkDeptToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgWorkLocToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgWorkLocToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgListWorkLocToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgListWorkLocToLOV(IEnumerable<CreateMctrLov> createMctrLov);
        ///*************************************************************
        ///<summary>
        ///Method Name : getRgRscToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgRscToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgWpdToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgWpdToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgBulkToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgBulkToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgCecEpToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgCecEpToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgListCecEpToLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgListCecEpToLOV(IEnumerable<CreateMctrLov> createMctrLov);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgAffiliateFromLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<CreateMctrLov> getRgAffiliateFromLOV(IEnumerable<CreateMctrLov> createMctrLov);


    }
}
