///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  

using System.Collections.Generic;
using MCTR.DomainEntity;

namespace MCTR.DataAccessInterface
{
    ///*********************************************************************
    ///<summary>
    ///IMctrOpenReportsBlRepository is an data access interface for the MctrOpenReportsBlRepository   
    ///which facilitates the dependency injection.
    ///</summary>
    public interface IMctrOpenReportsBlRepository //: IDataRepository
  { 
     
    ///*************************************************************
    ///<summary>
    ///Method Name : selectionoriginatorWhenButtonPressed
    ///</summary>
    ///<param name = "MctrOpenReportsBl"></param>
    ///<returns>IEnumerable<MctrOpenReportsBl> </returns>
    IEnumerable<MctrOpenReportsBl> selectionoriginatorWhenButtonPressed(IEnumerable<MctrOpenReportsBl> mctrOpenReportsBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : selectionstatusWhenButtonPressed
    ///</summary>
    ///<param name = "MctrOpenReportsBl"></param>
    ///<returns>IEnumerable<MctrOpenReportsBl> </returns>
    IEnumerable<MctrOpenReportsBl> selectionstatusWhenButtonPressed(IEnumerable<MctrOpenReportsBl> mctrOpenReportsBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : selectionfinancialControlWhenButtonPressed
    ///</summary>
    ///<param name = "MctrOpenReportsBl"></param>
    ///<returns>IEnumerable<MctrOpenReportsBl> </returns>
    IEnumerable<MctrOpenReportsBl> selectionfinancialControlWhenButtonPressed(IEnumerable<MctrOpenReportsBl> mctrOpenReportsBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : selectionbutExcelWhenButtonPressed
    ///</summary>
    ///<param name = "MctrOpenReportsBl"></param>
    ///<returns>IEnumerable<MctrOpenReportsBl> </returns>
    IEnumerable<MctrOpenReportsBl> selectionbutExcelWhenButtonPressed(IEnumerable<MctrOpenReportsBl> mctrOpenReportsBl);
       
       

    ///*************************************************************
    ///<summary>
    ///Method Name : getRgBuLOV
    ///</summary>
    ///<param name = "MctrOpenReportsBl"></param>
    ///<returns>IEnumerable<MctrOpenReportsBl> </returns>
    IEnumerable<MctrBusUnit> getRgBuLOV(IEnumerable<MctrBusUnit> mctrOpenReportsBl);


       
  }

}


