///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using MCTR.DomainEntity;

namespace MCTR.DataAccessInterface
{


    public interface IMctrCreateFormRepository 
    {

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgBuGrpLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<BusUnit> getRgBuGrpLOV(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrHeaderbutUnjrnlWhenButtonPressed(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItembutCopyWhenButtonPressed(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItemclassCdToPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<HeaderExcel> mctrheaderbuttoxlswhenbuttonpressed(IEnumerable<HeaderExcel> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItemamountToPostTextItem(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItemestmtgPricgCdToPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> submitBtnmctrLineItemquantityFromPostTextItem(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItemrscToPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItemworkLocToPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrRejectCode> getRgLOVReject(MctrRejectCode mctrRejectCode);

        IEnumerable<MctrCreateForm> mctrLineItemworkDeptToPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItemhomeBuglToPostTextItem(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> manRatedFlag(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItemaccountToPostTextItem(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItemestmtgPricgCdFromPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItemquantityFromPostTextItem(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItemhomeDeptToPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItemhomeLocToPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrHeaderonLoad(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrLineItem> mctrLineItemInsert(IEnumerable<MctrLineItem> mctrLineItem);

        IEnumerable<MctrLineItem> mctrLineItemDelete(IEnumerable<MctrLineItem> mctrCreateForm);
        IEnumerable<MctrLineItem> mctrLineItemPreDelete(IEnumerable<MctrLineItem> mctrCreateForm);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgYearLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<MctrCreateForm> getRgYearLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> justificationsave(IEnumerable<MctrCreateForm> mctrCreateForm);

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrHeaderbutJrnlWhenButtonPressed()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<MctrCreateForm> mctrHeaderbutJrnlWhenButtonPressed(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrHeaderbutJustificationWhenButtonPressed(IEnumerable<MctrCreateForm> mctrCreateForm);

        ///*************************************************************
        ///<summary>
        ///Method Name : getRgReasonLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        /// 

        IEnumerable<MctrCreateForm> getRgReasonLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrLineiteminquiry> ttdInqCyrTtdInqCyrOnLoad(IEnumerable<MctrLineiteminquiry> mctrlineitem);

        IEnumerable<MctrLineiteminquiry> ttdInqPyrTtdInqPyrOnLoad(IEnumerable<MctrLineiteminquiry> mctrlineitem);

        IEnumerable<MctrLineiteminquiry> ttdInqFilter(IEnumerable<MctrLineiteminquiry> mctrlineitem);

        IEnumerable<MctrLineItem> mctrLineItemOnLoad(IEnumerable<MctrLineItem> mctrLineItem);
        ///*************************************************************
        ///<summary>
        ///Method Name : getRgApplLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<MctrCreateForm> getRgApplLOV(IEnumerable<MctrCreateForm> mctrCreateForm);


        ///*************************************************************
        ///<summary>
        ///Method Name : getRgSuperLOV()
        ///</summary>
        ///<param name = "MctrCreateForm"></param>
        ///<returns>IEnumerable<MctrCreateForm> </returns>
        IEnumerable<MctrCreateForm> getRgSuperLOV(IEnumerable<MctrCreateForm> mctrCreateForm);


        IEnumerable<MctrCreateForm> mctrLineItemPostUpdate(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItemPostDelete(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItemPreUpdate(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItemPostInsert(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItemPreInsert(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItemPostQuery(IEnumerable<MctrCreateForm> mctrCreateForm);


        IEnumerable<MctrCreateForm> pycystatuscheckbubut(IEnumerable<MctrCreateForm> mctrCreateForm);


        IEnumerable<MctrCreateForm> fyearperiodvalidation(IEnumerable<MctrCreateForm> mctrCreateForm);


        IEnumerable<MctrCreateForm> validApprover(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrHeaderPreUpdate(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItemaccountFromPostTextItem(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItemaffiliateFromPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItemClassCditemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItemhomeLocFromPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItemhomeDeptFromPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItemwpdFromPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItemrscFromPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItemworkLocFromPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItemworkDeptFromPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<BuProfile> mctrLineItembulkFromPostTextItemOpenLOVBulkFlag(IEnumerable<BuProfile> BuProfile);

        IEnumerable<MctrCreateForm> mctrLineItembulkFromPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItembutBulkWhenButtonPressedOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItembutWpdWhenButtonPressedOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);

        IEnumerable<MctrCreateForm> mctrLineItemamountfromPostTextItemOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrHeaderbutBuWhenButtonPressedOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> buButPressPTTValidation(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrHeaderbutFiscalYearWhenButtonPressedOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrLineItem> overheadOnLoad(IEnumerable<MctrLineItem> mctrLineItem);
        IEnumerable<MctrLineItem> mctrLineItembutTransFromWhenButtonPressedOpenLOV(IEnumerable<MctrLineItem> mctrLineItem);
        IEnumerable<MctrCreateForm> ValidateActivityID(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrLineItembutProjToWhenButtonPressedOpenLOV(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> querymodecheck(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MctrCreateForm> mctrHeaderPreInsert(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MCTRComments> mctrCommentviewStatementWhenButtonPressed(IEnumerable<MCTRComments> mctrComments);
        IEnumerable<MctrCreateForm> mctrHeaderbutSubmitWhenButtonPressed(IEnumerable<MctrCreateForm> mctrCreateForm);
        IEnumerable<MCTRComments> mctrcommentonload(IEnumerable<MCTRComments> mctrComments);
        IEnumerable<MCTRComments> mctrCommentbutSaveWhenButtonPressed(IEnumerable<MCTRComments> mctrComments);
        IEnumerable<MCTRComments> mctrCommentpostquery(IEnumerable<MCTRComments> mctrComments);
        IEnumerable<MCTRComments> mctrCommentonmessage(IEnumerable<MCTRComments> mctrComments);
        IEnumerable<MCTRComments> mctrCommentpreinsert(IEnumerable<MCTRComments> mctrComments);
        IEnumerable<MCTRComments> mctrCommentOnInsert(IEnumerable<MCTRComments> mctrComments);
        IEnumerable<MctrCreateForm> batchModeCheck(IEnumerable<MctrCreateForm> mctrCreateForm);
    }
}

