///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  

using System.Collections.Generic;
using MCTR.DomainEntity;

namespace MCTR.DataAccessInterface
{
    ///*********************************************************************
    ///<summary>
    ///IMctrMainMenuRepository is an data access interface for the MctrMainMenuRepository   
    ///which facilitates the dependency injection.
    ///</summary>
    public interface IMctrMainMenuRepository //: IDataRepository
    {

        ///*************************************************************
        ///<summary>
        ///Method Name : buttonPalettebutAdminTblsWhenButtonPressed
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> buttonPalettebutAdminTblsWhenButtonPressed(IEnumerable<MctrMainMenu> mctrMainMenu);
        IEnumerable<Status> getDescription();

        IEnumerable<MctrMainMenu> populateActionTree(IEnumerable<MctrMainMenu> mctrMainMenu);

        IEnumerable<MctrMainMenu> populateAssignedAtree(IEnumerable<MctrMainMenu> mctrMainMenu);
    }

}

/*

     ///*************************************************************
        ///<summary>
        ///Method Name : actionTreeBlockactionTreeWhenTreeNodeExpanded
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> actionTreeBlockactionTreeWhenTreeNodeExpanded(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : actionTreeBlockactionTreeWhenTreeNodeActivated
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> actionTreeBlockactionTreeWhenTreeNodeActivated(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : actionTreeBlockOnError
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> actionTreeBlockOnError(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : buttonPalettebutMctrWhenButtonPressed
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> buttonPalettebutMctrWhenButtonPressed(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : buttonPalettebutLineItemWhenButtonPressed
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> buttonPalettebutLineItemWhenButtonPressed(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : buttonPalettebutRefreshWhenButtonPressed
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> buttonPalettebutRefreshWhenButtonPressed(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : buttonPalettebutCollapseWhenButtonPressed
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> buttonPalettebutCollapseWhenButtonPressed(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : buttonPalettebutReportsWhenButtonPressed
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> buttonPalettebutReportsWhenButtonPressed(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : buttonPalettebutUserListWhenButtonPressed
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> buttonPalettebutUserListWhenButtonPressed(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : buttonPaletteexitBtnWhenMouseClick
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> buttonPaletteexitBtnWhenMouseClick(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : buttonPalettecboxOpenonlyWhenCheckboxChanged
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> buttonPalettecboxOpenonlyWhenCheckboxChanged(IEnumerable<MctrMainMenu> mctrMainMenu);

    ///*************************************************************
        ///<summary>
        ///Method Name : buttonPalettecboxAccountantWhenCheckboxChanged
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> buttonPalettecboxAccountantWhenCheckboxChanged(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : webutildummyWhenButtonPressed
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> webutildummyWhenButtonPressed(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrMainMenuPreForm
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> mctrMainMenuPreForm(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrMainMenuOnError
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> mctrMainMenuOnError(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrMainMenuKeyExit
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> mctrMainMenuKeyExit(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrMainMenuWhenNewFormInstance
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> mctrMainMenuWhenNewFormInstance(IEnumerable<MctrMainMenu> mctrMainMenu);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrMainMenuRunReports
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> mctrMainMenuRunReports(IEnumerable<MctrMainMenu> mctrMainMenu);

///*************************************************************
        ///<summary>
        ///Method Name : mctrMainMenuWhenWindowActivated
        ///</summary>
        ///<param name = "MctrMainMenu"></param>
        ///<returns>IEnumerable<MctrMainMenu> </returns>
        IEnumerable<MctrMainMenu> mctrMainMenuWhenWindowActivated(IEnumerable<MctrMainMenu> mctrMainMenu);
*/
