///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MCTR.DomainEntity;

namespace MCTR.DataAccessInterface
{
  public interface IRoleListRepository 
  { 
    IEnumerable<RoleList> roleListOnLoad(IEnumerable<RoleList> roleList);
    IEnumerable<RoleList> roleListbutRoleWhenButtonPressed(IEnumerable<RoleList> roleList);
    IEnumerable<RoleList> roleListbutFindWhenButtonPressed(IEnumerable<RoleList> roleList);
    IEnumerable<RoleList> roleListPostQuery(IEnumerable<RoleList> roleList);
    IEnumerable<RoleList> roleListWhenNewFormInstance(IEnumerable<RoleList> roleList);       
  }

}

