///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///
 
///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using MCTR.DomainEntity;

namespace MCTR.DataAccessInterface
{
///*********************************************************************
///<summary>
///IStatHistBlRepository is an data access interface for the StatHistBlRepository   
///which facilitates the dependency injection.
///</summary>
  public interface IStatHistBlRepository //: IDataRepository
  { 
     

    ///*************************************************************
    ///<summary>
    ///Method Name : mctrStatusHistMctrStatusHistOnLoad
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatusHistory> mctrStatusHistMctrStatusHistOnLoad(IEnumerable<StatusHistory> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : mctrStatusHisthistButtonCloseWhenButtonPressed
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> mctrStatusHisthistButtonCloseWhenButtonPressed(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : mctrStatusHistPostQuery
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> mctrStatusHistPostQuery(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : selectionrgrpSortWhenRadioChanged
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> selectionrgrpSortWhenRadioChanged(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : selectionbutToXlsWhenButtonPressed
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> selectionbutToXlsWhenButtonPressed(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : webutildummyWhenButtonPressed
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> webutildummyWhenButtonPressed(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : webutilwebutilClientinfoFunctionsWhenCustomItemEvent
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> webutilwebutilClientinfoFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : webutilwebutilFileFunctionsWhenCustomItemEvent
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> webutilwebutilFileFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : webutilwebutilHostFunctionsWhenCustomItemEvent
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> webutilwebutilHostFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : webutilwebutilSessionFunctionsWhenCustomItemEvent
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> webutilwebutilSessionFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : webutilwebutilFiletransferFunctionsWhenCustomItemEvent
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> webutilwebutilFiletransferFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : webutilwebutilOleFunctionsWhenCustomItemEvent
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> webutilwebutilOleFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : webutilwebutilCApiFunctionsWhenCustomItemEvent
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> webutilwebutilCApiFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : webutilwebutilBrowserFunctionsWhenCustomItemEvent
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> webutilwebutilBrowserFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : statHistBlWhenNewFormInstance
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> statHistBlWhenNewFormInstance(IEnumerable<StatHistBl> statHistBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : statHistBlWhenWindowClosed
    ///</summary>
    ///<param name = "StatHistBl"></param>
    ///<returns>IEnumerable<StatHistBl> </returns>
    IEnumerable<StatHistBl> statHistBlWhenWindowClosed(IEnumerable<StatHistBl> statHistBl);
       
    
  }

}

