///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  

using System.Collections.Generic;
using MCTR.DomainEntity;

namespace MCTR.BusinessInterface
{

    ///*********************************************************************
    ///<summary>
    ///IMctrAttachBlBusiness is an interface for the MctrAttachBlBusiness   
    ///which facilitates the dependency injection.
    ///</summary>
    public interface IMctrAttachBlBusiness
  { 
     

    ///*************************************************************
    ///<summary>
    ///Method Name : summaryattachCloseButtonWhenButtonPressed
    ///</summary>
    ///<param name = "MctrAttachBl"></param>
    ///<returns>IEnumerable<MctrAttachBl> </returns>
    IEnumerable<MctrAttachBl> summaryattachCloseButtonWhenButtonPressed(IEnumerable<MctrAttachBl> mctrAttachBl);

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrAttachBlInsert
        ///</summary>
        ///<param name = "MctrAttachBl"></param>
        ///<returns>IEnumerable<MctrAttachBl> </returns>
        IEnumerable<MctrAttachBl> mctrAttachBlInsert(IEnumerable<MctrAttachBl> mctrAttachBl);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrAttachMctrAttachOnLoad
        ///</summary>
        ///<param name = "MctrAttachBl"></param>
        ///<returns>IEnumerable<MctrAttachBl> </returns>
        IEnumerable<MctrAttachBl> mctrAttachMctrAttachOnLoad(IEnumerable<MctrAttachBl> mctrAttachBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : mctrAttachattachDescrOnError
    ///</summary>
    ///<param name = "MctrAttachBl"></param>
    ///<returns>IEnumerable<MctrAttachBl> </returns>
    IEnumerable<MctrAttachBl> mctrAttachattachDescrOnError(IEnumerable<MctrAttachBl> mctrAttachBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : mctrAttachattachInsertFileWhenButtonPressed
    ///</summary>
    ///<param name = "MctrAttachBl"></param>
    ///<returns>IEnumerable<MctrAttachBl> </returns>
    IEnumerable<MctrAttachBl> mctrAttachattachInsertFileWhenButtonPressed(IEnumerable<MctrAttachBl> mctrAttachBl);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrAttachattachViewFileWhenButtonPressed
        ///</summary>
        ///<param name = "MctrAttachBl"></param>
        ///<returns>IEnumerable<MctrAttachBl> </returns>
        IEnumerable<MctrAttachBl> mctrAttachattachViewFileWhenButtonPressed(IEnumerable<MctrAttachBl> mctrAttachBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : mctrAttachPreInsert
    ///</summary>
    ///<param name = "MctrAttachBl"></param>
    ///<returns>IEnumerable<MctrAttachBl> </returns>
    IEnumerable<MctrAttachBl> mctrAttachPreInsert(IEnumerable<MctrAttachBl> mctrAttachBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : webutildummyWhenButtonPressed
    ///</summary>
    ///<param name = "MctrAttachBl"></param>
    ///<returns>IEnumerable<MctrAttachBl> </returns>
    IEnumerable<MctrAttachBl> webutildummyWhenButtonPressed(IEnumerable<MctrAttachBl> mctrAttachBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : mctrAttachBlWhenNewFormInstance
    ///</summary>
    ///<param name = "MctrAttachBl"></param>
    ///<returns>IEnumerable<MctrAttachBl> </returns>
    IEnumerable<MctrAttachBl> mctrAttachBlWhenNewFormInstance(IEnumerable<MctrAttachBl> mctrAttachBl);
       
    
  }

}

