///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  

using System.Collections.Generic;
using MCTR.DomainEntity;

namespace MCTR.BusinessInterface
{

    ///*********************************************************************
    ///<summary>
    ///IMctrIncrRatesBusiness is an interface for the MctrIncrRatesBusiness   
    ///which facilitates the dependency injection.
    ///</summary>
    public interface IMctrIncrRatesBusiness
    { 


        ///*************************************************************
        ///<summary>
        ///Method Name : selectionbutRatesListWhenButtonPressed
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> selectionbutRatesListWhenButtonPressed(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrIncrRatesMctrIncrRatesOnLoad
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> mctrIncrRatesMctrIncrRatesOnLoad(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrIncrRatescmponCdPostTextItem
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> mctrIncrRatescmponCdPostTextItem(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrIncrRatescascadeFlgWhenMouseClick
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> mctrIncrRatescascadeFlgWhenMouseClick(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrIncrRatesPreUpdate
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> mctrIncrRatesPreUpdate(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrIncrRatesPostQuery
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> mctrIncrRatesPostQuery(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : webutildummyWhenButtonPressed
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> webutildummyWhenButtonPressed(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : webutilwebutilClientinfoFunctionsWhenCustomItemEvent
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> webutilwebutilClientinfoFunctionsWhenCustomItemEvent(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : webutilwebutilFileFunctionsWhenCustomItemEvent
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> webutilwebutilFileFunctionsWhenCustomItemEvent(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : webutilwebutilHostFunctionsWhenCustomItemEvent
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> webutilwebutilHostFunctionsWhenCustomItemEvent(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : webutilwebutilSessionFunctionsWhenCustomItemEvent
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> webutilwebutilSessionFunctionsWhenCustomItemEvent(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : webutilwebutilFiletransferFunctionsWhenCustomItemEvent
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> webutilwebutilFiletransferFunctionsWhenCustomItemEvent(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : webutilwebutilOleFunctionsWhenCustomItemEvent
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> webutilwebutilOleFunctionsWhenCustomItemEvent(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : webutilwebutilCApiFunctionsWhenCustomItemEvent
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> webutilwebutilCApiFunctionsWhenCustomItemEvent(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : webutilwebutilBrowserFunctionsWhenCustomItemEvent
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> webutilwebutilBrowserFunctionsWhenCustomItemEvent(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrIncrRatesWhenNewFormInstance
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> mctrIncrRatesWhenNewFormInstance();


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrIncrRatesOnError
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> mctrIncrRatesOnError(IEnumerable<MctrIncrRates> mctrIncrRates);


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrIncrRatesWhenWindowClosed
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> mctrIncrRatesWhenWindowClosed(IEnumerable<MctrIncrRates> mctrIncrRates);



        ///*************************************************************
        ///<summary>
        ///Method Name : CreateIncrRates
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> Create(IEnumerable<MctrIncrRates> mctrIncrRates);

        ///*************************************************************
        ///<summary>
        ///Method Name : DeleteIncrRates
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<MctrIncrRates> DeleteStatus(IEnumerable<MctrIncrRates> mctrIncrRates);

        ///*************************************************************
        ///<summary>
        ///Method Name : EditIncrRates
        ///</summary>
        ///<param name = "MctrIncrRates"></param>
        ///<returns>IEnumerable<MctrIncrRates> </returns>
        IEnumerable<IncrRateEdit> EditStatus(IEnumerable<IncrRateEdit> mctrIncrRates);


    }

}

