///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  

using System.Collections.Generic;
using MCTR.DomainEntity;

namespace MCTR.BusinessInterface
{

    ///*********************************************************************
    ///<summary>
    ///IMctrJrnlByDateRptBlBusiness is an interface for the MctrJrnlByDateRptBlBusiness   
    ///which facilitates the dependency injection.
    ///</summary>
    public interface IMctrJrnlByDateRptBlBusiness
  { 
     

    ///*************************************************************
    ///<summary>
    ///Method Name : selectionbutRptWhenButtonPressed
    ///</summary>
    ///<param name = "MctrJrnlByDateRptBl"></param>
    ///<returns>IEnumerable<MctrJrnlByDateRptBl> </returns>
    IEnumerable<MctrJrnlByDate> selectionbutRptWhenButtonPressed(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : selectionbutExcelWhenButtonPressed
    ///</summary>
    ///<param name = "MctrJrnlByDateRptBl"></param>
    ///<returns>IEnumerable<MctrJrnlByDateRptBl> </returns>
    IEnumerable<MctrJrnlByDate> selectionbutExcelWhenButtonPressed(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl);
       


    ///*************************************************************
    ///<summary>
    ///Method Name : getRgBuLOV()
    ///</summary>
    ///<param name = "MctrJrnlByDateRptBl"></param>
    ///<returns>IEnumerable<MctrJrnlByDateRptBl> </returns>
    IEnumerable<MctrJrnlByDate> getRgBuLOV(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : getRgFinCtlLOV()
    ///</summary>
    ///<param name = "MctrJrnlByDateRptBl"></param>
    ///<returns>IEnumerable<MctrJrnlByDateRptBl> </returns>
    IEnumerable<MctrJrnlByDate> getRgFinCtlLOV(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : getRgOrigLOV()
    ///</summary>
    ///<param name = "MctrJrnlByDateRptBl"></param>
    ///<returns>IEnumerable<MctrJrnlByDateRptBl> </returns>
    IEnumerable<MctrJrnlByDate> getRgOrigLOV(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : getRgFromDateLOV()
    ///</summary>
    ///<param name = "MctrJrnlByDateRptBl"></param>
    ///<returns>IEnumerable<MctrJrnlByDateRptBl> </returns>
    IEnumerable<MctrJrnlByDate> getRgFromDateLOV(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : getRgToDateLOV()
    ///</summary>
    ///<param name = "MctrJrnlByDateRptBl"></param>
    ///<returns>IEnumerable<MctrJrnlByDateRptBl> </returns>
    IEnumerable<MctrJrnlByDate> getRgToDateLOV(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl);
       

    ///*************************************************************
    ///<summary>
    ///Method Name : mctrJrnlByDateRptBlWhenWindowClosed
    ///</summary>
    ///<param name = "MctrJrnlByDateRptBl"></param>
    ///<returns>IEnumerable<MctrJrnlByDateRptBl> </returns>
    IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBlWhenWindowClosed(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl);
       
    
  }

}

