///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  
using MCTR.DomainEntity;
using System.Collections.Generic;

namespace MCTR.BusinessInterface
{
    public interface IRoleListBusiness
    {
        ///*************************************************************
        ///<summary>
        ///Method Name : roleListOnload
        ///</summary>
        ///<param name = "roleList"></param>
        ///<returns>IEnumerable<roleList> </returns>
        IEnumerable<RoleList> roleListOnload(IEnumerable<RoleList> roleList);
        ///*************************************************************
        ///<summary>
        ///Method Name : roleListbutRoleWhenButtonPressed
        ///</summary>
        ///<param name = "roleList"></param>
        ///<returns>IEnumerable<roleList> </returns>
        IEnumerable<RoleList> roleListbutRoleWhenButtonPressed(IEnumerable<RoleList> roleList);
        ///*************************************************************
        ///<summary>
        ///Method Name : roleListbutFindWhenButtonPressed
        ///</summary>
        ///<param name = "roleList"></param>
        ///<returns>IEnumerable<roleList> </returns>
        IEnumerable<RoleList> roleListbutFindWhenButtonPressed(IEnumerable<RoleList> roleList);
        ///*************************************************************
        ///<summary>
        ///Method Name : roleListPostQuery
        ///</summary>
        ///<param name = "roleList"></param>
        ///<returns>IEnumerable<roleList> </returns>
        IEnumerable<RoleList> roleListPostQuery(IEnumerable<RoleList> roleList);
        ///*************************************************************
        ///<summary>
        ///Method Name : roleListWhenNewFormInstance
        ///</summary>
        ///<param name = "roleList"></param>
        ///<returns>IEnumerable<roleList> </returns>
        IEnumerable<RoleList> roleListWhenNewFormInstance(IEnumerable<RoleList> roleList);

    }
}

