///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  

using System.Collections.Generic;
using MCTR.DomainEntity;

namespace MCTR.BusinessInterface
///*********************************************************************
///<summary>
///ITtdCheckBlBusiness is an interface for the TtdCheckBlBusiness   
///which facilitates the dependency injection.
///</summary>
{

    public interface ITtdCheckBlBusiness
    {
        ///*************************************************************
        ///<summary>
        ///Method Name : ttdCheckTtdCheckOnLoad
        ///</summary>
        ///<param name = "TtdCheckBl"></param>
        ///<returns>IEnumerable<TtdCheckBl> </returns>
        IEnumerable<TtdCheckBl> ttdCheckTtdCheckOnLoad(IEnumerable<TtdCheckBl> ttdCheckBl);
        ///*************************************************************
        ///<summary>
        ///Method Name : ttdCheckPostQuery
        ///</summary>
        ///<param name = "TtdCheckBl"></param>
        ///<returns>IEnumerable<TtdCheckBl> </returns>
        IEnumerable<TtdCheckBl> ttdCheckPostQuery(IEnumerable<TtdCheckBl> ttdCheckBl);
        ///*************************************************************
        ///<summary>
        ///Method Name : ttdCheckBlWhenNewFormInstance
        ///</summary>
        ///<param name = "TtdCheckBl"></param>
        ///<returns>IEnumerable<TtdCheckBl> </returns>
        IEnumerable<TtdCheckBl> ttdCheckBlWhenNewFormInstance(IEnumerable<TtdCheckBl> ttdCheckBl);
        ///*************************************************************
        ///<summary>
        ///Method Name : ttdCheckBlWhenWindowClosed
        ///</summary>
        ///<param name = "TtdCheckBl"></param>
        ///<returns>IEnumerable<TtdCheckBl> </returns>
        IEnumerable<TtdCheckBl> ttdCheckBlWhenWindowClosed(IEnumerable<TtdCheckBl> ttdCheckBl);






    }

}

