
///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  


using MCTR.DomainEntity;
using MCTR.Web.Handlers;
using System;
using System.Linq;
using System.Web.Mvc;
using log4net;
using MCTR.Web.Security;

namespace MCTR.Web.Controllers
{
    ///*********************************************************************
    ///<summary>
    ///MctrJrnlByDateRptBlController is a web controller implementation for the 
    ///mctrJrnlByDateRptBl screen.
    ///</summary>
    ///
    [CustomAuthorize]
    public class MctrJrnlByDateRptBlController : Controller
    {
         private readonly ILog logger;



        public MctrJrnlByDateRptBlController()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        }


        public ActionResult MctrJrnlByDateRp() {
            return View();
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : selectionbutFromDateWhenButtonPressedOpenLOV
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult selectionbutFromDateWhenButtonPressedOpenLOV(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
        logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.selectionbutFromDateWhenButtonPressedOpenLOV(mctrJrnlByDateRptBl);
        logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
    }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
}
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : selectionbutRptWhenButtonPressed
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult selectionbutRptWhenButtonPressed(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.selectionbutRptWhenButtonPressed(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : selectionbutExcelWhenButtonPressed
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult selectionbutExcelWhenButtonPressed(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.selectionbutExcelWhenButtonPressed(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : webutildummyWhenButtonPressed
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult webutildummyWhenButtonPressed(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.webutildummyWhenButtonPressed(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }


        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : webutilwebutilClientinfoFunctionsWhenCustomItemEvent
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult webutilwebutilClientinfoFunctionsWhenCustomItemEvent(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.webutilwebutilClientinfoFunctionsWhenCustomItemEvent(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : webutilwebutilFileFunctionsWhenCustomItemEvent
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult webutilwebutilFileFunctionsWhenCustomItemEvent(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.webutilwebutilFileFunctionsWhenCustomItemEvent(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : webutilwebutilHostFunctionsWhenCustomItemEvent
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>
        public ActionResult webutilwebutilHostFunctionsWhenCustomItemEvent(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.webutilwebutilHostFunctionsWhenCustomItemEvent(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : webutilwebutilSessionFunctionsWhenCustomItemEvent
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult webutilwebutilSessionFunctionsWhenCustomItemEvent(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.webutilwebutilSessionFunctionsWhenCustomItemEvent(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : webutilwebutilFiletransferFunctionsWhenCustomItemEvent
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult webutilwebutilFiletransferFunctionsWhenCustomItemEvent(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.webutilwebutilFiletransferFunctionsWhenCustomItemEvent(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : webutilwebutilOleFunctionsWhenCustomItemEvent
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult webutilwebutilOleFunctionsWhenCustomItemEvent(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.webutilwebutilOleFunctionsWhenCustomItemEvent(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }
        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : webutilwebutilCApiFunctionsWhenCustomItemEvent
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult webutilwebutilCApiFunctionsWhenCustomItemEvent(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.webutilwebutilCApiFunctionsWhenCustomItemEvent(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }
        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : webutilwebutilBrowserFunctionsWhenCustomItemEvent
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult webutilwebutilBrowserFunctionsWhenCustomItemEvent(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.webutilwebutilBrowserFunctionsWhenCustomItemEvent(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }
        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : getRgBuLOV
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult getRgBuLOV(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.getRgBuLOV(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }

        public ActionResult getRgFinCtlLOV() {
            return PartialView();
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : getRgFinCtlLOV()
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult getRgFinCtlJson(string origBu)
        {
          try
            {
                var mctrJrnlByDateRptBl = new MctrJrnlByDate();
                mctrJrnlByDateRptBl.ORIG_BU = origBu;
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var mctrJrnlByDateResp = jrnlByDateRptBlHandler.getRgFinCtlLOV(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    var jsonData = new
                    {
                        total = 1,
                        page = 1,
                        records = mctrJrnlByDateResp.Count(),
                        rows = mctrJrnlByDateResp,
                        userdata = mctrJrnlByDateResp
                    };
                    return Json(jsonData, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return null;
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }

        public ActionResult getRgOrigLOV()
        {
            return PartialView();
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : getRgOrigJson
        //    ///</summary>
        //    ///<param name = "origBu"></param>
        //    ///<returns>IEnumerable<MctrJrnlByDate> </returns>

        public ActionResult getRgOrigJson(string origBu)
        {
            try
            {
                var mctrJrnlByDateRptBl = new MctrJrnlByDate();
                mctrJrnlByDateRptBl.ORIG_BU = origBu;
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var mctrJrnlByDateResp = jrnlByDateRptBlHandler.getRgOrigLOV(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    var jsonData = new
                    {
                        total = 1,
                        page = 1,
                        records = mctrJrnlByDateResp.Count(),
                        rows = mctrJrnlByDateResp,
                        userdata = mctrJrnlByDateResp
                    };
                    return Json(jsonData, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return null;
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }

        public ActionResult getRgFromDateLOV()
        {
            return PartialView();
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : getRgFromDateJson
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>
        [HttpPost]
        public ActionResult getRgFromDateJson(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var mctrJrnlByDateResp = jrnlByDateRptBlHandler.getRgFromDateLOV(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    var jsonData = new
                    {
                        total = 1,
                        page = 1,
                        records = mctrJrnlByDateResp.Count(),
                        rows = mctrJrnlByDateResp,
                        userdata = mctrJrnlByDateResp
                    };
                    return Json(jsonData, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return null;
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }

        public ActionResult getRgToDateLOV()
        {
            return PartialView();
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : getRgToDateJSON
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>
        [HttpPost]
        public ActionResult getRgToDateJSON(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                mctrJrnlByDateRptBl.DATE_JOURNAL = DateTime.Parse(mctrJrnlByDateRptBl.date);
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var mctrJrnlByDateResp = jrnlByDateRptBlHandler.getRgToDateLOV(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    var jsonData = new
                    {
                        total = 1,
                        page = 1,
                        records = mctrJrnlByDateResp.Count(),
                        rows = mctrJrnlByDateResp,
                        userdata = mctrJrnlByDateResp
                    };
                    return Json(jsonData, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return null;
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }

        //    ///*************************************************************
        //    ///<summary>
        //    ///Method Name : mctrJrnlByDateRptBlWhenWindowClosed
        //    ///</summary>
        //    ///<param name = "mctrJrnlByDateRptBl"></param>
        //    ///<returns>IEnumerable<mctrJrnlByDateRptBl> </returns>

        public ActionResult mctrJrnlByDateRptBlWhenWindowClosed(MctrJrnlByDate mctrJrnlByDateRptBl)
        {
            try
            {
                if (mctrJrnlByDateRptBl != null)
                {
                    logger.Info("Executing  MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()  " + mctrJrnlByDateRptBl);
                    MctrJrnlByDateRptBlHandler jrnlByDateRptBlHandler = new MctrJrnlByDateRptBlHandler();
                    logger.Debug("Executing MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()");
                    var MctrJrnlByDateResp = jrnlByDateRptBlHandler.mctrJrnlByDateRptBlWhenWindowClosed(mctrJrnlByDateRptBl);
                    logger.Info("Response Received from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                    return View("mctrJrnlByDateRptBl", MctrJrnlByDateResp);
                }
                else
                {
                    logger.Info("Request object is null or doesn't contain any value.");
                    return View();
                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Controllers.TtdStatusBlController.lineItemLineItemOnLoad()" + e.Message);
                throw;
            }
        }
    } 
}
