///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  
using System.Collections.Generic;
using System.Linq;
using System.Data;
using log4net;
using Oracle.ManagedDataAccess.Client;
using MCTR.DataEntity;
using MCTR.DomainEntity;
using MCTR.DataAccessInterface;

namespace MCTR.DataAccess
{
    public class CreateMctrLovRepository : BaseRepository, ICreateMctrLovRepository
    {
         private readonly ILog logger;
        readonly List<CreateMctrLov> list = new List<CreateMctrLov>();
        public CreateMctrLovRepository()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }

        public IEnumerable<CreateMctrLov> getRgYearLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov obj = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[7];
            string sqlstmt = @" select fiscal_year from (select distinct fiscal_year from mctr_incr_rates
where cmpon_cd = :0 and exists(select business_unit from mctr_bu_profile
where business_unit = :1 and man_rated_flg = 'N' )  union select distinct fiscal_year from mctr_incr_rates
where fiscal_year > 2007   and exists (select business_unit from mctr_bu_profile
where business_unit = :2 and man_rated_flg = 'Y')  union select distinct fiscal_year from mctr_mth_cal_mv
where setid = 'MDC'  and calendar_id = '01'  and begin_dt <= trunc(sysdate)  and end_dt >= trunc(sysdate)  and
exists (select business_unit from mctr_bu_profile  where business_unit = :3 and pyr_only_flg = 'N')) 
where :4 is null or ( :5 is not null and :6 <> fiscal_year) order by 1 desc";

            parameters[0] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, obj.Orig_Bu, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, obj.Orig_Bu, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, obj.Orig_Bu, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, obj.Orig_Bu, ParameterDirection.Input);
            parameters[4] = new OracleParameter(":fiscal_year", OracleDbType.Int32, obj.fiscal_year, ParameterDirection.Input);
            parameters[5] = new OracleParameter(":fiscal_year", OracleDbType.Int32, obj.fiscal_year, ParameterDirection.Input);
            parameters[6] = new OracleParameter(":fiscal_year", OracleDbType.Int32, obj.fiscal_year, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<CreateMctrLov>(sqlstmt, parameters).ToList();
            return response;
        }

        public IEnumerable<CreateMctrLov> getRgReasonLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[1];
            string sqlstmt = "select a.reason_code, a.reason_descr from mctr_reason_code a where exists (select op_segment_7 from MCTR_PS_BUS_UNIT_TBL7_MV where business_unit = :0 and op_segment_7 = a.op_segment_7 and a.reason_code not in ('BLT','CNA','FF','WAC','WAP')) order by a.reason_code";
            parameters[0] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, recievedValues.Orig_Bu, ParameterDirection.Input);
            var response = entities.Database.SqlQuery<ReasonCode>(sqlstmt, parameters).ToList();
            recievedValues.ReasonCodes = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgApplLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[1];
            string sqlstmt = "select a.appl_jrnl_id, a.descr  from   mctr_appl_id_v a  where a.eff_status = 'A' and a.effdt = (select max(a_ed.effdt) from mctr_appl_id_v a_ed where a.appl_jrnl_id = a_ed.appl_jrnl_id and a_ed.effdt <= sysdate) and ((:0 = 'CY' and a.appl_jrnl_id <> 'PYR') or(:0 = 'PY' and a.appl_jrnl_id <> 'LBR' and a.appl_jrnl_id <> 'MTL')) order by a.appl_jrnl_id";

            parameters[0] = new OracleParameter(":py_cy_status", OracleDbType.Varchar2, recievedValues.py_cy_status, ParameterDirection.Input);


            var response = entities.Database.SqlQuery<MctrApplIdV>(sqlstmt, parameters).ToList();
            recievedValues.MctrApplIdV = response;

            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgSuperLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[3];
            string sqlstmt = "select e.last_name,e.first_name,r.bems,e.component,e.acctg_loc_cdm,e.deptno,e.mail_code,e.work_phone,null nv_cd,null nv_date from mctr_role r, mctr_employee_v e  where r.bems = e.bems_id(+) and r.active = 'Y'  and exists (select lu.business_unit from mctr_role_bu lu  where lu.bems = r.bems and (lu.business_unit = :orig_bu or (lu.group_cd7 = :orig_group and lu.business_unit = '**'))) union select  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ', null, null from mctr_role r2 where r2.bems = :globalsession_bems order by last_name, first_name";

            //Need to check session bems

            parameters[0] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, recievedValues.Orig_Bu, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":orig_group", OracleDbType.Varchar2, recievedValues.orig_group, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalsession_bems", OracleDbType.Varchar2, recievedValues.bems, ParameterDirection.Input);
            var response = entities.Database.SqlQuery<getRgSuper>(sqlstmt, parameters).ToList();
            recievedValues.getRgSuper = response;
            return createMctrLov;

        }

        public IEnumerable<CreateMctrLov> getRgApprSuperLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {

            string sqlstmt = "select 'Y' code,'YES' approve from dual union select 'N' code,'NO' approve from dual union select '' code, 'NOT YET' approve from dual";


            var response = entities.Database.SqlQuery<CreateMctrLov>(sqlstmt).ToList();



            return response;
        }

        public IEnumerable<CreateMctrLov> getRgFinCtlLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[3];
            string sqlstmt = "select  e.last_name,  e.first_name,  r.bems,  e.component,  e.acctg_loc_cdm,   e.deptno,  e.mail_code,  e.work_phone, null nv_cd, null nv_date from mctr_employee_v e, mctr_role r  where  r.bems = e.bems_id(+) and  r.fin_control_role = 'Y' and r.active = 'Y'  and exists (select lu.business_unit from mctr_role_bu lu  where lu.bems = r.bems and (lu.business_unit = :orig_bu or (lu.group_cd7 = :orig_group and lu.business_unit = '**'))) union select  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ', null, null from mctr_role r2 where r2.bems = :globalsession_bems order by last_name, first_name";

            parameters[0] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, recievedValues.Orig_Bu, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":orig_group", OracleDbType.Varchar2, recievedValues.orig_group, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalsession_bems", OracleDbType.Varchar2, recievedValues.bems, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<getRgSuper>(sqlstmt, parameters).ToList();
            recievedValues.getRgSuper = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgApprFinCtlLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            string sqlstmt = "select 'Y' code,'YES' approve from dual union select 'N' code,'NO' approve from dual union select '' code, 'NOT YET' approve from dual";
            var response = entities.Database.SqlQuery<CreateMctrLov>(sqlstmt).ToList();
            return response;
        }

        public IEnumerable<CreateMctrLov> getRgAcctLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[4];
            string sqlstmt = "select  e.last_name, e.first_name,  r.bems, e.component, e.acctg_loc_cdm,  e.deptno, e.mail_code, e.work_phone, null nv_cd, null nv_date from mctr_employee_v e, mctr_role r  where e.bems_id = r.bems and  r.accountant_role = 'Y' and r.active = 'Y' and :status_id = 'AA'  and exists (select lu.business_unit from mctr_role_bu lu  where lu.bems = r.bems and       (lu.business_unit = :orig_bu or        (lu.group_cd7 = :orig_group and lu.business_unit = '**'))) union select  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ', null, null from mctr_role r2 where r2.bems = :globalsession_bems and :status_id = 'AA' order by last_name, first_name";
            parameters[0] = new OracleParameter(":status_id", OracleDbType.Varchar2, recievedValues.status_id, ParameterDirection.Input);

            parameters[1] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, recievedValues.Orig_Bu, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":orig_group", OracleDbType.Varchar2, recievedValues.orig_group, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":globalsession_bems", OracleDbType.Varchar2, recievedValues.bems, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<getRgSuper>(sqlstmt, parameters).ToList();
            recievedValues.getRgSuper = response;
            return createMctrLov;

        }

        public IEnumerable<CreateMctrLov> getRgApprAcctLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            string sqlstmt = "select 'Y' code,'YES' approve from dual union select 'N' code,'NO' approve from dual union select '' code, 'NOT YET' approve from dual";
            var response = entities.Database.SqlQuery<CreateMctrLov>(sqlstmt).ToList();
            return response;
        }

        public IEnumerable<CreateMctrLov> getRgLbrAcctLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[4];
            string sqlstmt = " select e.last_name, e.first_name,  r.bems, e.component, e.acctg_loc_cdm, e.deptno, e.mail_code, e.work_phone, null nv_cd, null nv_date from mctr_employee_v e, mctr_role r  where e.bems_id = r.bems and r.lbr_acct_role = 'Y' and r.active = 'Y'  and exists (select lu.business_unit from mctr_role_bu lu  where lu.bems = r.bems and       (lu.business_unit = :orig_bu or        (lu.group_cd7 = :orig_group and lu.business_unit = '**'))) union select  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ', null, null from mctr_role r2 where r2.bems = :globalsession_bems and :status_id not in ('LM','LB') order by last_name, first_name";

            parameters[0] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, recievedValues.Orig_Bu, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":orig_group", OracleDbType.Varchar2, recievedValues.orig_group, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalsession_bems", OracleDbType.Varchar2, recievedValues.bems, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":status_id", OracleDbType.Varchar2, recievedValues.status_id, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<getRgSuper>(sqlstmt, parameters).ToList();
            recievedValues.getRgSuper = response;
            return createMctrLov;
        }


        public IEnumerable<CreateMctrLov> getRgApprLbrAcctLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            string sqlstmt = "select 'Y' code,'YES' approve from dual union select 'N' code,'NO' approve from dual union select '' code, 'NOT YET' approve from dual";
            var response = entities.Database.SqlQuery<CreateMctrLov>(sqlstmt).ToList();
            return response;
        }

        public IEnumerable<CreateMctrLov> getRgMatlAcctLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[4];
            string sqlstmt = " select e.last_name, e.first_name, r.bems, e.component, e.acctg_loc_cdm, e.deptno, e.mail_code, e.work_phone, null nv_cd, null nv_date from mctr_employee_v e, mctr_role r  where e.bems_id = r.bems and r.matl_acct_role = 'Y' and r.active = 'Y'  and exists (select lu.business_unit from mctr_role_bu lu  where lu.bems = r.bems and       (lu.business_unit = :orig_bu or        (lu.group_cd7 = :orig_group and lu.business_unit = '**'))) union select  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ', null, null from mctr_role r2 where r2.bems = :globalsession_bems and :status_id not in ('LM', 'MA') order by last_name, first_name";

            parameters[0] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, recievedValues.Orig_Bu, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":orig_group", OracleDbType.Varchar2, recievedValues.orig_group, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalsession_bems", OracleDbType.Varchar2, recievedValues.bems, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":status_id", OracleDbType.Varchar2, recievedValues.status_id, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<getRgSuper>(sqlstmt, parameters).ToList();
            recievedValues.getRgSuper = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgApprMatlAcctLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            string sqlstmt = "select 'Y' code,'YES' approve from dual union select 'N' code,'NO' approve from dual union select '' code, 'NOT YET' approve from dual";
            var response = entities.Database.SqlQuery<CreateMctrLov>(sqlstmt).ToList();

            return response;
        }

        public IEnumerable<CreateMctrLov> getRgCostAcctLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[4];
            string sqlstmt = " select  e.last_name,  e.first_name,   r.bems,  e.component,  e.acctg_loc_cdm,   e.deptno,  e.mail_code,  e.work_phone, null nv_cd, null nv_date from mctr_employee_v e, mctr_role r  where e.bems_id = r.bems and r.cost_acct_role = 'Y' and r.active = 'Y'  and exists (select lu.business_unit from mctr_role_bu lu  where lu.bems = r.bems and       (lu.business_unit = :orig_bu or        (lu.group_cd7 = :orig_group and lu.business_unit = '**'))) union select  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ', null, null from mctr_role r2 where r2.bems = :globalsession_bems and :status_id = 'AA' order by last_name, first_name";


            parameters[0] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, recievedValues.Orig_Bu, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":orig_group", OracleDbType.Varchar2, recievedValues.orig_group, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalsession_bems", OracleDbType.Varchar2, recievedValues.bems, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":status_id", OracleDbType.Varchar2, recievedValues.status_id, ParameterDirection.Input);


            var response = entities.Database.SqlQuery<getRgSuper>(sqlstmt, parameters).ToList();
            recievedValues.getRgSuper = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgApprCostAcctLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            string sqlstmt = "select 'Y' code,'YES' approve from dual union select 'N' code,'NO' approve from dual union select '' code, 'NOT YET' approve from dual";
            var response = entities.Database.SqlQuery<CreateMctrLov>(sqlstmt).ToList();

            return response;
        }

        public IEnumerable<CreateMctrLov> getRgSrAcctLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[4];
            string sqlstmt = "select e.last_name, e.first_name, r.bems, e.component, e.acctg_loc_cdm,  e.deptno, e.mail_code, e.work_phone,  null nv_cd,  null nv_date  from mctr_employee_v e, mctr_role r  where e.bems_id = r.bems and r.sr_acct_role = 'Y' and r.active = 'Y'  and exists (select lu.business_unit from mctr_role_bu lu  where lu.bems = r.bems and       (lu.business_unit = :orig_bu or        (lu.group_cd7 = :orig_group and lu.business_unit = '**'))) union select  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ', null, null from mctr_role r2 where r2.bems = :globalsession_bems  and :status_id <> 'SR' order by last_name, first_name";

            parameters[0] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, recievedValues.Orig_Bu, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":orig_group", OracleDbType.Varchar2, recievedValues.orig_group, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalsession_bems", OracleDbType.Varchar2, recievedValues.bems, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":status_id", OracleDbType.Varchar2, recievedValues.status_id, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<getRgSuper>(sqlstmt, parameters).ToList();
            recievedValues.getRgSuper = response;
            return createMctrLov;


        }

        public IEnumerable<CreateMctrLov> getRgApprSrAcctLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            string sqlstmt = "select 'Y' code,'YES' approve from dual union select 'N' code,'NO' approve from dual union select '' code, 'NOT YET' approve from dual";
            var response = entities.Database.SqlQuery<CreateMctrLov>(sqlstmt).ToList();

            return response;
        }

        public IEnumerable<CreateMctrLov> getRgLiBemsLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[3];
            string sqlstmt = "select e.last_name, e.first_name, e.bems_id, e.component, e.acctg_loc_cdm,   e.deptno, e.mail_code, e.work_phone  from mctr_employee_v e, mctr_role r  where e.bems_id = r.bems and r.active = 'Y'  and exists (select lu.business_unit from mctr_role_bu lu  where lu.bems = r.bems and    (lu.business_unit = :orig_bu or        (lu.group_cd7 = :orig_group and lu.business_unit = '**'))) union select  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ',  ' ' from mctr_role r2 where r2.bems = :globalsession_bems order by last_name, first_name";

            parameters[0] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, recievedValues.Orig_Bu, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":orig_group", OracleDbType.Varchar2, recievedValues.orig_group, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalsession_bems", OracleDbType.Varchar2, recievedValues.bems, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<getRgSuper>(sqlstmt, parameters).ToList();
            recievedValues.getRgSuper = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgRejectLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            string sqlstmt = "select h.reject_code, h.reject_reason from mctr_reject_code h order by h.reject_code";
            var response = entities.Database.SqlQuery<CreateMctrLov>(sqlstmt).ToList();

            return response;
        }

        public IEnumerable<CreateMctrLov> getRgProjFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[14];
            string sqlstmt = @"select distinct a.activity_id, p.business_unit_gl, a.project_id, p.account, p2.contract_num, p.bus_unit_mgmt_cd7, p.customer_type_cd7,
                                    a.effdt ACC_EFF_DT, p.effdt proj_eff_dt, a2.eff_status activity_status, p2.eff_status project_status, a.direct_chrg_flg7 
                                    from  mctr_activity_v a,  mctr_project_v p,  mctr_activity_v a2,  mctr_project_v p2 where ((:0 = 'CY' and  
                                    a.activity_id = :1 and  a.effdt = (select max(a_ed.effdt) from mctr_activity_v a_ed  where a.activity_id = a_ed.activity_id 
                                    and a.project_id = a_ed.project_id and a_ed.effdt <= :2  and (a_ed.eff_status = 'A' or (a_ed.eff_status = 'I' 
                                    and a_ed.direct_chrg_flg7 = 'Y'))) and a.setid = p.setid and a.project_id = p.project_id and p.effdt = (select max(p_ed.effdt) 
                                    from mctr_project_v p_ed where p.project_id = p_ed.project_id and p_ed.effdt <= :3)) or (:4 = 'PY' and  
                                    a.activity_id = :5 and a.effdt = (select max(a_ed.effdt) from mctr_activity_v a_ed where a.activity_id = a_ed.activity_id 
                                    and a.project_id = a_ed.project_id and a_ed.effdt <= :6 and a_ed.eff_status = 'A') and a.setid = p.setid 
                                    and a.project_id = p.project_id and p.effdt = (select max(p_ed.effdt) from mctr_project_v p_ed where p.project_id = p_ed.project_id 
                                    and p_ed.effdt <= :7 and p_ed.eff_status = 'A')) or (:8 = 'PY' and  a.activity_id = :9 
                                    and a.effdt = (select max(a_ed.effdt) from mctr_activity_v a_ed where a.activity_id = a_ed.activity_id and a.project_id = a_ed.project_id 
                                    and a_ed.effdt <= :10 and a_ed.eff_status = 'A') and a.setid = p.setid and a.project_id = p.project_id 
                                    and p.effdt = (select max(p_ed.effdt) from mctr_project_v p_ed where p.project_id = p_ed.project_id and p_ed.effdt <= :11 
                                    and p_ed.eff_status = 'A'))) and a.activity_id = a2.activity_id and a.project_id = a2.project_id and a2.effdt = (select max(a2_ed.effdt) 
                                    from mctr_activity_v a2_ed where a2.activity_id = a2_ed.activity_id and a2.project_id = a2_ed.project_id and  a2_ed.effdt <= :12) 
                                    and a2.setid = p2.setid and a2.project_id = p2.project_id and p2.effdt = (select max(p2_ed.effdt) from mctr_project_v p2_ed  
                                    where p2.project_id = p2_ed.project_id and  p2_ed.effdt <= :13) order by a2.eff_status, a.effdt desc, p2.eff_status,  p.effdt desc,  
                                    a.project_id";
            
            string cowdate =string.Format("{0:dd-MMM-yyyy}",recievedValues.cow);
            
            string periodto = string.Format("{0:dd-MMM-yyyy}", recievedValues.period_to);

            parameters[0] = new OracleParameter(":py_cy_status", OracleDbType.Varchar2, recievedValues.py_cy_status, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":activity_id_from", OracleDbType.Varchar2, recievedValues.activity_id_from, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[4] = new OracleParameter(":py_cy_status", OracleDbType.Varchar2, recievedValues.py_cy_status, ParameterDirection.Input);
            parameters[5] = new OracleParameter(":activity_id_from", OracleDbType.Varchar2, recievedValues.activity_id_from, ParameterDirection.Input);
            parameters[6] = new OracleParameter(":cow", OracleDbType.Varchar2, cowdate, ParameterDirection.Input);
            parameters[7] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[8] = new OracleParameter(":py_cy_status", OracleDbType.Varchar2, recievedValues.py_cy_status, ParameterDirection.Input);
            parameters[9] = new OracleParameter(":activity_id_from", OracleDbType.Varchar2, recievedValues.activity_id_from, ParameterDirection.Input);
            parameters[10] = new OracleParameter(":cow", OracleDbType.Varchar2, cowdate, ParameterDirection.Input);
            parameters[11] = new OracleParameter(":cow", OracleDbType.Varchar2, cowdate, ParameterDirection.Input);
            parameters[12] = new OracleParameter(":cow", OracleDbType.Varchar2, cowdate, ParameterDirection.Input);
            parameters[13] = new OracleParameter(":cow", OracleDbType.Varchar2, cowdate, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<getRgProj>(sqlstmt, parameters).ToList();

            foreach (var obj in response)
            {
                obj.WORK_BUGL_FROM = obj.BUSINESS_UNIT_GL;
                obj.ACCOUNT_FROM = obj.ACCOUNT;
                obj.ACTIVITY_ID_FROM = obj.ACCOUNT;
                obj.PROJECT_ID_FROM = obj.PROJECT_ID;
                obj.BUM_CD7_FROM = obj.BUS_UNIT_MGMT_CD7;
                obj.CUST_TYPE_CD7_FROM = obj.CUSTOMER_TYPE_CD7;
                obj.CONTRACT_NUM_FROM = obj.CONTRACT_NUM;
            }

            recievedValues.getRgProj = response;
            return createMctrLov;
        }


        public IEnumerable<CreateMctrLov> getRgProjFromPromptLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[12];
            string sqlstmt = @"select distinct a.activity_id, p.business_unit_gl, a.project_id, p.account, p2.contract_num, p.bus_unit_mgmt_cd7, p.customer_type_cd7, 
a.effdt as ACC_EFF_DT, a2.eff_status activity_status, p2.eff_status project_status from  mctr_activity_v a,  mctr_project_v p,  mctr_activity_v a2,  
mctr_project_v p2 where ((:0 = 'CY' and a.activity_id = :1 and a.project_id like :2 
and a.eff_status = 'A' and a.effdt = (select max(a_ed.effdt) from mctr_activity_v a_ed where a.activity_id = a_ed.activity_id 
and a.project_id = a_ed.project_id and a_ed.effdt <= :3  and (a_ed.eff_status = 'A' or (a_ed.eff_status = 'I' 
and a_ed.direct_chrg_flg7 = 'Y'))) and a.setid = p.setid and a.project_id = p.project_id and p.effdt = (select max(p_ed.effdt) 
from mctr_project_v p_ed where p.project_id = p_ed.project_id and p.account = p_ed.account and p_ed.effdt <= :4)) 
or(:5 = 'PY' and a.activity_id = :6 and a.project_id like :7 
and a.effdt = (select max(a_ed.effdt) from mctr_activity_v a_ed where a.activity_id = a_ed.activity_id and a.project_id = a_ed.project_id 
and a_ed.effdt <= :8 and a_ed.eff_status = 'A') and a.setid = p.setid and a.project_id = p.project_id 
and p.effdt = (select max(p_ed.effdt) from mctr_project_v p_ed where p.project_id = p_ed.project_id and p.account = p_ed.account 
and p_ed.effdt <= :9 and p_ed.eff_status = 'A'))) and a.activity_id = a2.activity_id and a.project_id = a2.project_id and
a2.effdt = (select max(a2_ed.effdt) from mctr_activity_v a2_ed where a2.activity_id = a2_ed.activity_id and a2.project_id = a2_ed.project_id 
and a2_ed.effdt <= :10) and a2.setid = p2.setid and a2.project_id = p2.project_id and p2.project_id = p.project_id 
and p2.account = p.account and p2.effdt = (select max(p2_ed.effdt) from mctr_project_v p2_ed where p2.project_id = p2_ed.project_id and
p2.account = p2_ed.account and p2_ed.effdt <= :11) order by a2.eff_status, a.effdt desc,  p2.eff_status, a.project_id, p.account";

            string periodto = string.Format("{0:dd-MMM-yyyy}", recievedValues.period_to);

            parameters[0] = new OracleParameter(":globalpy_cy_status", OracleDbType.Varchar2, recievedValues.py_cy_status, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":activity_id_from", OracleDbType.Varchar2, recievedValues.activity_id_from, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":project_from_prompt", OracleDbType.Varchar2, recievedValues.project_from_prompt, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[4] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[5] = new OracleParameter(":globalpy_cy_status", OracleDbType.Varchar2, recievedValues.py_cy_status, ParameterDirection.Input);
            parameters[6] = new OracleParameter(":activity_id_from", OracleDbType.Varchar2, recievedValues.activity_id_from, ParameterDirection.Input);
            parameters[7] = new OracleParameter(":project_from_prompt", OracleDbType.Varchar2, recievedValues.project_from_prompt, ParameterDirection.Input);
            parameters[8] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[9] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[10] = new OracleParameter(":globalcow", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[11] = new OracleParameter(":globalcow", OracleDbType.Varchar2, periodto, ParameterDirection.Input);


            var response = entities.Database.SqlQuery<getRgProj>(sqlstmt, parameters).ToList();
            recievedValues.getRgProj = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgTransFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[1];
            string sqlstmt = "select proj_trans_type, proj_trans_code,statistics_code,unit_of_measure,decode(proj_trans_code,'STR',1,'OTS',2,'PRM',3,'OTH',4,5) trans_order from mctr_trans_type where cmpon_cd = :orig_bu order by trans_order, proj_trans_type, proj_trans_code";

            parameters[0] = new OracleParameter(":orig_bu", OracleDbType.Varchar2, recievedValues.Orig_Bu, ParameterDirection.Input);


            var response = entities.Database.SqlQuery<TransType>(sqlstmt, parameters).ToList();
            recievedValues.transtype = response;
            return createMctrLov;
        }


        public IEnumerable<CreateMctrLov> getRgHomeDeptFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();

            OracleParameter[] parameters = new OracleParameter[4];
            string sqlstmt = @"select  a.deptid, a.setid, a.acctg_loc_cd7, a.allow_pool_cd7,a.labor_rate_cd7,decode( a.resource_sub_cat,'095','B','A') class_cd,  
a.resource_sub_cat, a2.effdt, a2.eff_status from  mctr_locn_dept_mv a,  mctr_locn_dept_mv a2 where  
a.setid = :0 and  a.deptid = :1 and  a.effdt =(select max(a_ed.effdt) from mctr_locn_dept_mv a_ed 
where a.setid = a_ed.setid and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 and a.deptid = a_ed.deptid and a_ed.effdt <= :2) 
and  a.setid = a2.setid and  a.deptid = a2.deptid and  a.acctg_loc_cd7 = a2.acctg_loc_cd7 and  a2.effdt = (select max(a2_ed.effdt) 
from mctr_locn_dept_mv a2_ed  where a2.setid = a2_ed.setid and a2.acctg_loc_cd7 = a2_ed.acctg_loc_cd7 and a2.deptid = a2_ed.deptid and
a2_ed.effdt <= :3) order by  a2.eff_status, a2.effdt desc, a.deptid, a.setid, a.acctg_loc_cd7,  a.allow_pool_cd7,  
a.labor_rate_cd7, a.resource_sub_cat";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":home_dept_from", OracleDbType.Varchar2, recievedValues.home_dept_from, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.period_to, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":globalcow", OracleDbType.Date, recievedValues.cow, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocndeptmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocndeptmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgHomeDeptLocFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[5];
            string sqlstmt = @"select  a.deptid, a.setid, a.acctg_loc_cd7, a.allow_pool_cd7,a.labor_rate_cd7,decode( a.resource_sub_cat,'095','B','A') class_cd,  
a.resource_sub_cat, a2.effdt, a2.eff_status from  mctr_locn_dept_mv a, mctr_locn_dept_mv a2 where  a.setid = :globalsetid 
and  a.deptid = :home_dept_from and  a.acctg_loc_cd7 = :home_loc_from and  a.effdt = (select max(a_ed.effdt) from mctr_locn_dept_mv a_ed    
where a.setid = a_ed.setid and  a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 and  a.deptid = a_ed.deptid and a_ed.effdt <= :period_to) and  
a.setid = a2.setid and  a.deptid = a2.deptid and  a.acctg_loc_cd7 = a2.acctg_loc_cd7 and  a2.effdt =  (select max(a2_ed.effdt)       
from mctr_locn_dept_mv a2_ed   where a2.setid = a2_ed.setid and  a2.acctg_loc_cd7 = a2_ed.acctg_loc_cd7 and a2.deptid = a2_ed.deptid and
a2_ed.effdt <= :globalcow) order by  a2.eff_status, a2.effdt desc, a.deptid, a.setid, a.acctg_loc_cd7,  a.allow_pool_cd7, 
a.labor_rate_cd7, a.resource_sub_cat";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":home_dept_from", OracleDbType.Varchar2, recievedValues.home_dept_from, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":home_loc_from", OracleDbType.Varchar2, recievedValues.home_loc_from, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.period_to, ParameterDirection.Input);
            parameters[4] = new OracleParameter(":globalcow", OracleDbType.Date, recievedValues.cow, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocndeptmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocndeptmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgListHomeDeptFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[3];

            string sqlstmt = @"select a.deptid,a.setid,a.acctg_loc_cd7,a.allow_pool_cd7,a.labor_rate_cd7,decode( a.resource_sub_cat,'095','B','A') class_cd,
a.resource_sub_cat,a2.effdt,a2.eff_status from  mctr_locn_dept_mv a,mctr_locn_dept_mv a2 where a.setid = :setid 
and  rtrim(a.deptid) is not null and   a.effdt = (select max(a_ed.effdt) from mctr_locn_dept_mv a_ed where a.setid = a_ed.setid and
a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 and a.deptid = a_ed.deptid and a_ed.effdt <= :period_to) and  a.setid = a2.setid and  
a.deptid = a2.deptid and  a.acctg_loc_cd7 = a2.acctg_loc_cd7 and  a2.effdt = (select max(a2_ed.effdt) from mctr_locn_dept_mv a2_ed 
where a2.setid = a2_ed.setid and a2.acctg_loc_cd7 = a2_ed.acctg_loc_cd7 and a2.deptid = a2_ed.deptid and a2_ed.effdt <= :globalcow)  
order by a.deptid, a.acctg_loc_cd7, a.setid, a.allow_pool_cd7,a.labor_rate_cd7, a.resource_sub_cat,a2.eff_status, a2.effdt desc";

            parameters[0] = new OracleParameter(":setid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.period_to, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalcow", OracleDbType.Date, recievedValues.cow, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocndeptmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocndeptmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgHomeLocFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();

            OracleParameter[] parameters = new OracleParameter[2];
            string sqlstmt = "select distinct a.acctg_loc_cd7,a.setid from mctr_locn_mv a where  a.setid = :globalsetid and a.acctg_loc_cd7 = :home_loc_from  order by a.acctg_loc_cd7, a.setid";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":home_loc_from", OracleDbType.Varchar2, recievedValues.home_loc_from, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocnmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocnmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgListHomeLocFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();

            OracleParameter[] parameters = new OracleParameter[2];
            string sqlstmt = "select distinct a.acctg_loc_cd7, a.setid  from mctr_locn_mv a where a.setid = :globalsetid and a.eff_status = 'A' and a.effdt = (select max(a_ed.effdt) from mctr_locn_mv a_ed  where a.setid = a_ed.setid and  a.acctg_loc_cd7 =  a_ed.acctg_loc_cd7 and a_ed.effdt <= :period_to)  order by a.acctg_loc_cd7, a.setid";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.EFFDT, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocnmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocnmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgClassCodeFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();

            OracleParameter[] parameters = new OracleParameter[3];
            string sqlstmt = "select distinct class_cd7, proj_trans_type, setid, descr, resource_sub_cat, effdt, eff_status from mctr_class_code_v  where class_cd7 = :class_cd_from and proj_trans_type = :proj_trans_type_from  and setid = :globalsetid";

            parameters[0] = new OracleParameter(":class_cd_from", OracleDbType.Varchar2, recievedValues.class_cd_from, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":proj_trans_type_from", OracleDbType.Varchar2, recievedValues.proj_trans_type_from, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrclasscodev>(sqlstmt, parameters).ToList();
            recievedValues.mctrclasscodev = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgListClassCodeFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[2];

           string sqlstmt = "select distinct class_cd7, proj_trans_type, setid, descr, resource_sub_cat, effdt, eff_status from mctr_class_code_v  where proj_trans_type = :proj_trans_type_from and setid = :globalsetid order by class_cd7, proj_trans_type";
            parameters[0] = new OracleParameter(":proj_trans_type_from", OracleDbType.Varchar2, recievedValues.proj_trans_type_from, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrclasscodev>(sqlstmt, parameters).ToList();
            recievedValues.mctrclasscodev = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgWorkDeptFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[6];


            string sqlstmt = "select a.deptid,a.setid,a.acctg_loc_cd7,a.allow_pool_cd7,a.resource_sub_cat,a2.effdt,a2.eff_status from  mctr_locn_dept_mv a,  mctr_locn_dept_mv a2 where  a.setid = :0 and  a.deptid = :1 and  a.effdt =  (select max(a_ed.effdt) from mctr_locn_dept_mv a_ed where a.setid = a_ed.setid and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 and a.deptid = a_ed.deptid and a_ed.effdt <= :2) and a2.setid = :3 and  a2.deptid = :4 and  a2.acctg_loc_cd7 = a.acctg_loc_cd7 and  a2.effdt =  (select max(a2_ed.effdt) from mctr_locn_dept_mv a2_ed  where a2.setid = a2_ed.setid and a2.acctg_loc_cd7 = a2_ed.acctg_loc_cd7 and a2.deptid = a2_ed.deptid and a2_ed.effdt <= :5) order by  a.eff_status, a.effdt desc, a.deptid, a.setid, a.acctg_loc_cd7 ";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":work_dept_from", OracleDbType.Varchar2, recievedValues.work_dept_from, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.period_to, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":home_bugl_from", OracleDbType.Varchar2, recievedValues.home_bugl_from, ParameterDirection.Input);
            parameters[4] = new OracleParameter(":work_dept_from", OracleDbType.Varchar2, recievedValues.work_dept_from, ParameterDirection.Input);
            parameters[5] = new OracleParameter(":globalcow", OracleDbType.Date, recievedValues.cow, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocndeptmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocndeptmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgWorkDeptLocFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[7];

            string sqlstmt = @"select a.deptid,a.setid,a.acctg_loc_cd7,a.allow_pool_cd7,a.resource_sub_cat,a2.effdt,a2.eff_status 
from mctr_locn_dept_mv a,mctr_locn_dept_mv a2 where a.setid = :0 and  a.deptid = :1 
and a.acctg_loc_cd7 = :3 and  a.effdt =  (select max(a_ed.effdt) from mctr_locn_dept_mv a_ed 
where a.setid = a_ed.setid and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 and a.deptid = a_ed.deptid and a_ed.effdt <= :4) 
and a2.setid = :5 and  a2.deptid = :6 and  a2.acctg_loc_cd7 = a.acctg_loc_cd7 
and  a2.effdt =  (select max(a2_ed.effdt) from mctr_locn_dept_mv a2_ed  where a2.setid = a2_ed.setid and a2.acctg_loc_cd7 = a2_ed.acctg_loc_cd7 
and a2.deptid = a2_ed.deptid and a2_ed.effdt <= :7) order by  a.eff_status, a.effdt desc, a.deptid, a.setid, a.acctg_loc_cd7";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":work_dept_from", OracleDbType.Varchar2, recievedValues.work_dept_from, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":work_loc_from", OracleDbType.Varchar2, recievedValues.work_loc_from, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.period_to, ParameterDirection.Input);
            parameters[4] = new OracleParameter(":home_bugl_from", OracleDbType.Varchar2, recievedValues.home_bugl_from, ParameterDirection.Input);
            parameters[5] = new OracleParameter(":work_dept_from", OracleDbType.Varchar2, recievedValues.work_dept_from, ParameterDirection.Input);
            parameters[6] = new OracleParameter(":globalcow", OracleDbType.Date, recievedValues.cow, ParameterDirection.Input);


            var response = entities.Database.SqlQuery<mctrlocndeptmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocndeptmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgListWorkDeptFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[3];

            string sqlstmt = @"select  a.deptid,a.acctg_loc_cd7,a.setid,a.allow_pool_cd7,a.resource_sub_cat,a2.effdt, a2.eff_status 
from mctr_locn_dept_mv a,mctr_locn_dept_mv a2 where  a.setid = :0 and rtrim(a.deptid) is not null 
and a.effdt = (select max(a_ed.effdt) from mctr_locn_dept_mv a_ed where a.setid = a_ed.setid and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 
and a.deptid = a_ed.deptid and a_ed.effdt <= :1) and a2.setid = a.setid and a2.deptid = a.deptid and  a2.acctg_loc_cd7 = a.acctg_loc_cd7 
and a2.effdt = (select max(a2_ed.effdt) from mctr_locn_dept_mv a2_ed where a2.setid = a2_ed.setid and a2.acctg_loc_cd7 = a2_ed.acctg_loc_cd7 
and a2.deptid = a2_ed.deptid and a2_ed.effdt <= :3) order by a.deptid, a.acctg_loc_cd7, a.setid,  a.eff_status, a.effdt desc";


            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.period_to, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalcow", OracleDbType.Date, recievedValues.cow, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocndeptmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocndeptmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgWorkLocFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[3];

            string sqlstmt = @"select distinct a.acctg_loc_cd7,a.setid from mctr_locn_mv a where a.setid = :0 and a.acctg_loc_cd7 = :1   
and a.effdt = (select max(a_ed.effdt) from mctr_locn_mv a_ed where a.setid = a_ed.setid and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7
and a_ed.effdt <= :2) order by a.acctg_loc_cd7, a.setid";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":work_loc_from", OracleDbType.Varchar2, recievedValues.work_loc_from, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.period_to, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocnmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocnmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgListWorkLocFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[2];

            string sqlstmt = @"select distinct a.acctg_loc_cd7,a.setid  from mctr_locn_mv a  where a.setid = :0 and  a.effdt = (select max(a_ed.effdt)
from mctr_locn_mv a_ed where a.setid = a_ed.setid and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 and a_ed.effdt <= :1) order by a.acctg_loc_cd7, a.setid";


            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.period_to, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocnmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocnmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgRscFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[2];
            string sqlstmt = @"select a.resource_sub_cat,a.descr, a.effdt,a.eff_status from mctr_rsc_mv a where a.resource_sub_cat = :0 
and a.effdt = (select max(a_ed.effdt) from mctr_rsc_mv a_ed where a.resource_sub_cat = a_ed.resource_sub_cat and a_ed.effdt <= :1)  
union select null,  '** leave rsc null **', null, null from dual order by 1";


            parameters[0] = new OracleParameter(":rsc_from", OracleDbType.Varchar2, recievedValues.RESOURCE_SUB_CAT, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.period_to, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrrscmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrrscmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgWpdFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[1];

            string sqlstmt = "select distinct wpd_id7, descr30 from mctr_wp_master_v where wpd_id7 = :0";
            parameters[0] = new OracleParameter(":wpd_from", OracleDbType.Varchar2, recievedValues.WPD_ID7, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrwpmasterv>(sqlstmt, parameters).ToList();
            recievedValues.mctrwpmasterv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgBulkFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[3];

            string sqlstmt = "select bulk_alctn_cd7, proj_trans_type, descr from mctr_bulk_alctn_v where setid = :0 and proj_trans_type = :1 and bulk_alctn_cd7 = :2";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":proj_trans_type_from", OracleDbType.Varchar2, recievedValues.proj_trans_type_from, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":bulk_from", OracleDbType.Varchar2, recievedValues.BULK_ALCTN_CD7, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrbulkalctnv>(sqlstmt, parameters).ToList();
            recievedValues.mctrbulkalctnv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgCecEpFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[2];
            string sqlstmt = @"select a.setid, a.estmtg_pricg_cd7, a.effdt, a.eff_status, a.descrshort  from  mctr_estmtg_pricg_v a 
where estmtg_pricg_cd7 = :0 and setid = :1 order by a.estmtg_pricg_cd7,a.effdt desc";

            parameters[1] = new OracleParameter(":estmtg_pricg_cd_from", OracleDbType.Varchar2, recievedValues.ESTMTG_PRICG_CD7, ParameterDirection.Input);
            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrestmtgpricgv>(sqlstmt, parameters).ToList();
            recievedValues.mctrestmtgpricgv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgListCecEpFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[1];

            string sqlstmt = "select a.setid, a.estmtg_pricg_cd7, a.effdt, a.eff_status, a.descr from mctr_estmtg_pricg_v a where setid = :0 order by a.estmtg_pricg_cd7, a.effdt desc";
            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrestmtgpricgv>(sqlstmt, parameters).ToList();
            recievedValues.mctrestmtgpricgv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgProjToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[15];

            string sqlstmt = @"select distinct a.activity_id, p.business_unit_gl, a.project_id, p.account, p2.contract_num, p.bus_unit_mgmt_cd7, p.customer_type_cd7, 
a.effdt ACC_EFF_DT, p.effdt proj_eff_dt, a2.eff_status activity_status, p2.eff_status project_status, a.direct_chrg_flg7  
from   mctr_activity_v a, mctr_project_v p, mctr_activity_v a2, mctr_project_v p2 where  ((:0 = 'CY' and        
a.activity_id = :1 and a.effdt = (select max(a_ed.effdt) from mctr_activity_v a_ed where a.activity_id = a_ed.activity_id and
a.project_id = a_ed.project_id and  a_ed.effdt <= :2  and  (a_ed.eff_status = 'A' or (a_ed.eff_status = 'I' and a_ed.direct_chrg_flg7 = 'Y'))) 
and  a.setid = p.setid and  a.project_id = p.project_id and p.effdt = (select max(p_ed.effdt) from mctr_project_v p_ed 
where p.project_id = p_ed.project_id and  p_ed.effdt <= :3)) or (:4 = 'PY' and a.activity_id = :5 
and  a.effdt = (select max(a_ed.effdt) from mctr_activity_v a_ed  where a.activity_id = a_ed.activity_id and a.project_id = a_ed.project_id 
and  a_ed.effdt <= :6 and  a_ed.eff_status = 'A') and  a.setid = p.setid and  a.project_id = p.project_id 
and  p.effdt = (select max(p_ed.effdt) from mctr_project_v p_ed where p.project_id = p_ed.project_id and p_ed.effdt <= :7 
and  p_ed.eff_status = 'A')) or (:8 = 'PY' and  a.activity_id = :9 and  a.effdt = (select max(a_ed.effdt) 
from mctr_activity_v a_ed  where a.activity_id = a_ed.activity_id and  a.project_id = a_ed.project_id and  a_ed.effdt <= :10 and
a_ed.eff_status = 'A') and  a.setid = p.setid and  a.project_id = p.project_id and  p.effdt = (select max(p_ed.effdt) from mctr_project_v p_ed
where p.project_id = p_ed.project_id and  p_ed.effdt <= :11 and  p_ed.eff_status = 'A'))) and a2.activity_id = :12 
and a2.project_id  = a.project_id and a2.effdt = (select max(a2_ed.effdt) from mctr_activity_v a2_ed  where a2.activity_id = a2_ed.activity_id
and a2.project_id = a2_ed.project_id and  a2_ed.effdt <= :13) and a2.setid = p2.setid and a2.project_id = p2.project_id 
and p2.effdt = (select max(p2_ed.effdt) from mctr_project_v p2_ed where p2.project_id = p2_ed.project_id and p2_ed.effdt <= :14) 
order by a2.eff_status, a.effdt desc,  p2.eff_status, p.effdt desc,  a.project_id";

            string cowdate = string.Format("{0:dd-MMM-yyyy}", recievedValues.cow);

            string periodto = string.Format("{0:dd-MMM-yyyy}", recievedValues.period_to);

            parameters[0] = new OracleParameter(":globalpy_cy_status", OracleDbType.Varchar2, recievedValues.py_cy_status, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":activity_id_to", OracleDbType.Varchar2, recievedValues.activity_id_to, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[4] = new OracleParameter(":globalpy_cy_status", OracleDbType.Varchar2, recievedValues.py_cy_status, ParameterDirection.Input);
            parameters[5] = new OracleParameter(":activity_id_to", OracleDbType.Varchar2, recievedValues.activity_id_to, ParameterDirection.Input);
            parameters[6] = new OracleParameter(":globalcow", OracleDbType.Varchar2, cowdate, ParameterDirection.Input);
            parameters[7] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[8] = new OracleParameter(":globalpy_cy_status", OracleDbType.Varchar2, recievedValues.py_cy_status, ParameterDirection.Input);
            parameters[9] = new OracleParameter(":activity_id_to", OracleDbType.Varchar2, recievedValues.activity_id_to, ParameterDirection.Input);
            parameters[10] = new OracleParameter(":globalcow", OracleDbType.Varchar2, cowdate, ParameterDirection.Input);
            parameters[11] = new OracleParameter(":globalcow", OracleDbType.Varchar2, cowdate, ParameterDirection.Input);
            parameters[12] = new OracleParameter(":activity_id_to", OracleDbType.Varchar2, recievedValues.activity_id_to, ParameterDirection.Input);
            parameters[13] = new OracleParameter(":globalcow", OracleDbType.Varchar2, cowdate, ParameterDirection.Input);
            parameters[14] = new OracleParameter(":globalcow", OracleDbType.Varchar2, cowdate, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<getRgProj>(sqlstmt, parameters).ToList();
            recievedValues.getRgProj = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgProjToPromptLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[10];

            string sqlstmt = @"select distinct  a.activity_id, p.business_unit_gl, a.project_id, p.account, p2.contract_num, p.bus_unit_mgmt_cd7, p.customer_type_cd7, 
a.effdt as ACC_EFF_DT, a2.eff_status activity_status, p2.eff_status project_status from mctr_activity_v a,mctr_project_v p,mctr_activity_v a2,    
mctr_project_v p2 where a.activity_id = :0 and a.project_id like :1 and ((:2 = 'CY' and
a.eff_status = 'A' and  a.effdt = (select max(a_ed.effdt) from mctr_activity_v a_ed where a.activity_id = a_ed.activity_id and 
a.project_id = a_ed.project_id and a_ed.effdt <= :3  and (a_ed.eff_status = 'A' or (a_ed.eff_status = 'I' and a_ed.direct_chrg_flg7 = 'Y'))) 
and a.setid = p.setid and a.project_id = p.project_id and p.eff_status = 'A' and p.effdt = (select max(p_ed.effdt) from mctr_project_v p_ed
where p.project_id = p_ed.project_id and p.account = p_ed.account  and p_ed.effdt <= :4)) or(:5 = 'PY' and 
a.effdt = (select max(a_ed.effdt) from mctr_activity_v a_ed  where a.activity_id = a_ed.activity_id and  a.project_id = a_ed.project_id and
a_ed.effdt <= :6 and a_ed.eff_status = 'A') and a.setid = p.setid and a.project_id = p.project_id and p.effdt = (select max(p_ed.effdt)
from mctr_project_v p_ed where p.project_id = p_ed.project_id and  p.account = p_ed.account  and  p_ed.effdt <= :7 and
p_ed.eff_status = 'A'))) and a2.activity_id = a.activity_id and a2.project_id = a.project_id and a2.effdt = (select max(a2_ed.effdt) 
from mctr_activity_v a2_ed where a2.activity_id = a2_ed.activity_id and  a2.project_id = a2_ed.project_id and a2_ed.effdt <= :8) 
and a2.setid = p2.setid and a2.project_id = p2.project_id and  p2.project_id = p.project_id and p2.account = p.account and  
p2.effdt = (select max(p2_ed.effdt) from mctr_project_v p2_ed  where p2.project_id = p2_ed.project_id and p2.account = p2_ed.account 
and p2_ed.effdt <= :9)  order by a2.eff_status, a.effdt desc,  p2.eff_status,  a.project_id, p.account";
            string cowdate = string.Format("{0:dd-MMM-yyyy}", recievedValues.cow);

            string periodto = string.Format("{0:dd-MMM-yyyy}", recievedValues.EFFDT);

            parameters[0] = new OracleParameter(":activity_id_to", OracleDbType.Varchar2, recievedValues.ACTIVITY_ID, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":project_to_prompt", OracleDbType.Varchar2, recievedValues.PROJECT_ID, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalpy_cy_status", OracleDbType.Varchar2, recievedValues.py_cy_status, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[4] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[5] = new OracleParameter(":globalpy_cy_status", OracleDbType.Varchar2, recievedValues.py_cy_status, ParameterDirection.Input);
            parameters[6] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[7] = new OracleParameter(":period_to", OracleDbType.Varchar2, periodto, ParameterDirection.Input);
            parameters[8] = new OracleParameter(":globalcow", OracleDbType.Varchar2, cowdate, ParameterDirection.Input);
            parameters[9] = new OracleParameter(":globalcow", OracleDbType.Varchar2, cowdate, ParameterDirection.Input);


            var response = entities.Database.SqlQuery<getRgProj>(sqlstmt, parameters).ToList();
            recievedValues.getRgProj = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgHomeDeptToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[4];
            string sqlstmt = @"select a.deptid, a.setid,a.acctg_loc_cd7,a.allow_pool_cd7,a.labor_rate_cd7, decode( a.resource_sub_cat,'095','B','A') class_cd,  
a.resource_sub_cat, a2.effdt, a2.eff_status from  mctr_locn_dept_mv a,  mctr_locn_dept_mv a2 where  a.setid = :0 and  
a.deptid = :1 and  a.effdt = (select max(a_ed.effdt) from mctr_locn_dept_mv a_ed   where a.setid = a_ed.setid and
a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 and a.deptid = a_ed.deptid and  a_ed.effdt <= :2) and  a.setid = a2.setid and  
a.deptid = a2.deptid and  a.acctg_loc_cd7 = a2.acctg_loc_cd7 and  a2.effdt = (select max(a2_ed.effdt) from mctr_locn_dept_mv a2_ed  
where a2.setid = a2_ed.setid and  a2.acctg_loc_cd7 = a2_ed.acctg_loc_cd7 and a2.deptid = a2_ed.deptid and  a2_ed.effdt <= :3) 
order by  a.eff_status, a.effdt desc, a.deptid, a.setid, a.acctg_loc_cd7";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":home_dept_to", OracleDbType.Varchar2, recievedValues.DEPTID, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.EFFDT, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":globalcow", OracleDbType.Date, recievedValues.cow, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocndeptmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocndeptmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgHomeDeptLocToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();
            OracleParameter[] parameters = new OracleParameter[5];
            string sqlstmt = @"select a.deptid, a.setid,a.acctg_loc_cd7,a.allow_pool_cd7,a.labor_rate_cd7,decode( a.resource_sub_cat,'095','B','A') class_cd,  
a.resource_sub_cat, a2.effdt, a2.eff_status from  mctr_locn_dept_mv a,mctr_locn_dept_mv a2 where  a.setid = :0 and  
a.deptid = :1 and  a.acctg_loc_cd7 = :2 and  a.effdt =  (select max(a_ed.effdt) from mctr_locn_dept_mv a_ed   
where a.setid = a_ed.setid and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 and a.deptid = a_ed.deptid and  a_ed.effdt <= :3) 
and  a.setid = a2.setid and   a.deptid = a2.deptid and  a.acctg_loc_cd7 = a2.acctg_loc_cd7 and  a2.effdt =  (select max(a2_ed.effdt)
from mctr_locn_dept_mv a2_ed   where a2.setid = a2_ed.setid and a2.acctg_loc_cd7 = a2_ed.acctg_loc_cd7 and a2.deptid = a2_ed.deptid
and a2_ed.effdt <= :4) order by  a.eff_status, a.effdt desc, a.deptid, a.setid, a.acctg_loc_cd7";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":home_dept_to", OracleDbType.Varchar2, recievedValues.DEPTID, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":home_loc_to", OracleDbType.Varchar2, recievedValues.ACCTG_LOC_CD7, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.EFFDT, ParameterDirection.Input);
            parameters[4] = new OracleParameter(":globalcow", OracleDbType.Date, recievedValues.cow, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocndeptmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocndeptmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgListHomeDeptToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[3];
            string sqlstmt = @"select a.deptid, a.acctg_loc_cd7, a.setid,a.allow_pool_cd7,a.labor_rate_cd7,decode( a.resource_sub_cat,'095','B','A') class_cd,
a.resource_sub_cat, a2.effdt, a2.eff_status from  mctr_locn_dept_mv a,mctr_locn_dept_mv a2 where a.setid = :0 
and  rtrim(a.deptid) is not null and   a.effdt =  (select max(a_ed.effdt) from mctr_locn_dept_mv a_ed  where a.setid = a_ed.setid 
and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 and  a.deptid = a_ed.deptid and  a_ed.effdt <= :1) and a2.setid = a.setid 
and a2.deptid = a.deptid and  a2.acctg_loc_cd7 = a.acctg_loc_cd7 and  a2.effdt =  (select max(a2_ed.effdt) from mctr_locn_dept_mv a2_ed   
where a2.setid = a2_ed.setid and a2.acctg_loc_cd7 = a2_ed.acctg_loc_cd7 and a2.deptid = a2_ed.deptid and  a2_ed.effdt <= :2) 
order by a.deptid, a.acctg_loc_cd7, a.setid, a.eff_status, a.effdt desc";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.EFFDT, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalcow", OracleDbType.Date, recievedValues.cow, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocndeptmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocndeptmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgHomeLocToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[3];
            string sqlstmt = @"select a.acctg_loc_cd7, a.setid from mctr_locn_mv a  where a.setid = :0 and a.acctg_loc_cd7 = :1 and a.effdt = 
(select max(a_ed.effdt) from mctr_locn_mv a_ed where a.setid = a_ed.setid and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 and a_ed.effdt <= :3)
and a.eff_status = 'A'  order by a.acctg_loc_cd7, a.setid";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":home_loc_to", OracleDbType.Varchar2, recievedValues.ACCTG_LOC_CD7, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.EFFDT, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocnmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocnmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgListHomeLocToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[2];
            string sqlstmt = @"select a.acctg_loc_cd7, a.setid  from mctr_locn_mv a  where a.setid = :0 and  a.effdt = (select max(a_ed.effdt)
from mctr_locn_mv a_ed where a.setid = a_ed.setid  and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 and a_ed.effdt <= :1)      
and a.eff_status = 'A'  order by a.acctg_loc_cd7, a.setid";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.EFFDT, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocnmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocnmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgClassCodeToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[3];
            string sqlstmt = @"select distinct class_cd7, proj_trans_type, setid, descr, resource_sub_cat, effdt, eff_status from mctr_class_code_v  
where class_cd7 = :0 and proj_trans_type = :1 and setid = :2 and eff_status = 'A'";

            parameters[0] = new OracleParameter(":class_cd_to", OracleDbType.Varchar2, recievedValues.CLASS_CD7, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":proj_trans_type_to", OracleDbType.Varchar2, recievedValues.PROJ_TRANS_TYPE, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrclasscodev>(sqlstmt, parameters).ToList();
            recievedValues.mctrclasscodev = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgListClassCodeToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[2];
            string sqlstmt = @"select distinct class_cd7, proj_trans_type, setid, descr, resource_sub_cat, eff_status, effdt from mctr_class_code_v  
where proj_trans_type = :0 and setid = :1 and eff_status = 'A'  order by class_cd7, proj_trans_type";

            parameters[0] = new OracleParameter(":proj_trans_type_to", OracleDbType.Varchar2, recievedValues.proj_trans_type_to, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrclasscodev>(sqlstmt, parameters).ToList();
            recievedValues.mctrclasscodev = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgWorkDeptToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[6];

            string sqlstmt = @"select  a.deptid, a.setid, a.acctg_loc_cd7, a.allow_pool_cd7,a.resource_sub_cat, a2.effdt, a2.eff_status from  mctr_locn_dept_mv a,  
mctr_locn_dept_mv a2 where  a.setid = :0 and  a.deptid = :1 and  a.effdt =  (select max(a_ed.effdt)
from mctr_locn_dept_mv a_ed  where a.setid = a_ed.setid and  a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 and  a.deptid = a_ed.deptid and
a_ed.effdt <= :2)  and  a2.setid = :3 and  a2.deptid = :4 and  a2.acctg_loc_cd7 = a.acctg_loc_cd7 and
a2.effdt =  (select max(a2_ed.effdt) from mctr_locn_dept_mv a2_ed where a2.setid = a2_ed.setid and a2.acctg_loc_cd7 = a2_ed.acctg_loc_cd7 
and a2.deptid = a2_ed.deptid and a2_ed.effdt <= :5) order by  a.eff_status, a.effdt desc, a.deptid, a.setid, a.acctg_loc_cd7";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":work_dept_to", OracleDbType.Varchar2, recievedValues.DEPTID, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.EFFDT, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":home_bugl_to", OracleDbType.Varchar2, recievedValues.home_bugl_to, ParameterDirection.Input);
            parameters[4] = new OracleParameter(":work_dept_to", OracleDbType.Varchar2, recievedValues.work_dept_to, ParameterDirection.Input);
            parameters[5] = new OracleParameter(":globalcow", OracleDbType.Date, recievedValues.cow, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocndeptmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocndeptmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgWorkDeptLocToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[7];
            string sqlstmt = @"select  a.deptid, a.setid, a.acctg_loc_cd7, a.allow_pool_cd7,a.resource_sub_cat, a2.effdt, a2.eff_status from  mctr_locn_dept_mv a,  
mctr_locn_dept_mv a2 where a.setid = :0 and  a.deptid = :1 and  a2.acctg_loc_cd7 = :2 and  
a.effdt =  (select max(a_ed.effdt) from mctr_locn_dept_mv a_ed where a.setid = a_ed.setid and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 
and a.deptid = a_ed.deptid and a_ed.effdt <= :3) and  a2.setid = :4 and  a2.deptid = :5 
and  a2.acctg_loc_cd7 = a.acctg_loc_cd7 and  a2.effdt =  (select max(a2_ed.effdt) from mctr_locn_dept_mv a2_ed    
where a2.setid = a2_ed.setid and a2.acctg_loc_cd7 = a2_ed.acctg_loc_cd7 and a2.deptid = a2_ed.deptid and  a2_ed.effdt <= :6) 
order by  a.eff_status, a.effdt desc, a.deptid, a.setid, a.acctg_loc_cd7";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":work_dept_to", OracleDbType.Varchar2, recievedValues.DEPTID, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":work_loc_to", OracleDbType.Varchar2, recievedValues.ACCTG_LOC_CD7, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.EFFDT, ParameterDirection.Input);
            parameters[4] = new OracleParameter(":home_bugl_to", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[5] = new OracleParameter(":work_dept_to", OracleDbType.Varchar2, recievedValues.DEPTID, ParameterDirection.Input);
            parameters[6] = new OracleParameter(":globalcow", OracleDbType.Date, recievedValues.cow, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocndeptmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocndeptmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgListWorkDeptToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[3];
            string sqlstmt = @"select  a.deptid,a.setid,a.acctg_loc_cd7,a.allow_pool_cd7,a.resource_sub_cat,a2.effdt,a2.eff_status from mctr_locn_dept_mv a,
mctr_locn_dept_mv a2 where a.setid = :0 and  rtrim(a.deptid) is not null and   a.effdt = (select max(a_ed.effdt)
from mctr_locn_dept_mv a_ed where a.setid = a_ed.setid and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7 and a.deptid = a_ed.deptid and
a_ed.effdt <= :1) and a2.setid = a.setid and a2.deptid = a.deptid and a2.acctg_loc_cd7 = a.acctg_loc_cd7 and  
a2.effdt = (select max(a2_ed.effdt) from mctr_locn_dept_mv a2_ed  where a2.setid = a2_ed.setid and a2.acctg_loc_cd7 = a2_ed.acctg_loc_cd7 and
a2.deptid = a2_ed.deptid and a2_ed.effdt <= :2) order by a.deptid, a.acctg_loc_cd7, a.setid, a.eff_status, a.effdt desc";

            parameters[0] = new OracleParameter(":home_bugl_from", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.EFFDT, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":globalcow", OracleDbType.Date, recievedValues.cow, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocndeptmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocndeptmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgWorkLocToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[3];
            string sqlstmt = @"select distinct a.acctg_loc_cd7, a.setid  from mctr_locn_mv a  where a.setid = :0 and  a.acctg_loc_cd7 = :1 
and a.effdt = (select max(a_ed.effdt) from mctr_locn_mv a_ed  where a.setid = a_ed.setid and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7
and a_ed.effdt <= :2) and a.eff_status = 'A' order by a.acctg_loc_cd7, a.setid";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":work_loc_to", OracleDbType.Varchar2, recievedValues.ACCTG_LOC_CD7, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.EFFDT, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocnmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocnmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgListWorkLocToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[2];
            string sqlstmt = @"select distinct a.acctg_loc_cd7, a.setid from mctr_locn_mv a  where a.setid = :0 and a.effdt = (select max(a_ed.effdt)
from mctr_locn_mv a_ed where a.setid = a_ed.setid and a.acctg_loc_cd7 = a_ed.acctg_loc_cd7  and a_ed.effdt <= :1)   
and a.eff_status = 'A' order by a.acctg_loc_cd7, a.setid";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.EFFDT, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrlocnmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrlocnmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgRscToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();

            OracleParameter[] parameters = new OracleParameter[3];
            string sqlstmt = @"select a.resource_sub_cat, a.descr, a.effdt, a.eff_status from mctr_rsc_mv a  where a.resource_sub_cat = :0  and  
a.effdt = (select max(a_ed.effdt) from mctr_rsc_mv a_ed  where a.resource_sub_cat = a_ed.resource_sub_cat and a_ed.effdt <= :1) 
union select null, '** LEAVE RSC null **', null, null from dual where :2 in ('OVERHEAD', 'NON-PROJ') order by 1";

            parameters[0] = new OracleParameter(":rsc_to", OracleDbType.Varchar2, recievedValues.RESOURCE_SUB_CAT, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":period_to", OracleDbType.Date, recievedValues.EFFDT, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":activity_id_to", OracleDbType.Varchar2, recievedValues.ACTIVITY_ID, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrrscmv>(sqlstmt, parameters).ToList();
            recievedValues.mctrrscmv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgWpdToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();

            OracleParameter[] parameters = new OracleParameter[6];
            string sqlstmt = @"select l.wpd_id7, l.acctg_loc_cd7, l.deptid, l.descr30, l.effdt from mctr_wp_locdept_v l where l.setid = :0 
            and l.acctg_loc_cd7 = :1 and l.deptid = :2 and l.eff_status = 'A'  
            union select  w.wpd_id7, ' ', ' ', w.descr30, w.effdt effdt from mctr_wp_master_v w  where w.eff_status = 'A' and   
            w.wpd_id7 not in ('IN','999') union select null, ' ', ' ',  '** leave wpd null (blank value) **' , null from dual where :3 is not null
            and (:4 <> 'LBR'  or :5 < 2005) order by 2 desc, 3 desc, 1";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":work_loc_to", OracleDbType.Varchar2, recievedValues.ACCTG_LOC_CD7, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":work_dept_to", OracleDbType.Varchar2, recievedValues.DEPTID, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":wpd_to", OracleDbType.Varchar2, recievedValues.WPD_ID7, ParameterDirection.Input);
            parameters[4] = new OracleParameter(":proj_trans_type_to", OracleDbType.Varchar2, recievedValues.PROJ_TRANS_TYPE, ParameterDirection.Input);
            parameters[5] = new OracleParameter(":fiscal_year", OracleDbType.Int32, recievedValues.fiscal_year, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrwplocdeptv>(sqlstmt, parameters).ToList();
            recievedValues.mctrwplocdeptv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgBulkToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[3];
            string sqlstmt = "select bulk_alctn_cd7, proj_trans_type, descr, eff_status  from mctr_bulk_alctn_v where setid = :0 and proj_trans_type = :1 union select null,' ', '** NO BULK ALLOCATION (BLANK VALUE)',null from dual where :2 is not null order by 1";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":proj_trans_type_to", OracleDbType.Varchar2, recievedValues.PROJ_TRANS_TYPE, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":bulk_to", OracleDbType.Varchar2, recievedValues.BULK_ALCTN_CD7, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrbulkalctnv>(sqlstmt, parameters).ToList();
            recievedValues.mctrbulkalctnv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgCecEpToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();

            OracleParameter[] parameters = new OracleParameter[2];
            string sqlstmt = @"select a.setid, a.estmtg_pricg_cd7, a.effdt, a.eff_status, a.descrshort  from  mctr_estmtg_pricg_v a 
where estmtg_pricg_cd7 = :0 and eff_status = 'A'  and setid = :1";


            parameters[0] = new OracleParameter(":estmtg_pricg_cd_to", OracleDbType.Varchar2, recievedValues.ESTMTG_PRICG_CD7, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrestmtgpricgv>(sqlstmt, parameters).ToList();
            recievedValues.mctrestmtgpricgv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgListCecEpToLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[1];
            string sqlstmt = @"Select a.setid, a.estmtg_pricg_cd7,a.descr from mctr_estmtg_pricg_v a where setid = :0 and eff_status = 'A' 
order by a.estmtg_pricg_cd7, a.setid";

            parameters[0] = new OracleParameter(":globalsetid", OracleDbType.Varchar2, recievedValues.setid, ParameterDirection.Input);
            var response = entities.Database.SqlQuery<mctrestmtgpricgv>(sqlstmt, parameters).ToList();
            recievedValues.mctrestmtgpricgv = response;
            return createMctrLov;
        }

        public IEnumerable<CreateMctrLov> getRgAffiliateFromLOV(IEnumerable<CreateMctrLov> createMctrLov)
        {
            CreateMctrLov recievedValues = createMctrLov.First();


            OracleParameter[] parameters = new OracleParameter[7];
            string sqlstmt = @"select distinct affiliate from mctr_rp_master_vw where activity_id = :0 and project_id = :1  
and account = :2 and bus_unit_gl_from = :3 and business_unit_gl = :4 
and ((proj_trans_type like 'LB%' and :5 = 'LBR') or proj_trans_type = :6) order by affiliate";

            parameters[0] = new OracleParameter(":activity_id_from", OracleDbType.Varchar2, recievedValues.ACTIVITY_ID, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":project_id_from", OracleDbType.Varchar2, recievedValues.PROJECT_ID, ParameterDirection.Input);
            parameters[2] = new OracleParameter(":account_from", OracleDbType.Varchar2, recievedValues.ACCOUNT, ParameterDirection.Input);
            parameters[3] = new OracleParameter(":home_bugl_from", OracleDbType.Varchar2, recievedValues.BUS_UNIT_GL_FROM, ParameterDirection.Input);
            parameters[4] = new OracleParameter(":work_bugl_from", OracleDbType.Varchar2, recievedValues.BUSINESS_UNIT_GL, ParameterDirection.Input);
            parameters[5] = new OracleParameter(":proj_trans_type_from", OracleDbType.Varchar2, recievedValues.PROJ_TRANS_TYPE, ParameterDirection.Input);
            parameters[6] = new OracleParameter(":proj_trans_type_from", OracleDbType.Varchar2, recievedValues.PROJ_TRANS_TYPE, ParameterDirection.Input);

            var response = entities.Database.SqlQuery<mctrrpmastervw>(sqlstmt, parameters).ToList();
            recievedValues.mctrrpmastervw = response;
            return createMctrLov;
        }
    }
}
