///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///
 
///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using System.Data;
using log4net;
using Oracle.ManagedDataAccess.Client;

using MCTR.DomainEntity;
using MCTR.DataEntity;
using MCTR.DataAccessInterface;


namespace MCTR.DataAccess
{
///*********************************************************************
///<summary>
///MctrRptsAdmnBlRepository is a data access implementation which holds all 
///the data access logic in it.
///</summary>
  public class MctrRptsAdmnBlRepository : BaseRepository, IMctrRptsAdmnBlRepository
  {
    
        private readonly ILog logger = null;
        public MctrRptsAdmnBlRepository()
    {
      logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
    }


        ///*************************************************************
        ///<summary>
        ///Method Name : selectionbutBuWhenButtonPressedOpenLOV
        ///</summary>
        ///<param name = "MctrRptsAdmnBl"></param>
        ///<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        public IEnumerable<BusUnit> selectionbutBuWhenButtonPressedOpenLOV(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl)
        {
            MctrRptsAdmnBl mctrcreateForm = mctrRptsAdmnBl.First();
            OracleParameter[] parameters = new OracleParameter[2];

            string sqlstmt = @"select business_unit, group_cd7, descr, effdt, eff_status
                                from(select b.business_unit, b.group_cd7, b.descr, b.effdt, b.eff_status
                                from mctr_bus_unit_v b
                                where exists(select rb.business_unit from mctr_role_bu rb where rb.bems = :0
                                and(rb.business_unit = b.business_unit or(rb.group_cd7 = b.group_cd7 and  rb.business_unit = '**')))
                                union
                                select '**' as business_unit , group_cd7, null as descr, null as effdt, null as eff_status from mctr_role_bu
                                where exists(select rb.business_unit from mctr_role_bu rb where rb.bems = :1
                                and rb.group_cd7 = mctr_role_bu.group_cd7  and rb.business_unit = '**')) tbl
                                where exists(select * from mctr_role_bu where business_unit = tbl.business_unit
                                and exists(select * from mctr_role where bems = mctr_role_bu.bems and active = 'Y'))
                                order by business_unit";
            //where (:orig_bu is null or (:orig_bu is not null and  b.business_unit <> :orig_bu)) and exists  (select rb.business_unit from MCTR_ROLE_BU rb   where rb.bems = :bems and (rb.business_unit = b.business_unit or (rb.group_cd7 = b.group_cd7 and  rb.business_unit = '**'))) and exists (select bp.business_unit from mctr_bu_profile bp  where bp.business_unit = b.business_unit) order by b.business_unit";

            parameters[0] = new OracleParameter(":0", OracleDbType.Varchar2, mctrcreateForm.SessionBems, ParameterDirection.Input);
            parameters[1] = new OracleParameter(":1", OracleDbType.Varchar2, mctrcreateForm.SessionBems, ParameterDirection.Input);

            return entities.Database.SqlQuery<BusUnit>(sqlstmt, parameters).ToList();


        }

        public IEnumerable<WeeklyJournalDates> selectionbutToDateWhenButtonPressedOpenLOV()
        {
            string sqlstmt = @"SELECT DISTINCT date_journal,  SUM(ttl_count) as mctr_ttl_count, SUM(eot_count) as mctr_eot_count 
                                FROM MCTR_ACCTG_WEEKS_V WKS, (select to_date(trunc(date_journal),'DD-MON-YY') as date_journal,       
                                count(*) as ttl_count, max(0) as eot_count    from mctr_header   where date_journal is not null   
                                and trunc(date_journal) < trunc(sysdate)  and trunc(date_journal) > (trunc(sysdate) - 750)   
                                group by trunc(date_journal)  
                                union
                                select to_date(trunc(date_journal),'DD-MON-YY') as date_journal,  max(0) as ttl_count, count(*) as eot_count   
                                from mctr_header   where date_journal is not null  and trunc(date_journal) < trunc(sysdate)   
                                and trunc(date_journal) > (trunc(sysdate) - 750)
                                and orig_bu IN ('9T','9L','9M','9R')   group by trunc(date_journal)) TBL WHERE TBL.date_journal = TRUNC(WKS.BEGIN_DT)  AND WKS.FISCAL_YEAR >= (SELECT FISCAL_YEAR - 1 FROM MCTR_WEEK_V) 
                                GROUP BY TBL.date_journal ORDER BY TBL.date_journal DESC";

            return entities.Database.SqlQuery<WeeklyJournalDates>(sqlstmt).ToList();
        }

        /////*************************************************************
        /////<summary>
        /////Method Name : selectionbutActiveRoleBuListWhenButtonPressed
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> selectionbutActiveRoleBuListWhenButtonPressed(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing selectionbutActiveRoleBuListWhenButtonPressed with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : selectionrgrpUrolesWhenRadioChanged
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> selectionrgrpUrolesWhenRadioChanged(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing selectionrgrpUrolesWhenRadioChanged with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : selectionfDaysOnError
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> selectionfDaysOnError(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing selectionfDaysOnError with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : selectionfDaysPostChange
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> selectionfDaysPostChange(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing selectionfDaysPostChange with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : selectionbutActiveUserListWhenButtonPressed
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> selectionbutActiveUserListWhenButtonPressed(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing selectionbutActiveUserListWhenButtonPressed with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : selectionbutToDateWhenButtonPressedOpenLOV
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> selectionbutToDateWhenButtonPressedOpenLOV(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing selectionbutToDateWhenButtonPressedOpenLOV with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : selectionbutExcelEotWhenButtonPressed
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> selectionbutExcelEotWhenButtonPressed(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing selectionbutExcelEotWhenButtonPressed with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : selectionbutQtrlyRoleListWhenButtonPressed
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> selectionbutQtrlyRoleListWhenButtonPressed(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing selectionbutQtrlyRoleListWhenButtonPressed with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : webutildummyWhenButtonPressed
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> webutildummyWhenButtonPressed(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing webutildummyWhenButtonPressed with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : webutilwebutilClientinfoFunctionsWhenCustomItemEvent
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> webutilwebutilClientinfoFunctionsWhenCustomItemEvent(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing webutilwebutilClientinfoFunctionsWhenCustomItemEvent with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : webutilwebutilFileFunctionsWhenCustomItemEvent
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> webutilwebutilFileFunctionsWhenCustomItemEvent(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing webutilwebutilFileFunctionsWhenCustomItemEvent with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : webutilwebutilHostFunctionsWhenCustomItemEvent
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> webutilwebutilHostFunctionsWhenCustomItemEvent(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing webutilwebutilHostFunctionsWhenCustomItemEvent with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : webutilwebutilSessionFunctionsWhenCustomItemEvent
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> webutilwebutilSessionFunctionsWhenCustomItemEvent(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing webutilwebutilSessionFunctionsWhenCustomItemEvent with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : webutilwebutilFiletransferFunctionsWhenCustomItemEvent
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> webutilwebutilFiletransferFunctionsWhenCustomItemEvent(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing webutilwebutilFiletransferFunctionsWhenCustomItemEvent with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : webutilwebutilOleFunctionsWhenCustomItemEvent
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> webutilwebutilOleFunctionsWhenCustomItemEvent(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing webutilwebutilOleFunctionsWhenCustomItemEvent with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : webutilwebutilCApiFunctionsWhenCustomItemEvent
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> webutilwebutilCApiFunctionsWhenCustomItemEvent(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing webutilwebutilCApiFunctionsWhenCustomItemEvent with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : webutilwebutilBrowserFunctionsWhenCustomItemEvent
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> webutilwebutilBrowserFunctionsWhenCustomItemEvent(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing webutilwebutilBrowserFunctionsWhenCustomItemEvent with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : mctrRptsAdmnBlWhenWindowClosed
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBlWhenWindowClosed(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing mctrRptsAdmnBlWhenWindowClosed with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}

        /////*************************************************************
        /////<summary>
        /////Method Name : mctrRptsAdmnBlWhenNewFormInstance
        /////</summary>
        /////<param name = "MctrRptsAdmnBl"></param>
        /////<returns>IEnumerable<MctrRptsAdmnBl> </returns>

        //public IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBlWhenNewFormInstance(IEnumerable<MctrRptsAdmnBl> mctrRptsAdmnBl){
        //OracleParameter[] parameters = new OracleParameter[10];
        //logger.Debug("Executing mctrRptsAdmnBlWhenNewFormInstance with input : " + mctrRptsAdmnBl);
        ////TODO: Move the Data Access logic from the Business implementation class to here.
        //return null;
        //}


    }

}

