///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using System.Data;
using log4net;
using Oracle.ManagedDataAccess.Client;

using MCTR.DomainEntity;
//using MCTR.DataEntity;
using MCTR.DataAccessInterface;
using MCTR.DataEntity;

namespace MCTR.DataAccess
{
    ///*********************************************************************
    ///<summary>
    ///MctrCompRatesRepository is a data access implementation which holds all 
    ///the data access logic in it.
    ///</summary>
    public class MctrCompRatesRepository : BaseRepository, IMctrCompRatesRepository //: BaseRepository,
    {

        private readonly ILog logger = null;
        private MctrCompRates obj;

        MctrCompRates cratedomain = new MctrCompRates();

        public MctrCompRatesRepository()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrcompratesonload
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public IEnumerable<MctrCompRates> mctrcompratesonload(IEnumerable<MctrCompRates> mctrCompRates)
        {
            logger.Debug("Executing MCTR.DataAccess.MctrCompRatesRepository.mctrcompratesonload with input : " + mctrCompRates);
            try
            {
                obj = mctrCompRates.First<MctrCompRates>();
                OracleParameter[] parameter1 = new OracleParameter[17];
                string sqlstmt = "select * from mctr_owner.mctr_comp_rates where (cmpon_cd like :0 or :0 is null ) and ( fiscal_year like :1 or :1 is null ) and ( rsc_input like :2 or :2 is null ) and ( cust_type_input like :3 or :3 is null ) and ( bum_input like :4 or :4 is null ) and ( rsc_output like :5 or :5 is null ) and ( pool_output like :6 or :6 is null ) and ( comp_seq = :7 or :7 is null ) and exists ( select lu . business_unit from mctr_role_bu lu where lu . bems = :16 and ( lu.business_unit = cmpon_cd or ( lu.business_unit = '**' and exists ( select bu.business_unit from mctr_bus_unit_v bu where bu.business_unit = cmpon_cd and bu.group_cd7 = lu.group_cd7 ) ) ) ) order by cmpon_cd , fiscal_year , rsc_input , cust_type_input , bum_input , rsc_output , pool_output";
                var fiscalYrFilter = obj.FISCAL_YEAR.ToString() == "0" ? null : obj.FISCAL_YEAR.ToString();
                var compSeqFilter = obj.COMP_SEQ.ToString() == "0" ? null : obj.COMP_SEQ.ToString();
                parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, obj.CMPON_CD, ParameterDirection.Input);
                parameter1[1] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, obj.CMPON_CD, ParameterDirection.Input);
                parameter1[2] = new OracleParameter(":fiscal_year", OracleDbType.Int64, fiscalYrFilter, ParameterDirection.Input);
                parameter1[3] = new OracleParameter(":fiscal_year", OracleDbType.Int64, fiscalYrFilter, ParameterDirection.Input);
                parameter1[4] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, obj.RSC_INPUT, ParameterDirection.Input);
                parameter1[5] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, obj.RSC_INPUT, ParameterDirection.Input);
                parameter1[6] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, obj.CUST_TYPE_INPUT, ParameterDirection.Input);
                parameter1[7] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, obj.CUST_TYPE_INPUT, ParameterDirection.Input);
                parameter1[8] = new OracleParameter(":bum_input", OracleDbType.Varchar2, obj.BUM_INPUT, ParameterDirection.Input);
                parameter1[9] = new OracleParameter(":bum_input", OracleDbType.Varchar2, obj.BUM_INPUT, ParameterDirection.Input);
                parameter1[10] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, obj.RSC_OUTPUT, ParameterDirection.Input);
                parameter1[11] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, obj.RSC_OUTPUT, ParameterDirection.Input);
                parameter1[12] = new OracleParameter(":pool_output", OracleDbType.Varchar2, obj.POOL_OUTPUT, ParameterDirection.Input);
                parameter1[13] = new OracleParameter(":pool_output", OracleDbType.Varchar2, obj.POOL_OUTPUT, ParameterDirection.Input);
                parameter1[14] = new OracleParameter(":comp_seq", OracleDbType.Int64, compSeqFilter, ParameterDirection.Input);
                parameter1[15] = new OracleParameter(":comp_seq", OracleDbType.Int64, compSeqFilter, ParameterDirection.Input);
                parameter1[16] = new OracleParameter(":16", OracleDbType.Varchar2, obj.session_bems, ParameterDirection.Input);

                var resultlist = entities.Database.SqlQuery<MctrCompRates>(sqlstmt, parameter1).ToList<MctrCompRates>();
                logger.Debug("Response received from MCTR.DataAccess.MctrCompRatesRepository.mctrcompratesonload with response : " + resultlist);
                return resultlist;
            }
            catch (OracleException e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.mctrcompratesonload" + e.Message);

                throw;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.mctrIncrRatesMctrIncrRatesOnLoad" + e.Message);

                throw;
            }

        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrCompRatescmponCdPostTextItem
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public IEnumerable<MctrCompRates> mctrCompRatescmponCdPostTextItem(IEnumerable<MctrCompRates> mctrCompRates)
        {
            logger.Debug("Executing MCTR.DataAccess.MctrCompRatesRepository.mctrCompRatescmponCdPostTextItem with input : " + mctrCompRates);
            try
            {
                obj = mctrCompRates.First<MctrCompRates>();
             

                //if (obj.CMPON_CD != null)
                //{
                OracleParameter[] parameters = new OracleParameter[2];

                string sqlstmt = "select count(*) from mctr_role_bu lu where lu.bems = :0 and (lu.business_unit =:1 or (lu.business_unit = '**' and exists ( select bu.business_unit from mctr_bus_unit_v bu where bu.business_unit =:1 and bu.group_cd7 = lu.group_cd7 ) ) )";
                parameters[0] = new OracleParameter(":lu.bems", OracleDbType.Varchar2, obj.session_bems, ParameterDirection.Input);//,
                parameters[1] = new OracleParameter(":lu.business_unit", OracleDbType.Varchar2, obj.CMPON_CD, ParameterDirection.Input);

                obj.v_count = entities.Database.SqlQuery<int>(sqlstmt, parameters).Single<int>();
                //}
                //if (v_count == 0)
                //{
                //    obj.CMPON_CD = null;
                //    throw new Exception("this bu is not found in your bu/group access using mctr role bu table.");
                //    //message ='This BU is not in your BU/Group access';
                //}
                //logger.Debug("Response received from MCTR.DataAccess.MctrCompRatesRepository.mctrCompRatescmponCdPostTextItem with response : " + mctrCompRates);

                List<MctrCompRates> crates = new List<MctrCompRates>();
                crates.Add(obj);
                return crates;
            }

            catch (OracleException e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.mctrCompRatescmponCdPostTextItem" + e.Message);

                throw;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.mctrCompRatescmponCdPostTextItem" + e.Message);

                throw;
            }
        }


        //************************************************************
        ///<summary>
        ///Method Name : mctrCompRatesrscOutputPostChange
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public IEnumerable<MctrCompRates> mctrCompRatesrscOutputPostChange(IEnumerable<MctrCompRates> mctrCompRates)
        {
            logger.Debug("Executing mctrCompRatesrscOutputPostChange with input : " + mctrCompRates);
            try
            {
                OracleParameter[] parameter1 = new OracleParameter[3];
                obj = mctrCompRates.First<MctrCompRates>();

            
                // StringBuilder query = new StringBuilder(" select rsc_pool as rate_i_rsc_pool, rate as rate_i from mctr_incr_rates where cmpon_cd = :0 and fiscal_year = :1 and rsc_pool = :2");
                StringBuilder query = new StringBuilder(" select rsc_pool as rate_i_rsc_pool, rate as rate_i from mctr_incr_rates where cmpon_cd = :0 and fiscal_year = :1 and rsc_pool = :2");

                parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, obj.CMPON_CD, ParameterDirection.Input);
                parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int64, obj.FISCAL_YEAR, ParameterDirection.Input);
                parameter1[2] = new OracleParameter(":rsc_pool", OracleDbType.Varchar2, obj.RSC_OUTPUT, ParameterDirection.Input);

                var resultlist = entities.Database.SqlQuery<MctrCompRates>(query.ToString(), parameter1).ToList<MctrCompRates>();

                if (resultlist.Count != 0)
                {
                    List<MctrCompRates> crates = new List<MctrCompRates>();
                    var c = resultlist.First<MctrCompRates>();
                    //c.RATE_OUTPUT = c.RATE_I * (obj.BASE_AMT + obj.RATE_1 + obj.RATE_2 + obj.RATE_3 + obj.RATE_4 + obj.RATE_5 + obj.RATE_6 + obj.RATE_7 + obj.RATE_8);
                    c.RATE_OUTPUT = c.RATE_I * (obj.BASE_AMT);

                    crates.Add(c);
                    return crates;
                }
                else { return mctrCompRates; }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.mctrCompRatescmponCdPostTextItem" + e.Message);
                throw e;
        }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrCompRatespoolOutputPostChange
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public IEnumerable<MctrCompRates> mctrCompRatespoolOutputPostChange(IEnumerable<MctrCompRates> mctrCompRates)
        {
            logger.Debug("Executing mctrCompRatespoolOutputPostChange with input : " + mctrCompRates);
            try
            {
                OracleParameter[] parameter1 = new OracleParameter[3];
            
                obj = mctrCompRates.First<MctrCompRates>();
                StringBuilder query = new StringBuilder("select rsc_pool as rate_i_rsc_pool, rate as rate_i  from  mctr_incr_rates where cmpon_cd = :0 and fiscal_year = :1 and rsc_pool =:2");
                parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, obj.CMPON_CD, ParameterDirection.Input);
                parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int64, obj.FISCAL_YEAR, ParameterDirection.Input);
                parameter1[2] = new OracleParameter(":rsc_pool", OracleDbType.Varchar2, obj.POOL_OUTPUT, ParameterDirection.Input);

                var resultlist = entities.Database.SqlQuery<MctrCompRates>(query.ToString(), parameter1).ToList<MctrCompRates>();

                if (resultlist.Count != 0)
                {
                    List<MctrCompRates> crates = new List<MctrCompRates>();
                    var c = resultlist.First<MctrCompRates>();
                    // c.RATE_OUTPUT = c.RATE_I * (obj.BASE_AMT + obj.RATE_1 + obj.RATE_2 + obj.RATE_3 + obj.RATE_4 + obj.RATE_5 + obj.RATE_6 + obj.RATE_7 + obj.RATE_8);
                    c.RATE_OUTPUT = c.RATE_I * (obj.BASE_AMT);

                    crates.Add(c);
                    return crates;
                }
                else { return mctrCompRates; }
            }
            catch (Exception e)
            {

                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.mctrCompRatescmponCdPostTextItem" + e.Message);
                throw e; }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrCompRatescascadeFlgWhenMouseClick
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public IEnumerable<MctrCompRates> mctrCompRatescascadeFlgWhenMouseClick(IEnumerable<MctrCompRates> mctrCompRates)
        {
            logger.Debug("Executing mctrCompRatescascadeFlgWhenMouseClick with input : " + mctrCompRates);
            try {
            OracleParameter[] parameters = new OracleParameter[10];
            var obj = mctrCompRates.First<MctrCompRates>();

            updateCompRates(obj.CMPON_CD, obj.FISCAL_YEAR, obj.RSC_INPUT, obj.RSC_OUTPUT, obj.POOL_OUTPUT, obj.CUST_TYPE_INPUT, obj.BUM_INPUT, obj.COMP_SEQ, obj.RATE_OUTPUT);

            return mctrCompRates;
        }
            catch(Exception e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.mctrCompRatescascadeFlgWhenMouseClick" + e.Message);
                throw e;
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrCompRatesKeyDelrec
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public IEnumerable<MctrCompRates> mctrCompRatesKeyDelrec(IEnumerable<MctrCompRates> mctrCompRates)
        {
            logger.Debug("Executing mctrCompRatesKeyDelrec with input : " + mctrCompRates);
            try {
                OracleParameter[] parameter1 = new OracleParameter[8];
            StringBuilder query = new StringBuilder("select count (*)  from mctr_comp_rates where cmpon_cd = :0 and fiscal_year = :1 and rsc_input = :2 and rate_1_rsc_pool = :5 || '-' || :6 || '-' || :3 || '-' || :4 || '-' || :7");
            parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, obj.CMPON_CD, ParameterDirection.Input);
            parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int64, obj.FISCAL_YEAR, ParameterDirection.Input);
            parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, obj.RSC_INPUT, ParameterDirection.Input);
            parameter1[3] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, obj.CUST_TYPE_INPUT, ParameterDirection.Input);
            parameter1[4] = new OracleParameter(":bum_input", OracleDbType.Varchar2, obj.BUM_INPUT, ParameterDirection.Input);
            parameter1[5] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, obj.RSC_OUTPUT, ParameterDirection.Input);
            parameter1[6] = new OracleParameter(":pool_output", OracleDbType.Varchar2, obj.POOL_OUTPUT, ParameterDirection.Input);
            parameter1[7] = new OracleParameter(":comp_seq", OracleDbType.Int64, obj.COMP_SEQ, ParameterDirection.Input);

            int count = entities.Database.SqlQuery<int>(query.ToString(), parameter1).Single<int>();

            if (count > 0)
            {

                //message("error - this rate is used in another. delete not allowed.")
                throw new Exception("error - this rate is used in another. delete not allowed");
            }

            else
            {

                //delete_record
            }

            return null;
        }
            catch(Exception e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.mctrCompRatesKeyDelrec" + e.Message);
                throw e;
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : selectBlockbutCopyWhenButtonPressed
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public IEnumerable<MctrCompRates> selectBlockbutCopyWhenButtonPressed(IEnumerable<MctrCompRates> mctrCompRates)
        {
            logger.Debug("Executing selectBlockbutCopyWhenButtonPressed with input : " + mctrCompRates);
            
            OracleParameter[] parameter1 = new OracleParameter[3];
           
            var obj = mctrCompRates.First<MctrCompRates>();
            obj.Count = new Dictionary<string, int?>();
            obj.Count.Clear();

            int? v_lbr_from_flg = null;
            int? v_lbr_to_flg = null;

            Double? v_new_i_rate = 0;

            Double? v_rate_output = null;


            StringBuilder query = new StringBuilder("select count (*)  from mctr_incr_rates where cmpon_cd = :copy_from_bu and fiscal_year = :copy_from_yr and rsc_pool = :copy_from_pl_rsc");
            parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, obj.copy_from_bu.ToUpper(), ParameterDirection.Input);
            parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int64, obj.copy_from_yr, ParameterDirection.Input);
            parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, obj.copy_from_pl_rsc.ToUpper(), ParameterDirection.Input);

            try
            {
                v_lbr_from_flg = entities.Database.SqlQuery<int>(query.ToString(), parameter1).Single<int>();
                obj.Count.Add("v_lbr_from_flg", v_lbr_from_flg);
            }
            catch (Exception e)
            {

                obj.Count.Add("v_lbr_from_flg", 0);
                logger.Error("Error from MCTR.DataAccess.LineItemRepository.mctrLineItemPostQuery" + e.Message);

            }

            //if (v_lbr_from_flg == 0)
            //{

            //    throw new Exception(" incremental rate labor rsc does not exist for the copy from.");
            //}

            StringBuilder query1 = new StringBuilder("select count (*)  from mctr_incr_rates where cmpon_cd = :copy_to_bu and fiscal_year = :copy_to_yr and rsc_pool = :copy_to_pl_rsc");
            parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, obj.copy_to_bu.ToUpper(), ParameterDirection.Input);
            parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int64, obj.copy_to_yr, ParameterDirection.Input);
            parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, obj.copy_to_pl_rsc.ToUpper(), ParameterDirection.Input);

            try
            {
                v_lbr_to_flg = entities.Database.SqlQuery<int>(query.ToString(), parameter1).Single<int>();
                obj.Count.Add("v_lbr_to_flg", v_lbr_to_flg);
            }
            catch (Exception e)
            {

                obj.Count.Add("v_lbr_to_flg", 0);
                logger.Error("Error from MCTR.DataAccess.LineItemRepository.mctrLineItemPostQuery" + e.Message);

            }


            //if (v_lbr_to_flg == 0)
            //{

            //    throw new Exception(" incremental rate labor rsc does not exist for the copy to.");
            //}

            if (obj.v_same == "n" & v_lbr_from_flg > 0 & v_lbr_to_flg > 0)
            {

                // cursor  c_copy_from

           StringBuilder query2 = new StringBuilder("select cmpon_cd, fiscal_year, rsc_input, cust_type_input, bum_input, rsc_output, pool_output, comp_seq, rate_i_rsc_pool, incl_base, base_amt, rate_1_rsc_pool, rate_2_rsc_pool, rate_3_rsc_pool, rate_4_rsc_pool, rate_5_rsc_pool, rate_6_rsc_pool, rate_7_rsc_pool, rate_8_rsc_pool, rate_9_rsc_pool, rate_override from mctr_comp_rates where cmpon_cd = :copy_from_bu and fiscal_year = :copy_from_yr and rsc_input = :copy_from_pl_rsc");
            parameter1[0] = new OracleParameter(":copy_from_bu", OracleDbType.Varchar2, obj.copy_from_bu.ToUpper(), ParameterDirection.Input);
            parameter1[1] = new OracleParameter(":copy_from_yr", OracleDbType.Int64, obj.copy_from_yr, ParameterDirection.Input);
            parameter1[2] = new OracleParameter(":copy_from_pl_rsc", OracleDbType.Varchar2, obj.copy_from_pl_rsc.ToUpper(), ParameterDirection.Input);

            var result = entities.Database.SqlQuery<MctrCompRates>(query2.ToString(), parameter1).ToList<MctrCompRates>();
                    foreach (var loop in result)
                    {
                        if (loop.RATE_I_RSC_POOL == obj.copy_from_pl_rsc)
                        {
                            loop.RATE_I_RSC_POOL = obj.copy_to_pl_rsc;
                        }


                        StringBuilder query3 = new StringBuilder("select rate  from mctr_incr_rates where cmpon_cd = :copy_to_bu and fiscal_year = :copy_to_yr and rsc_pool =:2");

                        OracleParameter[] parameter2 = new OracleParameter[3];
                        parameter2[0] = new OracleParameter(":copy_to_bu", OracleDbType.Varchar2, obj.copy_from_bu.ToUpper(), ParameterDirection.Input);
                        parameter2[1] = new OracleParameter(":copy_to_yr", OracleDbType.Int64, obj.copy_from_yr, ParameterDirection.Input);
                        parameter2[2] = new OracleParameter(":copy_to_yr", OracleDbType.Double, Convert.ToDouble(loop.RATE_I_RSC_POOL), ParameterDirection.Input);
                        try
                        {
                        v_new_i_rate = entities.Database.SqlQuery<Double>(query2.ToString(), parameter2).SingleOrDefault<Double>();
                        }
                        catch (Exception e)
                        {
                            v_new_i_rate = 0;
                            logger.Error("Error from MCTR.DataAccess.LineItemRepository.mctrLineItemPostQuery" + e.Message);

                        }

                        v_rate_output = (v_new_i_rate) * (loop.BASE_AMT);

                       if (loop.RSC_OUTPUT == obj.copy_from_pl_rsc)
                       {
                        loop.RSC_OUTPUT = obj.copy_to_pl_rsc;
                       }

                      if (loop.POOL_OUTPUT == obj.copy_from_pl_rsc)
                        {
                        loop.POOL_OUTPUT = obj.copy_to_pl_rsc;
                        }


                    //            c_rate_1_rsc_pool:=
                    //replace(c_rate_1_rsc_pool, :copy_from_lbr_rsc || '-', :copy_to_lbr_rsc || '-');

                    //            c_rate_1_rsc_pool:=
                    //             replace(c_rate_1_rsc_pool, '-' || :copy_from_pl_rsc || '-', '-' || :copy_to_pl_rsc || '-');

                    //            c_rate_2_rsc_pool:=
                    //             replace(c_rate_2_rsc_pool, :copy_from_lbr_rsc || '-', :copy_to_lbr_rsc || '-');
                    //            c_rate_2_rsc_pool:=
                    //             replace(c_rate_2_rsc_pool, '-' || :copy_from_pl_rsc || '-', '-' || :copy_to_pl_rsc || '-');

                    //            c_rate_3_rsc_pool:=
                    //             replace(c_rate_3_rsc_pool, :copy_from_lbr_rsc || '-', :copy_to_lbr_rsc || '-');
                    //            c_rate_3_rsc_pool:=
                    //             replace(c_rate_3_rsc_pool, '-' || :copy_from_pl_rsc || '-', '-' || :copy_to_pl_rsc || '-');

                    //            c_rate_4_rsc_pool:=
                    //             replace(c_rate_4_rsc_pool, :copy_from_lbr_rsc || '-', :copy_to_lbr_rsc || '-');
                    //            c_rate_4_rsc_pool:=
                    //             replace(c_rate_4_rsc_pool, '-' || :copy_from_pl_rsc || '-', '-' || :copy_to_pl_rsc || '-');

                    //            c_rate_5_rsc_pool:=
                    //             replace(c_rate_5_rsc_pool, :copy_from_lbr_rsc || '-', :copy_to_lbr_rsc || '-');
                    //            c_rate_5_rsc_pool:=
                    //             replace(c_rate_5_rsc_pool, '-' || :copy_from_pl_rsc || '-', '-' || :copy_to_pl_rsc || '-');

                    //            c_rate_6_rsc_pool:=
                    //             replace(c_rate_6_rsc_pool, :copy_from_lbr_rsc || '-', :copy_to_lbr_rsc || '-');
                    //            c_rate_6_rsc_pool:=
                    //             replace(c_rate_6_rsc_pool, '-' || :copy_from_pl_rsc || '-', '-' || :copy_to_pl_rsc || '-');

                    //            c_rate_7_rsc_pool:=
                    //             replace(c_rate_7_rsc_pool, :copy_from_lbr_rsc || '-', :copy_to_lbr_rsc || '-');
                    //            c_rate_7_rsc_pool:=
                    //             replace(c_rate_7_rsc_pool, '-' || :copy_from_pl_rsc || '-', '-' || :copy_to_pl_rsc || '-');

                    //            c_rate_8_rsc_pool:=
                    //             replace(c_rate_8_rsc_pool, :copy_from_lbr_rsc || '-', :copy_to_lbr_rsc || '-');
                    //            c_rate_8_rsc_pool:=
                    //             replace(c_rate_8_rsc_pool, '-' || :copy_from_pl_rsc || '-', '-' || :copy_to_pl_rsc || '-');

                    //            c_rate_9_rsc_pool:=
                    //             replace(c_rate_9_rsc_pool, :copy_from_lbr_rsc || '-', :copy_to_lbr_rsc || '-');
                    //            c_rate_9_rsc_pool:=
                    //             replace(c_rate_9_rsc_pool, '-' || :copy_from_pl_rsc || '-', '-' || :copy_to_pl_rsc || '-');

                    try
                    {
                        StringBuilder query4 = new StringBuilder("insert into mctr_comp_rates values ( :0 , :1 , :2 , loop.CUST_TYPE_INPUT , loop.BUM_INPUT,loop.RSC_OUTPUT , loop.POOL_OUTPUT , loop.COMP_SEQ ,v_rate_output,  loop.RATE_I_RSC_POOL ,v_new_i_rate,loop.INCL_BASE,loop.BASE_AMT,0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 'cascade' , loop.loop.RATE_OVERRIDE");
                        parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, obj.copy_to_bu.ToUpper(), ParameterDirection.Input);
                        parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int64, obj.copy_to_yr, ParameterDirection.Input);
                        parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, obj.copy_to_pl_rsc.ToUpper(), ParameterDirection.Input);
                        int result3 = entities.Database.ExecuteSqlCommand("BEGIN " + query4.ToString() + " END;");
                    }

                    catch(Exception e)
                    {
                        logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.selectBlockbutCopyWhenButtonPressed" + e.Message);
                        throw e;
                    }
                  }
                }
            
            //message('copy complete')
            return mctrCompRates;
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrCompRatesWhenNewFormInstance
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public IEnumerable<MctrCompRates> mctrCompRatesWhenNewFormInstance(IEnumerable<MctrCompRates> mctrCompRates)
        {
           
            try
            {
            List<MctrCompRates> ra = new List<MctrCompRates>();

            MctrCompRates a = new MctrCompRates();

             

            string sqlstmt2 = "select max(fiscal_year) from mctr_lbr_rate";

            int f_year = entities.Database.SqlQuery<int>(sqlstmt2).Single<int>();

            a.f_year = f_year;

            logger.Debug("Response received from  MCTR.DataAccess.MctrIncrRatesRepository.mctrIncrRatesWhenNewFormInstance with input : ");

            ra.Add(a);
            return ra;
        }
            catch(Exception e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.mctrCompRatesWhenNewFormInstance" + e.Message);
                throw e;
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : getrgrateilov
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public IEnumerable<MctrCompRates> getrgrateilov(IEnumerable<MctrCompRates> mctrCompRates)
        {
            logger.Debug("Executing MCTR.DataAccess.MctrIncrRatesRepository.mctrIncrRatesWhenNewFormInstance with input : ");
            try
            {
            OracleParameter[] parameter = new OracleParameter[2];

            obj = mctrCompRates.First<MctrCompRates>();
            StringBuilder query = new StringBuilder("select cmpon_cd , fiscal_year , rsc_pool as RATE_I_RSC_POOL, rate as RATE_I from mctr_incr_rates where cmpon_cd = :0 and fiscal_year = : 1");

            parameter[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, obj.CMPON_CD, ParameterDirection.Input);
            parameter[1] = new OracleParameter(":fiscal_year", OracleDbType.Int64, obj.FISCAL_YEAR, ParameterDirection.Input);
            var resultlist = entities.Database.SqlQuery<MctrCompRates>(query.ToString(), parameter).ToList<MctrCompRates>();
            return resultlist;
            }
            catch(Exception e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.getrgrateilov" + e.Message);
                throw e;
            }

        }


        ///*************************************************************
        ///<summary>
        ///Method Name : getrgrateclov
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public IEnumerable<MctrCompRates> getrgrateclov(IEnumerable<MctrCompRates> mctrCompRates)
        {
            logger.Debug("Executing MCTR.DataAccess.MctrIncrRatesRepository.getrgrateclov with input : ");
            try
            {
            OracleParameter[] parameter = new OracleParameter[7];
            StringBuilder query = new StringBuilder("select cmpon_cd , fiscal_year , rsc_input , rsc_output || '-' || pool_output || '-' || cust_type_input || '-' || bum_input || '-' || comp_seq comp_key , rate_output , rsc_output , pool_output , cust_type_input , bum_input , comp_seq from mctr_comp_rates where cmpon_cd = :0 and fiscal_year = :1 and rsc_input = : 2 and ( rsc_output != : 3 or pool_output != :4 or cust_type_input != :5 or bum_input != :6) and ( cust_type_input = :5 or cust_type_input = 'nl' ) and ( bum_input = :6 or bum_input = 'nl' ) union select null , null , null , null , 0 , null , null , null , null , null from dual order by 4");

            parameter[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, obj.CMPON_CD, ParameterDirection.Input);
            parameter[1] = new OracleParameter(":fiscal_year", OracleDbType.Int64, obj.FISCAL_YEAR, ParameterDirection.Input);
            parameter[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, obj.RSC_INPUT, ParameterDirection.Input);
            parameter[3] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, obj.RSC_OUTPUT, ParameterDirection.Input);
            parameter[4] = new OracleParameter(":pool_output", OracleDbType.Varchar2, obj.POOL_OUTPUT, ParameterDirection.Input);
            parameter[5] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, obj.CUST_TYPE_INPUT, ParameterDirection.Input);
            parameter[6] = new OracleParameter(":bum_input", OracleDbType.Varchar2, obj.BUM_INPUT, ParameterDirection.Input);

            var resultlist = entities.Database.SqlQuery<MctrCompRates>(query.ToString(), parameter).ToList<MctrCompRates>();
            return resultlist;
            }
            catch(Exception e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.getrgrateclov" + e.Message);
                throw e;
            }

        }

        ///*************************************************************
        ///<summary>
        ///Method Name : crtetbl
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        // cursor for download to excel
        ///  -- download pulled data to excel file.
        public IEnumerable<MctrCompRates> crtetbl(IEnumerable<MctrCompRates> mctrCompRates)
        {
            logger.Debug("Executing MCTR.DataAccess.MctrIncrRatesRepository.crtetbl with input : ");
            try
            {
            OracleParameter[] parameter = new OracleParameter[1];
            obj = mctrCompRates.First<MctrCompRates>();
            StringBuilder query = new StringBuilder("select cmpon_cd , fiscal_year , rsc_input , bum_input , rsc_output , pool_output , comp_seq , rate_i_rsc_pool ,rate_i as rate from mctr_owner. mctr_comp_rates where (fiscal_year = :0 and :0 is not null)");
            parameter[0] = new OracleParameter(":0", OracleDbType.Int64, obj.fyear, ParameterDirection.Input);

            var resultlist = entities.Database.SqlQuery<MctrCompRates>(query.ToString(), parameter).ToList<MctrCompRates>();
            return resultlist;
        }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.getrgrateclov" + e.Message);
                throw e;
            }
        }


        ///*************************************************************
        ///<summary>
        ///Method Name : updateCompRates
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public void updateCompRates(string bu, int fyear, string rscinput, string rscoutput, string pooloutput, string custtypeinput, string buminput, int compseq, Decimal? rateoutput)

        {
            logger.Debug("Executing MCTR.DataAccess.MctrIncrRatesRepository.updateCompRates with input : ");
            try
            {

                OracleParameter[] parameter1 = new OracleParameter[8];

                OracleParameter[] parameter2 = new OracleParameter[10];

                string query;
                Decimal? v_comp_rate;

                // cursors

                string sqlstmt = "select rsc_output, pool_output, cust_type_input, bum_input, comp_seq from mctr_comp_rates where cmpon_cd =:0 and fiscal_year =:1 and rsc_input =:2 and";
                string sqlstmt1 = sqlstmt + " rate_1_rsc_pool = :3 || '-' || :4 || '-' || :5 || '-' || :6 || '-' || :7";


                string sqlstmt2 = sqlstmt + " rate_2_rsc_pool = :3 || '-' || :4 || '-' || :5 || '-' || :6 || '-' || :7";
                string sqlstmt3 = sqlstmt + " rate_3_rsc_pool = :3 || '-' || :4 || '-' || :5 || '-' || :6 || '-' || :7";
                string sqlstmt4 = sqlstmt + " rate_4_rsc_pool = :3 || '-' || :4 || '-' || :5 || '-' || :6 || '-' || :7";
                string sqlstmt5 = sqlstmt + " rate_5_rsc_pool = :3 || '-' || :4 || '-' || :5 || '-' || :6 || '-' || :7";
                string sqlstmt6 = sqlstmt + " rate_6_rsc_pool = :3 || '-' || :4 || '-' || :5 || '-' || :6 || '-' || :7";
                string sqlstmt7 = sqlstmt + " rate_7_rsc_pool = :3 || '-' || :4 || '-' || :5 || '-' || :6 || '-' || :7";
                string sqlstmt8 = sqlstmt + " rate_8_rsc_pool = :3 || '-' || :4 || '-' || :5 || '-' || :6 || '-' || :7";
                string sqlstmt9 = sqlstmt + " rate_9_rsc_pool = :3 || '-' || :4 || '-' || :5 || '-' || :6 || '-' || :7";


                parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                parameter1[3] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, rscoutput, ParameterDirection.Input);
                parameter1[4] = new OracleParameter(":pool_output", OracleDbType.Varchar2, pooloutput, ParameterDirection.Input);
                parameter1[5] = new OracleParameter(":p_ct_i", OracleDbType.Varchar2, custtypeinput, ParameterDirection.Input);
                parameter1[6] = new OracleParameter(":p_bum_i", OracleDbType.Varchar2, buminput, ParameterDirection.Input);
                parameter1[7] = new OracleParameter(":p_seq", OracleDbType.Int32, compseq, ParameterDirection.Input);


                var resultlist1 = entities.Database.SqlQuery<MctrCompRates>(sqlstmt1, parameter1).ToList<MctrCompRates>();

                foreach (var b in resultlist1)
                {

                    string smt1 = "select rate_i , base_amt , rate_2 , rate_3 , rate_4 , rate_5 , rate_6 , rate_7 , rate_8 , rate_9  from mctr_comp_rates where cmpon_cd =:0 and fiscal_year = :1 and rsc_input =:2 and rsc_output =:3 and pool_output =:4 and cust_type_input = :5 and bum_input = :6 and comp_seq = :7";

                    parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter1[3] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter1[4] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);
                    parameter1[5] = new OracleParameter(":p_ct_i", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter1[6] = new OracleParameter(":p_bum_i", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter1[7] = new OracleParameter(":p_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);

                    var result = entities.Database.SqlQuery<MctrCompRates>(smt1, parameter2).ToList<MctrCompRates>();

                    var c = result.First<MctrCompRates>();


                    v_comp_rate = (Decimal)((c.RATE_I) * (c.BASE_AMT + rateoutput + c.RATE_2 + c.RATE_3 + c.RATE_4 + c.RATE_5 + c.RATE_6 + c.RATE_7 + c.RATE_8 + c.RATE_9));

                    query = "UPDATE MCTR_COMP_RATES  SET rate_1=:0, rate_output=:1 where (cmpon_cd = :2 and fiscal_year =:3 and rsc_input=:4 and cust_type_input = :5 and bum_input = :6 and  comp_seq = :7 and rsc_output = :8 and pool_output = :9 )";

                    parameter2[0] = new OracleParameter(":rate_1", OracleDbType.Double, rateoutput, ParameterDirection.Input);
                    parameter2[1] = new OracleParameter(":rate_output", OracleDbType.Double, v_comp_rate, ParameterDirection.Input);
                    parameter2[2] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter2[3] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter2[4] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter2[5] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter2[6] = new OracleParameter(":bum_input", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter2[7] = new OracleParameter(":comp_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);
                    parameter2[8] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter2[9] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);

                    entities.Database.ExecuteSqlCommand("BEGIN " + query + " END;", parameter2);
                    updateCompRates(bu, fyear, rscinput, b.RSC_OUTPUT, b.POOL_OUTPUT, b.CUST_TYPE_INPUT, b.BUM_INPUT, b.COMP_SEQ, v_comp_rate);
                }

                var resultlist2 = entities.Database.SqlQuery<MctrCompRates>(sqlstmt2, parameter1).ToList<MctrCompRates>();
                foreach (var b in resultlist2)
                {

                    string smt1 = "select rate_i , base_amt , rate_1 , rate_3 , rate_4 , rate_5 , rate_6 , rate_7 , rate_8 , rate_9  from mctr_comp_rates where cmpon_cd =:0 and fiscal_year = :1 and rsc_input =:2 and rsc_output =:3 and pool_output =:4 and cust_type_input = :5 and bum_input = :6 and comp_seq = :7";

                    parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter1[3] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter1[4] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);
                    parameter1[5] = new OracleParameter(":p_ct_i", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter1[6] = new OracleParameter(":p_bum_i", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter1[7] = new OracleParameter(":p_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);

                    var result = entities.Database.SqlQuery<MctrCompRates>(smt1, parameter2).ToList<MctrCompRates>();

                    var c = result.First<MctrCompRates>();

                    v_comp_rate = (Decimal)((c.RATE_I) * (c.BASE_AMT + rateoutput + c.RATE_1 + c.RATE_3 + c.RATE_4 + c.RATE_5 + c.RATE_6 + c.RATE_7 + c.RATE_8 + c.RATE_9));

                    query = "UPDATE MCTR_COMP_RATES  SET rate_2=:0, rate_output=:1 where (cmpon_cd = :2 and fiscal_year =:3 and rsc_input=:4 and cust_type_input = :5 and bum_input = :6 and  comp_seq = :7 and rsc_output = :8 and pool_output = :9 )";

                    parameter2[0] = new OracleParameter(":rate_2", OracleDbType.Double, rateoutput, ParameterDirection.Input);
                    parameter2[1] = new OracleParameter(":rate_output", OracleDbType.Double, v_comp_rate, ParameterDirection.Input);
                    parameter2[2] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter2[3] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter2[4] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter2[5] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter2[6] = new OracleParameter(":bum_input", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter2[7] = new OracleParameter(":comp_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);
                    parameter2[8] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter2[9] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);

                    entities.Database.ExecuteSqlCommand("BEGIN " + query + " END;", parameter2);
                    updateCompRates(bu, fyear, rscinput, b.RSC_OUTPUT, b.POOL_OUTPUT, b.CUST_TYPE_INPUT, b.BUM_INPUT, b.COMP_SEQ, v_comp_rate);
                }


                var resultlist3 = entities.Database.SqlQuery<MctrCompRates>(sqlstmt3, parameter1).ToList<MctrCompRates>();
                foreach (var b in resultlist3)
                {

                    string smt1 = "select rate_i , base_amt , rate_1 , rate_2 , rate_4 , rate_5 , rate_6 , rate_7 , rate_8 , rate_9  from mctr_comp_rates where cmpon_cd =:0 and fiscal_year = :1 and rsc_input =:2 and rsc_output =:3 and pool_output =:4 and cust_type_input = :5 and bum_input = :6 and comp_seq = :7";

                    parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter1[3] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter1[4] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);
                    parameter1[5] = new OracleParameter(":p_ct_i", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter1[6] = new OracleParameter(":p_bum_i", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter1[7] = new OracleParameter(":p_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);

                    var result = entities.Database.SqlQuery<MctrCompRates>(smt1, parameter2).ToList<MctrCompRates>();

                    var c = result.First<MctrCompRates>();

                    v_comp_rate = (Decimal)((c.RATE_I) * (c.BASE_AMT + rateoutput + c.RATE_1 + c.RATE_2 + c.RATE_4 + c.RATE_5 + c.RATE_6 + c.RATE_7 + c.RATE_8 + c.RATE_9));

                    query = "UPDATE MCTR_COMP_RATES  SET rate_3=:0, rate_output=:1 where (cmpon_cd = :2 and fiscal_year =:3 and rsc_input=:4 and cust_type_input = :5 and bum_input = :6 and  comp_seq = :7 and rsc_output = :8 and pool_output = :9 )";

                    parameter2[0] = new OracleParameter(":rate_3", OracleDbType.Double, rateoutput, ParameterDirection.Input);
                    parameter2[1] = new OracleParameter(":rate_output", OracleDbType.Double, v_comp_rate, ParameterDirection.Input);
                    parameter2[2] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter2[3] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter2[4] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter2[5] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter2[6] = new OracleParameter(":bum_input", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter2[7] = new OracleParameter(":comp_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);
                    parameter2[8] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter2[9] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);

                    entities.Database.ExecuteSqlCommand("BEGIN " + query + " END;", parameter2);
                    updateCompRates(bu, fyear, rscinput, b.RSC_OUTPUT, b.POOL_OUTPUT, b.CUST_TYPE_INPUT, b.BUM_INPUT, b.COMP_SEQ, v_comp_rate);
                }
                var resultlist4 = entities.Database.SqlQuery<MctrCompRates>(sqlstmt4, parameter1).ToList<MctrCompRates>();
                foreach (var b in resultlist4)
                {

                    string smt1 = "select rate_i , base_amt , rate_1 , rate_2,rate_3 , rate_5 , rate_6 , rate_7 , rate_8 , rate_9  from mctr_comp_rates where cmpon_cd =:0 and fiscal_year = :1 and rsc_input =:2 and rsc_output =:3 and pool_output =:4 and cust_type_input = :5 and bum_input = :6 and comp_seq = :7";

                    parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter1[3] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter1[4] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);
                    parameter1[5] = new OracleParameter(":p_ct_i", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter1[6] = new OracleParameter(":p_bum_i", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter1[7] = new OracleParameter(":p_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);

                    var result = entities.Database.SqlQuery<MctrCompRates>(smt1, parameter2).ToList<MctrCompRates>();

                    var c = result.First<MctrCompRates>();

                    v_comp_rate = (Decimal)((c.RATE_I) * (c.BASE_AMT + rateoutput + c.RATE_1 + +c.RATE_2 + c.RATE_3 + c.RATE_5 + c.RATE_6 + c.RATE_7 + c.RATE_8 + c.RATE_9));

                    query = "UPDATE MCTR_COMP_RATES  SET rate_4=:0, rate_output=:1 where (cmpon_cd = :2 and fiscal_year =:3 and rsc_input=:4 and cust_type_input = :5 and bum_input = :6 and  comp_seq = :7 and rsc_output = :8 and pool_output = :9 )";

                    parameter2[0] = new OracleParameter(":rate_4", OracleDbType.Double, rateoutput, ParameterDirection.Input);
                    parameter2[1] = new OracleParameter(":rate_output", OracleDbType.Double, v_comp_rate, ParameterDirection.Input);
                    parameter2[2] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter2[3] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter2[4] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter2[5] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter2[6] = new OracleParameter(":bum_input", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter2[7] = new OracleParameter(":comp_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);
                    parameter2[8] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter2[9] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);

                    entities.Database.ExecuteSqlCommand("BEGIN " + query + " END;", parameter2);
                    updateCompRates(bu, fyear, rscinput, b.RSC_OUTPUT, b.POOL_OUTPUT, b.CUST_TYPE_INPUT, b.BUM_INPUT, b.COMP_SEQ, v_comp_rate);
                }
                var resultlist5 = entities.Database.SqlQuery<MctrCompRates>(sqlstmt5, parameter1).ToList<MctrCompRates>();
                foreach (var b in resultlist5)
                {

                    string smt1 = "select rate_i , base_amt , rate_1 , rate_2,rate_3 , rate_4 , rate_6 , rate_7 , rate_8 , rate_9  from mctr_comp_rates where cmpon_cd =:0 and fiscal_year = :1 and rsc_input =:2 and rsc_output =:3 and pool_output =:4 and cust_type_input = :5 and bum_input = :6 and comp_seq = :7";

                    parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter1[3] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter1[4] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);
                    parameter1[5] = new OracleParameter(":p_ct_i", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter1[6] = new OracleParameter(":p_bum_i", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter1[7] = new OracleParameter(":p_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);

                    var result = entities.Database.SqlQuery<MctrCompRates>(smt1, parameter2).ToList<MctrCompRates>();

                    var c = result.First<MctrCompRates>();

                    v_comp_rate = (Decimal)((c.RATE_I) * (c.BASE_AMT + rateoutput + c.RATE_1 + +c.RATE_2 + c.RATE_3 + c.RATE_4 + c.RATE_6 + c.RATE_7 + c.RATE_8 + c.RATE_9));

                    query = "UPDATE MCTR_COMP_RATES  SET rate_5=:0, rate_output=:1 where (cmpon_cd = :2 and fiscal_year =:3 and rsc_input=:4 and cust_type_input = :5 and bum_input = :6 and  comp_seq = :7 and rsc_output = :8 and pool_output = :9 )";

                    parameter2[0] = new OracleParameter(":rate_5", OracleDbType.Double, rateoutput, ParameterDirection.Input);
                    parameter2[1] = new OracleParameter(":rate_output", OracleDbType.Double, v_comp_rate, ParameterDirection.Input);
                    parameter2[2] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter2[3] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter2[4] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter2[5] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter2[6] = new OracleParameter(":bum_input", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter2[7] = new OracleParameter(":comp_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);
                    parameter2[8] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter2[9] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);

                    entities.Database.ExecuteSqlCommand("BEGIN " + query + " END;", parameter2);
                    updateCompRates(bu, fyear, rscinput, b.RSC_OUTPUT, b.POOL_OUTPUT, b.CUST_TYPE_INPUT, b.BUM_INPUT, b.COMP_SEQ, v_comp_rate);
                }
                var resultlist6 = entities.Database.SqlQuery<MctrCompRates>(sqlstmt6, parameter1).ToList<MctrCompRates>();
                foreach (var b in resultlist6)
                {

                    string smt1 = "select rate_i , base_amt , rate_1 , rate_2,rate_3 , rate_4 , rate_5 , rate_7 , rate_8 , rate_9  from mctr_comp_rates where cmpon_cd =:0 and fiscal_year = :1 and rsc_input =:2 and rsc_output =:3 and pool_output =:4 and cust_type_input = :5 and bum_input = :6 and comp_seq = :7";

                    parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter1[3] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter1[4] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);
                    parameter1[5] = new OracleParameter(":p_ct_i", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter1[6] = new OracleParameter(":p_bum_i", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter1[7] = new OracleParameter(":p_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);

                    var result = entities.Database.SqlQuery<MctrCompRates>(smt1, parameter2).ToList<MctrCompRates>();

                    var c = result.First<MctrCompRates>();

                    v_comp_rate = (Decimal)((c.RATE_I) * (c.BASE_AMT + rateoutput + c.RATE_1 + +c.RATE_2 + c.RATE_3 + c.RATE_4 + c.RATE_5 + c.RATE_7 + c.RATE_8 + c.RATE_9));

                    query = "UPDATE MCTR_COMP_RATES  SET rate_6=:0, rate_output=:1 where (cmpon_cd = :2 and fiscal_year =:3 and rsc_input=:4 and cust_type_input = :5 and bum_input = :6 and  comp_seq = :7 and rsc_output = :8 and pool_output = :9 )";

                    parameter2[0] = new OracleParameter(":rate_6", OracleDbType.Double, rateoutput, ParameterDirection.Input);
                    parameter2[1] = new OracleParameter(":rate_output", OracleDbType.Double, v_comp_rate, ParameterDirection.Input);
                    parameter2[2] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter2[3] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter2[4] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter2[5] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter2[6] = new OracleParameter(":bum_input", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter2[7] = new OracleParameter(":comp_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);
                    parameter2[8] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter2[9] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);

                    entities.Database.ExecuteSqlCommand("BEGIN " + query + " END;", parameter2);
                    updateCompRates(bu, fyear, rscinput, b.RSC_OUTPUT, b.POOL_OUTPUT, b.CUST_TYPE_INPUT, b.BUM_INPUT, b.COMP_SEQ, v_comp_rate);
                }
                var resultlist7 = entities.Database.SqlQuery<MctrCompRates>(sqlstmt7, parameter1).ToList<MctrCompRates>();
                foreach (var b in resultlist7)
                {
                    string smt1 = "select rate_i , base_amt , rate_1 , rate_2,rate_3 , rate_4 , rate_5 , rate_6 , rate_8 , rate_9  from mctr_comp_rates where cmpon_cd =:0 and fiscal_year = :1 and rsc_input =:2 and rsc_output =:3 and pool_output =:4 and cust_type_input = :5 and bum_input = :6 and comp_seq = :7";

                    parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter1[3] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter1[4] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);
                    parameter1[5] = new OracleParameter(":p_ct_i", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter1[6] = new OracleParameter(":p_bum_i", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter1[7] = new OracleParameter(":p_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);

                    var result = entities.Database.SqlQuery<MctrCompRates>(smt1, parameter2).ToList<MctrCompRates>();

                    var c = result.First<MctrCompRates>();

                    v_comp_rate = (Decimal)((c.RATE_I) * (c.BASE_AMT + rateoutput + c.RATE_1 + +c.RATE_2 + c.RATE_3 + c.RATE_4 + c.RATE_5 + c.RATE_6 + c.RATE_8 + c.RATE_9));

                    query = "UPDATE MCTR_COMP_RATES  SET rate_7=:0, rate_output=:1 where (cmpon_cd = :2 and fiscal_year =:3 and rsc_input=:4 and cust_type_input = :5 and bum_input = :6 and  comp_seq = :7 and rsc_output = :8 and pool_output = :9 )";

                    parameter2[0] = new OracleParameter(":rate_7", OracleDbType.Double, rateoutput, ParameterDirection.Input);
                    parameter2[1] = new OracleParameter(":rate_output", OracleDbType.Double, v_comp_rate, ParameterDirection.Input);
                    parameter2[2] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter2[3] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter2[4] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter2[5] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter2[6] = new OracleParameter(":bum_input", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter2[7] = new OracleParameter(":comp_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);
                    parameter2[8] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter2[9] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);

                    entities.Database.ExecuteSqlCommand("BEGIN " + query + " END;", parameter2);
                    updateCompRates(bu, fyear, rscinput, b.RSC_OUTPUT, b.POOL_OUTPUT, b.CUST_TYPE_INPUT, b.BUM_INPUT, b.COMP_SEQ, v_comp_rate);
                }
                var resultlist8 = entities.Database.SqlQuery<MctrCompRates>(sqlstmt8, parameter1).ToList<MctrCompRates>();
                foreach (var b in resultlist8)
                {

                    string smt1 = "select rate_i , base_amt , rate_1 , rate_2,rate_3 , rate_4 , rate_5 , rate_6 , rate_7 , rate_9  from mctr_comp_rates where cmpon_cd =:0 and fiscal_year = :1 and rsc_input =:2 and rsc_output =:3 and pool_output =:4 and cust_type_input = :5 and bum_input = :6 and comp_seq = :7";

                    parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter1[3] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter1[4] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);
                    parameter1[5] = new OracleParameter(":p_ct_i", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter1[6] = new OracleParameter(":p_bum_i", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter1[7] = new OracleParameter(":p_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);

                    var result = entities.Database.SqlQuery<MctrCompRates>(smt1, parameter2).ToList<MctrCompRates>();

                    var c = result.First<MctrCompRates>();

                    v_comp_rate = (Decimal)((c.RATE_I) * (c.BASE_AMT + rateoutput + c.RATE_1 + +c.RATE_2 + c.RATE_3 + c.RATE_4 + c.RATE_5 + c.RATE_6 + c.RATE_7 + c.RATE_9));

                    query = "UPDATE MCTR_COMP_RATES  SET rate_8=:0, rate_output=:1 where (cmpon_cd = :2 and fiscal_year =:3 and rsc_input=:4 and cust_type_input = :5 and bum_input = :6 and  comp_seq = :7 and rsc_output = :8 and pool_output = :9 )";

                    parameter2[0] = new OracleParameter(":rate_8", OracleDbType.Double, rateoutput, ParameterDirection.Input);
                    parameter2[1] = new OracleParameter(":rate_output", OracleDbType.Double, v_comp_rate, ParameterDirection.Input);
                    parameter2[2] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter2[3] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter2[4] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter2[5] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter2[6] = new OracleParameter(":bum_input", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter2[7] = new OracleParameter(":comp_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);
                    parameter2[8] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter2[9] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);

                    entities.Database.ExecuteSqlCommand("BEGIN " + query + " END;", parameter2);
                    updateCompRates(bu, fyear, rscinput, b.RSC_OUTPUT, b.POOL_OUTPUT, b.CUST_TYPE_INPUT, b.BUM_INPUT, b.COMP_SEQ, v_comp_rate);
                }

                var resultlist9 = entities.Database.SqlQuery<MctrCompRates>(sqlstmt9, parameter1).ToList<MctrCompRates>();

                foreach (var b in resultlist9)
                {

                    string smt1 = "select rate_i , base_amt , rate_1 , rate_2,rate_3 , rate_4 , rate_5 , rate_6 , rate_7 , rate_8  from mctr_comp_rates where cmpon_cd =:0 and fiscal_year = :1 and rsc_input =:2 and rsc_output =:3 and pool_output =:4 and cust_type_input = :5 and bum_input = :6 and comp_seq = :7";

                    parameter1[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter1[1] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter1[2] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter1[3] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter1[4] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);
                    parameter1[5] = new OracleParameter(":p_ct_i", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter1[6] = new OracleParameter(":p_bum_i", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter1[7] = new OracleParameter(":p_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);

                    var result = entities.Database.SqlQuery<MctrCompRates>(smt1, parameter2).ToList<MctrCompRates>();

                    var c = result.First<MctrCompRates>();

                    v_comp_rate = (Decimal)((c.RATE_I) * (c.BASE_AMT + rateoutput + c.RATE_1 + +c.RATE_2 + c.RATE_3 + c.RATE_4 + c.RATE_5 + c.RATE_6 + c.RATE_7 + c.RATE_8));

                    query = "UPDATE MCTR_COMP_RATES  SET rate_9=:0, rate_output=:1 where (cmpon_cd = :2 and fiscal_year =:3 and rsc_input=:4 and cust_type_input = :5 and bum_input = :6 and  comp_seq = :7 and rsc_output = :8 and pool_output = :9 )";

                    parameter2[0] = new OracleParameter(":rate_9", OracleDbType.Double, rateoutput, ParameterDirection.Input);
                    parameter2[1] = new OracleParameter(":rate_output", OracleDbType.Double, v_comp_rate, ParameterDirection.Input);
                    parameter2[2] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, bu, ParameterDirection.Input);
                    parameter2[3] = new OracleParameter(":fiscal_year", OracleDbType.Int32, fyear, ParameterDirection.Input);
                    parameter2[4] = new OracleParameter(":rsc_input", OracleDbType.Varchar2, rscinput, ParameterDirection.Input);
                    parameter2[5] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, b.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameter2[6] = new OracleParameter(":bum_input", OracleDbType.Varchar2, b.BUM_INPUT, ParameterDirection.Input);
                    parameter2[7] = new OracleParameter(":comp_seq", OracleDbType.Int32, b.COMP_SEQ, ParameterDirection.Input);
                    parameter2[8] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, b.RSC_OUTPUT, ParameterDirection.Input);
                    parameter2[9] = new OracleParameter(":pool_output", OracleDbType.Varchar2, b.POOL_OUTPUT, ParameterDirection.Input);

                    entities.Database.ExecuteSqlCommand("BEGIN " + query + " END;", parameter2);
                    updateCompRates(bu, fyear, rscinput, b.RSC_OUTPUT, b.POOL_OUTPUT, b.CUST_TYPE_INPUT, b.BUM_INPUT, b.COMP_SEQ, v_comp_rate);
                }

                logger.Debug("Response received from  MCTR.DataAccess.MctrIncrRatesRepository.updateCompRates: ");
            }
            catch (OracleException e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrIncrRatesRepository.updateCompRates" + e.Message);

                throw;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrIncrRatesRepository.updateCompRates" + e.Message);

                throw;
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : genericLovCall
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public IEnumerable<MctrCompRates> genericLovCall(IEnumerable<MctrCompRates> mctrCompRates)
        {
            logger.Debug("Executing MCTR.DataAccess.MctrIncrRatesRepository.updateCompRates with input : ");
            try {
            OracleParameter[] parameter = new OracleParameter[9];
            var comprates = mctrCompRates.First<MctrCompRates>();
            string v_check_circular;
            List<MctrCompRates> list = new List<MctrCompRates>();

            //note: v_check_circular caused ora - 06502 numeric error because the length was 14.increase to 16.

            v_check_circular = comprates.RSC_OUTPUT + "-" + comprates.POOL_OUTPUT + "-" + comprates.CUST_TYPE_INPUT + "-" + comprates.BUM_INPUT + "-" + comprates.COMP_SEQ;

            StringBuilder query = new StringBuilder("select count (*)  from mctr_comp_rates where cmpon_cd = :0 and fiscal_year = :1 and rsc_output = : check_rsc and pool_output = : check_pool and cust_type_input = : check_ct and bum_input = : check_bum and comp_seq = : check_seq and (rate_1_rsc_pool = v_check_circular or rate_2_rsc_pool = v_check_circular or rate_3_rsc_pool = v_check_circular or rate_4_rsc_pool = v_check_circular or rate_5_rsc_pool = v_check_circular or rate_6_rsc_pool = v_check_circular or rate_7_rsc_pool = v_check_circular or rate_8_rsc_pool = v_check_circular or rate_9_rsc_pool = v_check_circular ");
            parameter[0] = new OracleParameter(":cmpon_cd", OracleDbType.Varchar2, obj.CMPON_CD, ParameterDirection.Input);
            parameter[1] = new OracleParameter(":fiscal_year", OracleDbType.Int64, obj.FISCAL_YEAR, ParameterDirection.Input);
            parameter[2] = new OracleParameter(":rsc_pool", OracleDbType.Varchar2, obj.POOL_OUTPUT, ParameterDirection.Input);
            parameter[3] = new OracleParameter(":rsc_output", OracleDbType.Varchar2, obj.RSC_OUTPUT, ParameterDirection.Input);
            parameter[4] = new OracleParameter(":pool_output", OracleDbType.Varchar2, obj.POOL_OUTPUT, ParameterDirection.Input);
            parameter[5] = new OracleParameter(":cust_type_input", OracleDbType.Varchar2, obj.CUST_TYPE_INPUT, ParameterDirection.Input);
            parameter[6] = new OracleParameter(":bum_input", OracleDbType.Varchar2, obj.BUM_INPUT, ParameterDirection.Input);
            parameter[7] = new OracleParameter(":comp_seq", OracleDbType.Int64, obj.COMP_SEQ, ParameterDirection.Input);
            parameter[8] = new OracleParameter(":lu.bems", OracleDbType.Varchar2, v_check_circular, ParameterDirection.Input);


            cratedomain.v_count_circular = entities.Database.SqlQuery<int>(query.ToString(), parameter).Single<int>();

            list.Add(cratedomain);
            return list;
        }
            catch(Exception e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrIncrRatesRepository.genericLovCall" + e.Message);

                throw;
            }
        }



        ///*************************************************************
        ///<summary>
        ///Method Name : compositeInsert
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public IEnumerable<MctrCompRates> compositeInsert(IEnumerable<MctrCompRates> mctrCompRates)
        {
            logger.Debug("Executing MCTR.DataAccess.MctrIncrRatesRepository.compositeInsert with input : ");
            try
            {

                MctrCompRates comprates = mctrCompRates.First();
                StringBuilder sql = new StringBuilder();
                
                OracleParameter[] parameters = new OracleParameter[8];
                // SQL: delete from mctr_ovrhd where mctr_no = : mctr_line_item . mctr_no and line_no = : mctr_line_item . line_no
                sql = new StringBuilder("SELECT COUNT(*) FROM MCTR_COMP_RATES WHERE CMPON_CD=:0 AND FISCAL_YEAR=:1 AND RSC_INPUT=:2 AND CUST_TYPE_INPUT=:3 AND BUM_INPUT=:4 AND RSC_OUTPUT=:5 AND POOL_OUTPUT=:6 AND COMP_SEQ=:7");
                parameters[0] = new OracleParameter(":0", OracleDbType.Varchar2, comprates.CMPON_CD, ParameterDirection.Input);
                parameters[1] = new OracleParameter(":1", OracleDbType.Int32, comprates.FISCAL_YEAR, ParameterDirection.Input);
                parameters[2] = new OracleParameter(":2", OracleDbType.Varchar2, comprates.RSC_INPUT, ParameterDirection.Input);
                parameters[3] = new OracleParameter(":3", OracleDbType.Varchar2, comprates.CUST_TYPE_INPUT, ParameterDirection.Input);
                parameters[4] = new OracleParameter(":4", OracleDbType.Varchar2, comprates.BUM_INPUT, ParameterDirection.Input);
                parameters[5] = new OracleParameter(":5", OracleDbType.Varchar2, comprates.RSC_OUTPUT, ParameterDirection.Input);
                parameters[6] = new OracleParameter(":6", OracleDbType.Varchar2, comprates.POOL_OUTPUT, ParameterDirection.Input);
                parameters[7] = new OracleParameter(":7", OracleDbType.Int32, comprates.COMP_SEQ, ParameterDirection.Input);
                var count = entities.Database.SqlQuery<int>(sql.ToString(), parameters).SingleOrDefault();
                if (count == 0)
                {
                    try
                    {

                        // MctrCompRates comprates = mctrCompRates.First();
                        //StringBuilder sql = new StringBuilder();
                        // 
                        // OracleParameter[] 
                        parameters = new OracleParameter[14];
                        sql = new StringBuilder("INSERT INTO MCTR_COMP_RATES (CMPON_CD, FISCAL_YEAR, RSC_INPUT, CUST_TYPE_INPUT, BUM_INPUT, RSC_OUTPUT, POOL_OUTPUT, COMP_SEQ, RATE_OUTPUT, RATE_I_RSC_POOL, RATE_I, INCL_BASE, BASE_AMT,RATE_OVERRIDE) VALUES (:0,:1,:2,:3,:4,:5,:6,:7,:8,:9,:10,:11,:12,:13);");
                        parameters[0] = new OracleParameter(":0", OracleDbType.Varchar2, comprates.CMPON_CD, ParameterDirection.Input);
                        parameters[1] = new OracleParameter(":1", OracleDbType.Int32, comprates.FISCAL_YEAR, ParameterDirection.Input);
                        parameters[2] = new OracleParameter(":2", OracleDbType.Varchar2, comprates.RSC_INPUT, ParameterDirection.Input);
                        parameters[3] = new OracleParameter(":3", OracleDbType.Varchar2, comprates.CUST_TYPE_INPUT, ParameterDirection.Input);
                        parameters[4] = new OracleParameter(":4", OracleDbType.Varchar2, comprates.BUM_INPUT, ParameterDirection.Input);
                        parameters[5] = new OracleParameter(":5", OracleDbType.Varchar2, comprates.RSC_OUTPUT, ParameterDirection.Input);
                        parameters[6] = new OracleParameter(":6", OracleDbType.Varchar2, comprates.POOL_OUTPUT, ParameterDirection.Input);
                        parameters[7] = new OracleParameter(":7", OracleDbType.Int32, comprates.COMP_SEQ, ParameterDirection.Input);
                        parameters[8] = new OracleParameter(":8", OracleDbType.Double, comprates.RATE_OUTPUT, ParameterDirection.Input);
                        parameters[9] = new OracleParameter(":9", OracleDbType.Varchar2, comprates.RATE_I_RSC_POOL, ParameterDirection.Input);
                        parameters[10] = new OracleParameter(":10", OracleDbType.Double, comprates.RATE_I, ParameterDirection.Input);
                        parameters[11] = new OracleParameter(":11", OracleDbType.Varchar2, comprates.INCL_BASE, ParameterDirection.Input);
                        parameters[12] = new OracleParameter(":12", OracleDbType.Int32, comprates.BASE_AMT, ParameterDirection.Input);
                        parameters[13] = new OracleParameter(":13", OracleDbType.Int32, comprates.RATE_OVERRIDE, ParameterDirection.Input);

                        int result = entities.Database.ExecuteSqlCommand("BEGIN " + sql.ToString() + " END;", parameters);
                        return mctrCompRates;
                    }
                    catch (Exception e)
                    {
                        logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.compositeInsert" + e.Message);
                        throw;
                    }
                }

                else
                {


                    //MctrCompRates comprates = mctrCompRates.First();
                    //StringBuilder sql = new StringBuilder();
                    //
                    //OracleParameter[] 
                    parameters = new OracleParameter[14];


                    sql = new StringBuilder("UPDATE MCTR_COMP_RATES SET RATE_OUTPUT=:0,RATE_I_RSC_POOL=:1,RATE_I=:2,INCL_BASE=:3,BASE_AMT=:4,RATE_OVERRIDE=:5 WHERE CMPON_CD=:6 AND FISCAL_YEAR=:7 AND RSC_INPUT=:8 AND CUST_TYPE_INPUT=:9 AND BUM_INPUT=:10 AND RSC_OUTPUT=:11 AND POOL_OUTPUT=:12 AND COMP_SEQ=:13;");
                    // sql = new StringBuilder("UPDATE MCTR_COMP_RATES SET RATE_OVERRIDE=:0 WHERE CMPON_CD=:1 AND FISCAL_YEAR=:2 AND RSC_INPUT=:3 AND CUST_TYPE_INPUT=:4 AND BUM_INPUT=:5 AND RSC_OUTPUT=:6 AND POOL_OUTPUT=:7 AND COMP_SEQ=:8;");


                    parameters[0] = new OracleParameter(":0", OracleDbType.Double, comprates.RATE_OUTPUT, ParameterDirection.Input);
                    parameters[1] = new OracleParameter(":1", OracleDbType.Varchar2, comprates.RATE_I_RSC_POOL, ParameterDirection.Input);
                    parameters[2] = new OracleParameter(":2", OracleDbType.Double, comprates.RATE_I, ParameterDirection.Input);
                    parameters[3] = new OracleParameter(":3", OracleDbType.Varchar2, comprates.INCL_BASE, ParameterDirection.Input);
                    parameters[4] = new OracleParameter(":4", OracleDbType.Int32, comprates.BASE_AMT, ParameterDirection.Input);
                    parameters[5] = new OracleParameter(":5", OracleDbType.Int32, comprates.RATE_OVERRIDE, ParameterDirection.Input);
                    parameters[6] = new OracleParameter(":6", OracleDbType.Varchar2, comprates.CMPON_CD, ParameterDirection.Input);
                    parameters[7] = new OracleParameter(":7", OracleDbType.Int32, comprates.FISCAL_YEAR, ParameterDirection.Input);
                    parameters[8] = new OracleParameter(":8", OracleDbType.Varchar2, comprates.RSC_INPUT, ParameterDirection.Input);
                    parameters[9] = new OracleParameter(":9", OracleDbType.Varchar2, comprates.CUST_TYPE_INPUT, ParameterDirection.Input);
                    parameters[10] = new OracleParameter(":10", OracleDbType.Varchar2, comprates.BUM_INPUT, ParameterDirection.Input);
                    parameters[11] = new OracleParameter(":11", OracleDbType.Varchar2, comprates.RSC_OUTPUT, ParameterDirection.Input);
                    parameters[12] = new OracleParameter(":12", OracleDbType.Varchar2, comprates.POOL_OUTPUT, ParameterDirection.Input);
                    parameters[13] = new OracleParameter(":13", OracleDbType.Int32, comprates.COMP_SEQ, ParameterDirection.Input);



                    int result = entities.Database.ExecuteSqlCommand("BEGIN " + sql.ToString() + " END;", parameters);
                    return mctrCompRates;



                }
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.compositeInsert" + e.Message);
                throw;
            }


        }


        ///*************************************************************
        ///<summary>
        ///Method Name : compositeDelete
        ///</summary>
        ///<param name = "MctrCompRates"></param>
        ///<returns>IEnumerable<MctrCompRates> </returns>

        public IEnumerable<MctrCompRates> compositeDelete(IEnumerable<MctrCompRates> mctrCompRates)
        {
            logger.Debug("Executing MCTR.DataAccess.MctrIncrRatesRepository.compositeDelete with input : ");
            try
            {

                MctrCompRates comprates = mctrCompRates.First();
                StringBuilder sql = new StringBuilder();
                
                OracleParameter[] parameters = new OracleParameter[8];
                // SQL: delete from mctr_ovrhd where mctr_no = : mctr_line_item . mctr_no and line_no = : mctr_line_item . line_no
                sql = new StringBuilder("DELETE FROM MCTR_COMP_RATES WHERE CMPON_CD=:0 AND FISCAL_YEAR=:1 AND RSC_INPUT=:2 AND CUST_TYPE_INPUT=:3 AND BUM_INPUT=:4 AND RSC_OUTPUT =:5 AND POOL_OUTPUT=:6 AND COMP_SEQ = :7;");
                parameters[0] = new OracleParameter(":0", OracleDbType.Varchar2, comprates.CMPON_CD, ParameterDirection.Input);
                parameters[1] = new OracleParameter(":1", OracleDbType.Int32, comprates.FISCAL_YEAR, ParameterDirection.Input);
                parameters[2] = new OracleParameter(":2", OracleDbType.Varchar2, comprates.RSC_INPUT, ParameterDirection.Input);
                parameters[3] = new OracleParameter(":3", OracleDbType.Varchar2, comprates.CUST_TYPE_INPUT, ParameterDirection.Input);
                parameters[4] = new OracleParameter(":4", OracleDbType.Varchar2, comprates.BUM_INPUT, ParameterDirection.Input);
                parameters[5] = new OracleParameter(":5", OracleDbType.Varchar2, comprates.RSC_OUTPUT, ParameterDirection.Input);
                parameters[6] = new OracleParameter(":6", OracleDbType.Varchar2, comprates.POOL_OUTPUT, ParameterDirection.Input);
                parameters[7] = new OracleParameter(":7", OracleDbType.Int32, comprates.COMP_SEQ, ParameterDirection.Input);
                var DeletedStatus = entities.Database.ExecuteSqlCommand("BEGIN " + sql.ToString() + " END;", parameters);
                return mctrCompRates;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.DataAccess.MctrCompRatesRepository.compositeDelete" + e.Message);
                throw;
            }

        }


    }
}
