///*************************************************************************
///
/// BOEING CONFIDENTIAL
/// ___________________
///
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
///
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be
/// covered by U.S. and Foreign Patents, patents in process,
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing.
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :

using log4net;
using MCTR.BusinessInterface;
using MCTR.DataAccess;
using MCTR.DataAccessInterface;
using MCTR.DomainEntity;
using System;
using System.Collections.Generic;

namespace MCTR.Business
{

    public class BuprofileBusiness : BaseBusiness, IBuProfileBusiness
    {
         private readonly ILog logger;
        readonly IBuProfileRepository buProfileObj;
        IEnumerable<BuProfile> response;

        public BuprofileBusiness()
        {
            buProfileObj = new BuProfileRepository();
            response = new List<BuProfile>();
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileBuProfileOnLoad
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>
        public IEnumerable<BuProfile> buProfileBuProfileOnLoad()
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfilebusinessUnitOnLoad : ");
                response = buProfileObj.buProfileBuProfileOnLoad();
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfilebusinessUnitOnLoad :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfilebusinessUnitOnLoad :" + e.Message);
                throw;
            }
            return response;
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilebusinessUnitPreTextItem
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        public IEnumerable<BuProfile> buProfilebusinessUnitPostTextItem(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfilebusinessUnitPostTextItem with input : " + buProfile);
                response = buProfileObj.buProfilebusinessUnitPostTextItem(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfilebusinessUnitPostTextItem :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from from MCTR.Business.BuprofileBusiness.buProfilebusinessUnitPostTextItem :" + e.Message);
                throw;
            }
            return response;
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileBuProfileOnLoad
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>
        public IEnumerable<BuProfile> buProfileoffsetActivityPreTextItem(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfileoffsetActivityPreTextItem with input : " + buProfile);
                response = buProfileObj.buProfileoffsetActivityPreTextItem(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfileoffsetActivityPreTextItem :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfileoffsetActivityPreTextItem :" + e.Message);
                throw;
            }
            return response;
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileBuProfileOnLoad
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        public IEnumerable<BuProfile> buProfileoffsetActivityPostTextItem(IEnumerable<BuProfile> buProfile)
        {
            try
            {

                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfileoffsetActivityPostTextItem with input : " + buProfile);
                response = buProfileObj.buProfileoffsetActivityPostTextItem(buProfile);
                logger.Debug("Response recieved from  MCTR.Business.BuprofileBusiness.buProfileoffsetActivityPostTextItem :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfileoffsetActivityPostTextItem :" + e.Message);
                throw;
            }
            return response;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileBuProfileOnLoad
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        public IEnumerable<BuProfile> buProfileoffsetProjectPreTextItem(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfileoffsetProjectPreTextItem with input : " + buProfile);
                response = buProfileObj.buProfileoffsetProjectPreTextItem(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfileoffsetProjectPreTextItem :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfileoffsetProjectPreTextItem :" + e.Message);
                throw;
            }
            return response;
        }

        public IEnumerable<BuProfile> buProfileoffsetProjectPostTextItem(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfileoffsetProjectPostTextItem with input : " + buProfile);
                response = buProfileObj.buProfileoffsetProjectPostTextItem(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfileoffsetProjectPostTextItem :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfileoffsetProjectPostTextItem :" + e.Message);
                throw;
            }
            return response;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileoffsetAccountPreTextItem
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        public IEnumerable<BuProfile> buProfileoffsetAccountPreTextItem(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfileoffsetAccountPreTextItem with input : " + buProfile);
                response = buProfileObj.buProfileoffsetAccountPreTextItem(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfileoffsetProjectPostTextItem :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfileoffsetProjectPostTextItem  :" + e.Message);
                throw;
            }
            return response;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name :     public IEnumerable<BuProfile> buProfileoffsetAccountPostTextItem(IEnumerable<BuProfile> buProfile)

        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        public IEnumerable<BuProfile> buProfileoffsetAccountPostTextItem(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfileoffsetAccountPostTextItem  with input : " + buProfile);
                response = buProfileObj.buProfileoffsetAccountPostTextItem(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfileoffsetAccountPostTextItem :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfileoffsetAccountPostTextItem :" + e.Message);
                throw;
            }
            return response;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilebemsAdminPostTextItem
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        public IEnumerable<BuProfile> buProfilebemsAdminPostTextItem(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfilebemsAdminPostTextItem with input : " + buProfile);
                response = buProfileObj.buProfilebemsAdminPostTextItem(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfilebemsAdminPostTextItem :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfilebemsAdminPostTextItem :" + e.Message);
                throw;
            }
            return response;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilePostQuery
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        public IEnumerable<BuProfile> buProfilePostQuery(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfilePostQuery with input : " + buProfile);
                response = buProfileObj.buProfilePostQuery(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfilePostQuery :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfilePostQuery :" + e.Message);
                throw;
            }
            return response;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilePreInsert
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        public IEnumerable<BuProfile> buProfilePreInsert(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfilePreInsert  with input : " + buProfile);
                response = buProfileObj.buProfilePreInsert(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfilePreInsert :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfilePreInsert :" + e.Message);
                throw;
            }
            return response;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilePreUpdate
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        public IEnumerable<BuProfile> buProfilePreUpdate(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfilePreUpdate with input : " + buProfile);
                response = buProfileObj.buProfilePreUpdate(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfilePreUpdate :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfilePreUpdate :" + e.Message);
                throw;
            }
            return response;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileWhenNewFormInstance
        ///</summary>
        ///<param name ="buProfile" ></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        public IEnumerable<BuProfile> buProfileWhenNewFormInstance(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfileWhenNewFormInstance with input : " + buProfile);
                response = buProfileObj.buProfileWhenNewFormInstance(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfileWhenNewFormInstance :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfileWhenNewFormInstance :" + e.Message);
                throw;
            }
            return response;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileWhenWindowClosed
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        public IEnumerable<BuProfile> buProfileWhenWindowClosed(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfileWhenWindowClosed with input : " + buProfile);
                response = buProfileObj.buProfileWhenWindowClosed(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfileWhenWindowClosed :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfileWhenWindowClosed :" + e.Message);
                throw;
            }
            return response;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilePostInsert
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        public IEnumerable<BuProfile> buProfilePostInsert(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfilePostInsert with input : " + buProfile);
                response = buProfileObj.buProfilePostInsert(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfilePostInsert :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfilePostInsert:" + e.Message);
                throw;
            }
            return response;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfilePostUpdate
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        public IEnumerable<BuProfile> buProfilePostUpdate(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfilePostUpdate with input : " + buProfile);
                response = buProfileObj.buProfilePostUpdate(buProfile);
                logger.Debug("Response recieved from  MCTR.Business.BuprofileBusiness.buProfilePostUpdate :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfilePostUpdate :" + e.Message);
                throw;
            }
            return response;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : GetAdmin
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<Employee> </returns>

        public IEnumerable<MctrEmployee> GetAdmin(IEnumerable<MctrEmployee> list)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.GetAdmin ");
                var responseObj = buProfileObj.GetAdmin(list);
                logger.Debug("Response recieved from  MCTR.Business.BuprofileBusiness.GetAdmin :" + response);
                return responseObj;
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from  MCTR.Business.BuprofileBusiness.GetAdmin :" + e.Message);
                throw;
            }
           
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileDelete
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>
        public IEnumerable<BuProfile> buProfileDelete(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfileDelete with input : " + buProfile);
                response = buProfileObj.buProfileDelete(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfileDelete :" + response);
            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfileDelete :" + e.Message);
                throw;
            }
            return response;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : buProfileopenLOV
        ///</summary>
        ///<param value="buProfile"></param>
        ///<returns>IEnumerable<BuProfile> </returns>

        IEnumerable<BuProfile> IBuProfileBusiness.buProfileopenLOV(IEnumerable<BuProfile> buProfile)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.BuprofileBusiness.buProfileopenLOV with input: " + buProfile);
                response = buProfileObj.buProfileopenLOV(buProfile);
                logger.Debug("Response recieved from MCTR.Business.BuprofileBusiness.buProfileopenLOV :" + response);

            }
            catch (Exception e)
            {
                logger.Error("Exception thrown from MCTR.Business.BuprofileBusiness.buProfileopenLOV :" + e.Message);
                throw;
            }
            return response;
        }
    }
}