///*************************************************************************
///
/// BOEING CONFIDENTIAL
/// ___________________
///
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
///
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be
/// covered by U.S. and Foreign Patents, patents in process,
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing.
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :

using System;
using System.Collections.Generic;
using log4net;
using MCTR.DomainEntity;
using MCTR.BusinessInterface;
using MCTR.DataAccessInterface;
using MCTR.DataAccess;

namespace MCTR.Business
{

    ///*********************************************************************
    ///<summary>
    ///jrnlhist_business is the business logic implementation class which holds all
    ///business logic in it.
    ///</summary>
    public class JrnlHistBusiness : BaseBusiness, IJrnlHistBusiness
    {
         private readonly ILog logger;

        IJrnlHistRepository repository = new JrnlHistRepository();

        public JrnlHistBusiness()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : getRgJhistDateLOV
        ///</summary>
        ///<param name = "JrnlHist"></param>
        ///<returns>IEnumerable<JrnlHist> </returns>
        public IEnumerable<JrnlHist> getRgJhistDateLOV()
        {
            try
            {
                logger.Info("Executing  MCTR.Web.Business.JrnlHistBusiness.getRgJhistDateLOV():");
                var resultlist = repository.getRgJhistDateLOV();
                logger.Info("Response received from  MCTR.Web.Business.JrnlHistBusiness.getRgJhistDateLOV(): ");
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from  MCTR.Web.Business.JrnlHistBusiness.getRgJhistDateLOV() " + e.Message);
                throw;
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : jrnlHistOnLoad
        ///</summary>
        ///<param name = "jrnlHist"></param>
        ///<returns>IEnumerable<JrnlHist> </returns>
        public IEnumerable<JrnlHist> jrnlHistOnLoad(IEnumerable<JrnlHist> jrnlHist)
        {
            try
            {
                logger.Info("Executing MCTR.Web.Business.JrnlHistBusiness.jrnlHistOnLoad()");
                var resultlist = repository.jrnlHistOnLoad(jrnlHist);
                logger.Info("Response received from MCTR.Web.Business.JrnlHistBusiness.jrnlHistOnLoad() ");
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Web.Business.JrnlHistBusiness.jrnlHistOnLoad() " + e.Message);
                throw;
            }


        }
    }
}