///*************************************************************************
///
/// BOEING CONFIDENTIAL
/// ___________________
///
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
///
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be
/// covered by U.S. and Foreign Patents, patents in process,
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing.
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :

using System;
using System.Collections.Generic;
using log4net;
using MCTR.DomainEntity;
using MCTR.BusinessInterface;
using MCTR.DataAccessInterface;
using MCTR.DataAccess;

namespace MCTR.Business
{

    ///*********************************************************************
    ///<summary>
    ///mctropenreportsbl_business is the business logic implementation class which holds all
    ///business logic in it.
    ///</summary>
    public class MctrOpenReportsBlBusiness : BaseBusiness, IMctrOpenReportsBlBusiness
    {
         private readonly ILog logger;

        IMctrOpenReportsBlRepository repository = new MctrOpenReportsBlRepository();

        public MctrOpenReportsBlBusiness()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }

        public IEnumerable<MctrBusUnit> getRgBuLOV(IEnumerable<MctrBusUnit> mctrOpenReportsBl)
        {
            try
            {
                logger.Info("Executing MCTR.Business.MctrOpenReportsBlBusiness.getRgBuLOV with request : " + mctrOpenReportsBl);
                var resultlist = repository.getRgBuLOV(mctrOpenReportsBl);
                logger.Info("Response received from  MCTR.Business.MctrIncrRatesBusiness.getRgBuLOV with request : " + mctrOpenReportsBl);
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Business.MctrOpenReportsBlBusiness.getRgBuLOV with request : " + e.Message);
                throw;
            }
        }

        public IEnumerable<MctrOpenReportsBl> selectionbutExcelWhenButtonPressed(IEnumerable<MctrOpenReportsBl> mctrOpenReportsBl)
        {
            try
            {
                logger.Info("Executing MCTR.Business.MctrOpenReportsBlBusiness.selectionbutExcelWhenButtonPressed with request : " + mctrOpenReportsBl);
                var resultlist = repository.selectionbutExcelWhenButtonPressed(mctrOpenReportsBl);
                logger.Info("Response received from  MCTR.Business.MctrIncrRatesBusiness.selectionbutExcelWhenButtonPressed with request : " + mctrOpenReportsBl);
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Business.MctrOpenReportsBlBusiness.selectionbutExcelWhenButtonPressed with request : " + e.Message);
                throw;
            }
        }

        public IEnumerable<MctrOpenReportsBl> selectionfinancialControlWhenButtonPressed(IEnumerable<MctrOpenReportsBl> mctrOpenReportsBl)
        {
            try
            {
                logger.Info("Executing MCTR.Business.MctrOpenReportsBlBusiness.selectionfinancialControlWhenButtonPressed with request : " + mctrOpenReportsBl);
                var resultlist = repository.selectionfinancialControlWhenButtonPressed(mctrOpenReportsBl);
                logger.Info("Response received from  MCTR.Business.MctrIncrRatesBusiness.selectionfinancialControlWhenButtonPressed with request : " + mctrOpenReportsBl);
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Business.MctrOpenReportsBlBusiness.selectionfinancialControlWhenButtonPressed with request : " + e.Message);
                throw;
            }
        }

        public IEnumerable<MctrOpenReportsBl> selectionoriginatorWhenButtonPressed(IEnumerable<MctrOpenReportsBl> mctrOpenReportsBl)
        {
            try
            {
                logger.Info("Executing MCTR.Business.MctrOpenReportsBlBusiness.selectionoriginatorWhenButtonPressed with request : " + mctrOpenReportsBl);
                var resultlist = repository.selectionoriginatorWhenButtonPressed(mctrOpenReportsBl);
                logger.Info("Response received from  MCTR.Business.MctrIncrRatesBusiness.selectionoriginatorWhenButtonPressed with request : " + mctrOpenReportsBl);
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Business.MctrOpenReportsBlBusiness.selectionoriginatorWhenButtonPressed with request : " + e.Message);
                throw;
            }
        }

        public IEnumerable<MctrOpenReportsBl> selectionstatusWhenButtonPressed(IEnumerable<MctrOpenReportsBl> mctrOpenReportsBl)
        {
            try
            {
                logger.Info("Executing MCTR.Business.MctrOpenReportsBlBusiness.getRgBuLOV with request : " + mctrOpenReportsBl);
                var resultlist = repository.selectionstatusWhenButtonPressed(mctrOpenReportsBl);
                logger.Info("Response received from  MCTR.Business.MctrIncrRatesBusiness.getRgBuLOV with request : " + mctrOpenReportsBl);
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Business.MctrOpenReportsBlBusiness.getRgBuLOV with request : " + e.Message);
                throw;
            }
        }
    }
}