///*************************************************************************
///
/// BOEING CONFIDENTIAL
/// ___________________
///
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
///
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be
/// covered by U.S. and Foreign Patents, patents in process,
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing.
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :

using System;
using System.Collections.Generic;
using log4net;
using MCTR.DomainEntity;
using MCTR.BusinessInterface;
using MCTR.DataAccessInterface;
using MCTR.DataAccess;

namespace MCTR.Business
{

    ///*********************************************************************
    ///<summary>
    ///mctrjrnlbydaterptbl_business is the business logic implementation class which holds all
    ///business logic in it.
    ///</summary>
    public class MctrJrnlByDateRptBlBusiness : BaseBusiness, IMctrJrnlByDateRptBlBusiness
    {
         private readonly ILog logger;
        IMctrJrnlByDateRptBlRepository repository = new MctrJrnlByDateRptBlRepository();

        public MctrJrnlByDateRptBlBusiness()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }


      public  IEnumerable<MctrJrnlByDate> selectionbutRptWhenButtonPressed(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl)
        {
            try
            {
                logger.Info("MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() with request : " + mctrJrnlByDateRptBl);
                var resultlist = repository.selectionbutRptWhenButtonPressed(mctrJrnlByDateRptBl);
                logger.Info("Response received from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad" + e.Message);
                throw;
            }
        }
       

      public  IEnumerable<MctrJrnlByDate> selectionbutExcelWhenButtonPressed(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl)
        {
            try
            {
                logger.Info("MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() with request : " + mctrJrnlByDateRptBl);
                var resultlist = repository.selectionbutExcelWhenButtonPressed(mctrJrnlByDateRptBl);
                logger.Info("Response received from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad" + e.Message);
                throw;
            }
        }
       
        public IEnumerable<MctrJrnlByDate> getRgBuLOV(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl)
        {
            try
            {
                logger.Info("MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() with request : " + mctrJrnlByDateRptBl);
                var resultlist = repository.getRgBuLOV(mctrJrnlByDateRptBl);
                logger.Info("Response received from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad" + e.Message);
                throw;
            }
        }
        public IEnumerable<MctrJrnlByDate> getRgFinCtlLOV(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl)
        {
            try
            {
                logger.Info("MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() with request : " + mctrJrnlByDateRptBl);
                var resultlist = repository.getRgFinCtlLOV(mctrJrnlByDateRptBl);
                logger.Info("Response received from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad" + e.Message);
                throw;
            }
        }
        public IEnumerable<MctrJrnlByDate> getRgOrigLOV(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl)
        {
            try
            {
                logger.Info("MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() with request : " + mctrJrnlByDateRptBl);
                var resultlist = repository.getRgOrigLOV(mctrJrnlByDateRptBl);
                logger.Info("Response received from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad" + e.Message);
                throw;
            }
        }

       public IEnumerable<MctrJrnlByDate> getRgFromDateLOV(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl)
        {
            try
            {
                logger.Info("MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() with request : " + mctrJrnlByDateRptBl);
                var resultlist = repository.getRgFromDateLOV(mctrJrnlByDateRptBl);
                logger.Info("Response received from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad" + e.Message);
                throw;
            }
        }
        public IEnumerable<MctrJrnlByDate> getRgToDateLOV(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl)
        {
            try
            {
                logger.Info("MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() with request : " + mctrJrnlByDateRptBl);
                var resultlist = repository.getRgToDateLOV(mctrJrnlByDateRptBl);
                logger.Info("Response received from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad" + e.Message);
                throw;
            }
        }
        public IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBlWhenWindowClosed(IEnumerable<MctrJrnlByDate> mctrJrnlByDateRptBl)
        {
            try
            {
                logger.Info("MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() with request : " + mctrJrnlByDateRptBl);
                var resultlist = repository.mctrJrnlByDateRptBlWhenWindowClosed(mctrJrnlByDateRptBl);
                logger.Info("Response received from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad() : " + mctrJrnlByDateRptBl);
                return resultlist;
            }
            catch (Exception e)
            {
                logger.Error("Error from MCTR.Business.LineItemBusiness.mctrLineItemMctrLineItemOnLoad" + e.Message);
                throw;
            }
        }

    
        }
    }
