///*************************************************************************
///
/// BOEING CONFIDENTIAL
/// ___________________
///
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
///
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be
/// covered by U.S. and Foreign Patents, patents in process,
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing.
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :

using System;
using System.Collections.Generic;
using log4net;
using MCTR.DomainEntity;
using MCTR.BusinessInterface;
using MCTR.DataAccessInterface;
using MCTR.DataAccess;

namespace MCTR.Business
{

    ///*********************************************************************
    ///<summary>
    ///mctroffsetformbl_business is the business logic implementation class which holds all
    ///business logic in it.
    ///</summary>
    public class MctrOffsetFormBlBusiness : BaseBusiness, IMctrOffsetFormBlBusiness
    {
         private readonly ILog logger;
        public MctrOffsetFormBlBusiness()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrOffsetMctrOffsetOnLoad
        ///</summary>
        ///<param name = "mctrOffsetFormBl"></param>
        ///<returns>IEnumerable<Status></returns>
        public IEnumerable<MctrOffsetFormBl> mctrOffsetMctrOffsetOnLoad(IEnumerable<MctrOffsetFormBl> mctrOffsetFormBl)
        {
            try
            {
                logger.Info("Executing Business : mctrOffsetMctrOffsetOnLoad()");
                IMctrOffsetFormBlRepository MctrOffsetFormBlRepository = new MctrOffsetFormBlRepository();
                var response = MctrOffsetFormBlRepository.mctrOffsetMctrOffsetOnLoad(mctrOffsetFormBl);
                logger.Info("Response received from MctrOffsetFormBlRepository.mctrOffsetMctrOffsetOnLoad() : " + response);
                return response;
            }
            catch (Exception e)
            {
                logger.Error("Error from  Mctr.DataAccess.mctrOffsetMctrOffsetOnLoad():" + e.Message);
                throw;
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrOffsetFormBlWhenNewFormInstance
        ///</summary>
        ///<param name = "mctrOffsetFormBl"></param>
        ///<returns>IEnumerable<Status></returns>
        public IEnumerable<MctrOffsetFormBl> mctrOffsetFormBlWhenNewFormInstance(IEnumerable<MctrOffsetFormBl> mctrOffsetFormBl)
        {
            try
            {
                logger.Info("Executing Business : mctrOffsetFormBlWhenNewFormInstance()");
                IMctrOffsetFormBlRepository MctrOffsetFormBlRepository = new MctrOffsetFormBlRepository();
                var response = MctrOffsetFormBlRepository.mctrOffsetFormBlWhenNewFormInstance(mctrOffsetFormBl);
                logger.Info("Response received from MctrOffsetFormBlRepository.mctrOffsetFormBlWhenNewFormInstance() : " + response);
                return response;
            }
            catch (Exception e)
            {
                logger.Error("Error from  Mctr.DataAccess.mctrOffsetFormBlWhenNewFormInstance():" + e.Message);
                throw;
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrOffsetFormBlWhenWindowClosed
        ///</summary>
        ///<param name = "mctrOffsetFormBl"></param>
        ///<returns>IEnumerable<Status></returns>
        public IEnumerable<MctrOffsetFormBl> mctrOffsetFormBlWhenWindowClosed(IEnumerable<MctrOffsetFormBl> mctrOffsetFormBl)
        {
            try
            {
                logger.Info("Executing Business : mctrOffsetFormBlWhenWindowClosed()");
                IMctrOffsetFormBlRepository MctrOffsetFormBlRepository = new MctrOffsetFormBlRepository();
                var response = MctrOffsetFormBlRepository.mctrOffsetFormBlWhenWindowClosed(mctrOffsetFormBl);
                logger.Info("Response received from MctrOffsetFormBlRepository.mctrOffsetFormBlWhenWindowClosed() : " + response);

                return response;
            }
            catch (Exception e)
            {
                logger.Error("Error from  Mctr.DataAccess.mctrOffsetFormBlWhenWindowClosed():" + e.Message);
                throw;
            }
        }
    }
}