///*************************************************************************
///
/// BOEING CONFIDENTIAL
/// ___________________
///
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
///
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be
/// covered by U.S. and Foreign Patents, patents in process,
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing.
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :

using System;
using System.Collections.Generic;
using log4net;
using MCTR.DomainEntity;
using MCTR.BusinessInterface;
using MCTR.DataAccessInterface;
using MCTR.DataAccess;

namespace MCTR.Business
{

    ///*********************************************************************
    ///<summary>
    ///percheckbl_business is the business logic implementation class which holds all
    ///business logic in it.
    ///</summary>
    public class PerCheckBlBusiness : BaseBusiness, IPerCheckBlBusiness
    {
         private readonly ILog logger;

        public PerCheckBlBusiness()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : perCheckPerCheckOnLoad
        ///</summary>
        ///<param name = "PerCheckBl"></param>
        ///<returns>IEnumerable<PerCheckBl> </returns>

        public IEnumerable<PerCheckBl> perCheckPerCheckOnLoad(IEnumerable<PerCheckBl> perCheckBl)
        {
            try
            {
                logger.Info("Executing  Business : perCheckPerCheckOnLoad() with request : " + perCheckBl);
                IPerCheckBlRepository PerCheckBlRepository = new PerCheckBlRepository();
                var response = PerCheckBlRepository.perCheckPerCheckOnLoad(perCheckBl);
                logger.Info("Response received from PerCheckBlRepository.perCheckPerCheckOnLoad() : " + response);
                return response;
            }
            catch (Exception e)
            {
                logger.Info("Response received from JrnlWeekRepository.jrnlWeekJrnlWeekOnLoad() : " + e.Message);

                throw;
            }
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : perCheckBlWhenNewFormInstance
        ///</summary>
        ///<param name = "PerCheckBl"></param>
        ///<returns>IEnumerable<PerCheckBl> </returns>
        public IEnumerable<PerCheckBl> perCheckBlWhenNewFormInstance(IEnumerable<PerCheckBl> perCheckBl)
        {
            try
            {
                logger.Info("Executing Business: perCheckBlWhenNewFormInstance() with request : " + perCheckBl);
                IPerCheckBlRepository PerCheckBlRepository = new PerCheckBlRepository();
                var response = PerCheckBlRepository.perCheckBlWhenNewFormInstance(perCheckBl);
                logger.Info("Response received from PerCheckBlRepository.perCheckBlWhenNewFormInstance() : " + response);
                return response;
            }
            catch (Exception e)
            {
                logger.Info("Response received from JrnlWeekRepository.jrnlWeekJrnlWeekOnLoad() : " + e.Message);

                throw;
            }

        }
        ///*************************************************************
        ///<summary>
        ///Method Name : perCheckBlWhenWindowClosed
        ///</summary>
        ///<param name = "PerCheckBl"></param>
        ///<returns>IEnumerable<PerCheckBl> </returns>
        public IEnumerable<PerCheckBl> perCheckBlWhenWindowClosed(IEnumerable<PerCheckBl> perCheckBl)
        {
            try
            {
                logger.Info("Executing Business: perCheckBlWhenWindowClosed() with request : " + perCheckBl);
                IPerCheckBlRepository PerCheckBlRepository = new PerCheckBlRepository();
                var response = PerCheckBlRepository.perCheckBlWhenWindowClosed(perCheckBl);
                logger.Info("Response received from PerCheckBlRepository.perCheckBlWhenWindowClosed() : " + response);
                return response;
            }
            catch (Exception e)
            {
                logger.Info("Response received from JrnlWeekRepository.jrnlWeekJrnlWeekOnLoad() : " + e.Message);

                throw;
            }

        }
    }
}