///*************************************************************************
///
/// BOEING CONFIDENTIAL
/// ___________________
///
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
///
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be
/// covered by U.S. and Foreign Patents, patents in process,
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing.
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :
using log4net;
using MCTR.DomainEntity;
using MCTR.BusinessInterface;
using MCTR.DataAccessInterface;
using MCTR.DataAccess;
using System;
using System.Collections.Generic;

namespace MCTR.Business
{

    ///*********************************************************************
    ///<summary>
    ///stathistbl_business is the business logic implementation class which holds all
    ///business logic in it.
    ///</summary>
    public class StatHistBlBusiness : BaseBusiness, IStatHistBlBusiness
    {
         private readonly ILog logger;
        IStatHistBlRepository statHistBlRepository;

        public StatHistBlBusiness()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
            statHistBlRepository = new StatHistBlRepository();
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>

        public IEnumerable<StatusHistory> mctrStatusHistMctrStatusHistOnLoad(IEnumerable<StatusHistory> statHistBl)
        {
            try
            {
                logger.Debug("Executing MCTR.Business.StatHistBlBusiness.mctrStatusHistMctrStatusHistOnLoad with input : ");
                var response = statHistBlRepository.mctrStatusHistMctrStatusHistOnLoad(statHistBl);
                logger.Debug("Response recieved from StatHistBlBusiness.mctrStatusHistMctrStatusHistOnLoad :" + response);
                return response;
            }
            catch (Exception ex)
            {
                logger.Debug("Exception Occured at MCTR.Business.StatHistBlBusiness.mctrStatusHistMctrStatusHistOnLoad:" + ex.Message);
                throw;
            }
        

    }
    ///*************************************************************
    ///<summary>
    ///Method Name : mctrStatusHistMctrStatusHistOnLoad
    ///</summary>
    ///<param name = "statHistBl"></param>
    ///<returns>IEnumerable<StatusHistory> </returns>
    public IEnumerable<StatHistBl> mctrStatusHisthistButtonCloseWhenButtonPressed(IEnumerable<StatHistBl> statHistBl)
        {
            //exit_form
            return null;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>
        public IEnumerable<StatHistBl> mctrStatusHistPostQuery(IEnumerable<StatHistBl> statHistBl)
        {

            return null;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>
        public IEnumerable<StatHistBl> selectionrgrpSortWhenRadioChanged(IEnumerable<StatHistBl> statHistBl)
        {

            return null;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>

        public IEnumerable<StatHistBl> selectionbutToXlsWhenButtonPressed(IEnumerable<StatHistBl> statHistBl)
        {

            return null;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>
        public IEnumerable<StatHistBl> webutildummyWhenButtonPressed(IEnumerable<StatHistBl> statHistBl)
        {
            // webutil_core.customeventhandler(system.custom_item_event,system.custom_item_event_parameters);
            return null;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>
        public IEnumerable<StatHistBl> webutilwebutilClientinfoFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl)
        {
            //webutil_core.customeventhandler(system.custom_item_event,system.custom_item_event_parameters);
            return null;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>
        public IEnumerable<StatHistBl> webutilwebutilFileFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl)
        {
            //webutil_core.customeventhandler(system.custom_item_event,system.custom_item_event_parameters);
            return null;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>
        public IEnumerable<StatHistBl> webutilwebutilHostFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl)
        {
            // webutil_core.customeventhandler(system.custom_item_event,system.custom_item_event_parameters);
            return null;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>
        public IEnumerable<StatHistBl> webutilwebutilSessionFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl)
        {
            // webutil_core.customeventhandler(system.custom_item_event,system.custom_item_event_parameters);
            return null;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>
        public IEnumerable<StatHistBl> webutilwebutilFiletransferFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl)
        {
            //  webutil_core.customeventhandler(system.custom_item_event,system.custom_item_event_parameters);
            return null;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>

        public IEnumerable<StatHistBl> webutilwebutilOleFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl)
        {
            //  webutil_core.customeventhandler(system.custom_item_event,system.custom_item_event_parameters);
            return null;
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>
        public void stathistblwhennewforminstance()
        {

        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>

        public IEnumerable<StatHistBl> webutilwebutilCApiFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl)
        {
            throw new NotImplementedException();
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>
        public IEnumerable<StatHistBl> webutilwebutilBrowserFunctionsWhenCustomItemEvent(IEnumerable<StatHistBl> statHistBl)
        {
            throw new NotImplementedException();
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>
        public IEnumerable<StatHistBl> statHistBlWhenNewFormInstance(IEnumerable<StatHistBl> statHistBl)
        {
            throw new NotImplementedException();
        }
        ///*************************************************************
        ///<summary>
        ///Method Name : mctrStatusHistMctrStatusHistOnLoad
        ///</summary>
        ///<param name = "statHistBl"></param>
        ///<returns>IEnumerable<StatusHistory> </returns>

        public IEnumerable<StatHistBl> statHistBlWhenWindowClosed(IEnumerable<StatHistBl> statHistBl)
        {
            throw new NotImplementedException();
        }
    }
}