///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Threading.Tasks;
using System.Web.Mvc;
using System.Net.Http;
using System.Net.Http.Headers;

using log4net;

using MCTR.DomainEntity;

namespace MCTR.Web.Handlers
{
    ///*********************************************************************
    ///<summary>
    ///MctrOhFormBlHandler provides a level of abstraction for consuming the REST api.
    ///</summary>
    public class MctrOhFormBlHandler
    {
         private readonly ILog logger;

        public MctrOhFormBlHandler()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }


        ///*************************************************************
        ///<summary>
        ///Method Name : mctrOhMctrOhOnLoad
        ///</summary>
        ///<param name = "MctrOhFormBl"></param>
        ///<returns>IEnumerable<MctrOhFormBl> </returns>

        public IEnumerable<MctrOhFormBl> mctrOhMctrOhOnLoad(MctrOhFormBl mctrOhFormBl)
        {
            try
            {
                logger.Debug("Executing mctrOhMctrOhOnLoad rest service handler.");
                string restApiPath = "MctrOhFormBlService/mctrOhMctrOhOnLoad";
                logger.Info("Invoking Rest API : " + restApiPath + " with Request : " + mctrOhFormBl);
                var response = HandlerUtil<MctrOhFormBl>.RestPostProcessor(restApiPath, mctrOhFormBl);
                logger.Info("Response received form Rest API : " + restApiPath + " : " + response);
                return response;
            }
            catch (Exception e)
            {
                logger.Error("Error from  Mctr.Handler.mctrOhMctrOhOnLoad():" + e.Message);
                throw;
                
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrOhFormBlWhenNewFormInstance
        ///</summary>
        ///<param name = "MctrOhFormBl"></param>
        ///<returns>IEnumerable<MctrOhFormBl> </returns>

        public IEnumerable<MctrOhFormBl> mctrOhFormBlWhenNewFormInstance(MctrOhFormBl mctrOhFormBl)
        {
            if (mctrOhFormBl != null)
            {
                logger.Debug("Executing mctrOhFormBlWhenNewFormInstance rest service handler.");
                string restApiPath = "MctrOhFormBlService/mctrOhFormBlWhenNewFormInstance";
                logger.Info("Invoking Rest API : " + restApiPath + " with Request : " + mctrOhFormBl);
                var response = HandlerUtil<MctrOhFormBl>.RestPostProcessor(restApiPath, mctrOhFormBl);
                logger.Info("Response received form Rest API : " + restApiPath + " : " + response);
                return response;
            }
            else
            {
                logger.Info("The passed parameter mctrOhFormBl is NULL.");
                return null;
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrOhFormBlWhenWindowClosed
        ///</summary>
        ///<param name = "MctrOhFormBl"></param>
        ///<returns>IEnumerable<MctrOhFormBl> </returns>

        public IEnumerable<MctrOhFormBl> mctrOhFormBlWhenWindowClosed(MctrOhFormBl mctrOhFormBl)
        {
            if (mctrOhFormBl != null)
            {
                logger.Debug("Executing mctrOhFormBlWhenWindowClosed rest service handler.");
                string restApiPath = "MctrOhFormBlService/mctrOhFormBlWhenWindowClosed";
                logger.Info("Invoking Rest API : " + restApiPath + " with Request : " + mctrOhFormBl);
                var response = HandlerUtil<MctrOhFormBl>.RestPostProcessor(restApiPath, mctrOhFormBl);
                logger.Info("Response received form Rest API : " + restApiPath + " : " + response);
                return response;
            }
            else
            {
                logger.Info("The passed parameter mctrOhFormBl is NULL.");
                return null;
            }


        }

    }
}

