///*************************************************************************
/// 
/// BOEING CONFIDENTIAL
/// ___________________
/// 
///  BOEING is a trademark of Boeing Management Company.
///
///  Copyright © 2016 Boeing. All rights reserved.
/// 
/// NOTICE:  All information contained herein is, and remains
/// the property of Boeing and its suppliers, if any.  
/// The intellectual and technical concepts contained
/// herein are proprietary to Boeing and its suppliers and may be 
/// covered by U.S. and Foreign Patents, patents in process, 
/// and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material
/// is strictly forbidden unless prior written permission is obtained
/// from Boeing. 
///

///************************************************************************
/// Author           : Generated by ATMA ®
/// Revision History :  

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Threading.Tasks;
using System.Web.Mvc;
using System.Net.Http;
using System.Net.Http.Headers;

using log4net;

using MCTR.DomainEntity;

namespace MCTR.Web.Handlers
{
    ///*********************************************************************
    ///<summary>
    ///MctrWkipJrnlsBlHandler provides a level of abstraction for consuming the REST api.
    ///</summary>
    public class MctrWkipJrnlsBlHandler
    {
         private readonly ILog logger;

        public MctrWkipJrnlsBlHandler()
        {
            logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        }


        ///*************************************************************
        ///<summary>
        ///Method Name : jrnlWeekJrnlWeekOnLoad
        ///</summary>
        ///<param name = "MctrWkipJrnlsBl"></param>
        ///<returns>IEnumerable<MctrWkipJrnlsBl> </returns>

        public IEnumerable<MctrWkipJrnlsBl> jrnlWeekJrnlWeekOnLoad(MctrWkipJrnlsBl mctrWkipJrnlsBl)
        {
            try
            {

                logger.Debug("Executing jrnlWeekJrnlWeekOnLoad rest service handler.");
                string restApiPath = "MctrWkipJrnlsBlService/jrnlWeekJrnlWeekOnLoad";
                logger.Info("Invoking Rest API : " + restApiPath + " with Request : " + mctrWkipJrnlsBl);
                var response = HandlerUtil<MctrWkipJrnlsBl>.RestPostProcessor(restApiPath, mctrWkipJrnlsBl);
                logger.Info("Response received form Rest API : " + restApiPath + " : " + response);
                return response;
            }
            catch (Exception e)
            {
                logger.Info("Response received from JrnlWeekRepository.jrnlWeekJrnlWeekOnLoad() : " + e.Message);

                throw;
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrWkipJrnlsBlWhenNewFormInstance
        ///</summary>
        ///<param name = "MctrWkipJrnlsBl"></param>
        ///<returns>IEnumerable<MctrWkipJrnlsBl> </returns>

        public IEnumerable<MctrWkipJrnlsBl> mctrWkipJrnlsBlWhenNewFormInstance(MctrWkipJrnlsBl mctrWkipJrnlsBl)
        {
            try
            {

                logger.Debug("Executing mctrWkipJrnlsBlWhenNewFormInstance rest service handler.");
                string restApiPath = "MctrWkipJrnlsBl/mctrWkipJrnlsBlWhenNewFormInstance";
                logger.Info("Invoking Rest API : " + restApiPath + " with Request : " + mctrWkipJrnlsBl);
                var response = HandlerUtil<MctrWkipJrnlsBl>.RestPostProcessor(restApiPath, mctrWkipJrnlsBl);
                logger.Info("Response received form Rest API : " + restApiPath + " : " + response);
                return response;
            }
            catch (Exception e)
            {
                logger.Info("Response received from JrnlWeekRepository.jrnlWeekJrnlWeekOnLoad() : " + e.Message);

                throw;
            }
        }

        ///*************************************************************
        ///<summary>
        ///Method Name : mctrWkipJrnlsBlWhenWindowClosed
        ///</summary>
        ///<param name = "MctrWkipJrnlsBl"></param>
        ///<returns>IEnumerable<MctrWkipJrnlsBl> </returns>

        public IEnumerable<MctrWkipJrnlsBl> mctrWkipJrnlsBlWhenWindowClosed(MctrWkipJrnlsBl mctrWkipJrnlsBl)
        {
            try
            {

                logger.Debug("Executing mctrWkipJrnlsBlWhenWindowClosed rest service handler.");
                string restApiPath = "MctrWkipJrnlsBl/mctrWkipJrnlsBlWhenWindowClosed";
                logger.Info("Invoking Rest API : " + restApiPath + " with Request : " + mctrWkipJrnlsBl);
                var response = HandlerUtil<MctrWkipJrnlsBl>.RestPostProcessor(restApiPath, mctrWkipJrnlsBl);
                logger.Info("Response received form Rest API : " + restApiPath + " : " + response);
                return response;
            }
            catch (Exception e)
            {
                logger.Info("Response received from JrnlWeekRepository.jrnlWeekJrnlWeekOnLoad() : " + e.Message);

                throw;
            }
        }


    }

}

